### ISSUE TITLE
IceGrid/replication failures on Windows 10

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#1248]
```
Running on ice-dist-windows-windows10_vs2019_x86-test-3.7
*** [84/92] Running cpp/IceGrid/replication tests ***
[ running IceGrid test - 01/19/21 11:43:07 ]
- Config: ssl,mx,Release,Win32
starting IceGrid registry Master... (C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142-default\cpp\msbuild\packages\zeroc.ice.v142.3.7.5\build\native\bin\Win32\Release\icegridregistry.exe --Ice.Default.Host=127.0.0.1 --Ice.Warn.Connections=0 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --Ice.Admin.Endpoints="tcp -h 127.0.0.1" --Ice.Admin.InstanceName=Server --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --Ice.Plugin.IceSSL=IceSSL:createIceSSL --IceSSL.Password=password --IceSSL.DefaultDir=C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142-default\certs --IceSSL.CAs=cacert.pem --IceSSL.CertFile=server.p12 --Ice.NullHandleAbort=1 --Ice.PrintStackTraces=1 --IceGrid.InstanceName=TestIceGrid --IceGrid.Registry.PermissionsVerifier=TestIceGrid/NullPermissionsVerifier --IceGrid.Registry.AdminPermissionsVerifier=TestIceGrid/NullPermissionsVerifier --IceGrid.Registry.SSLPermissionsVerifier=TestIceGrid/NullSSLPermissionsVerifier --IceGrid.Registry.AdminSSLPermissionsVerifier=TestIceGrid/NullSSLPermissionsVerifier --IceGrid.Registry.Server.Endpoints=default --IceGrid.Registry.Internal.Endpoints=default --IceGrid.Registry.Client.Endpoints="default -p 12030" --IceGrid.Registry.Discovery.Port=12109 --IceGrid.Registry.SessionManager.Endpoints=default --IceGrid.Registry.AdminSessionManager.Endpoints=default --IceGrid.Registry.SessionTimeout=60 --IceGrid.Registry.ReplicaName=Master --Ice.ProgramName=Master --Ice.PrintAdapterReady=1 --Ice.ThreadPool.Client.SizeWarn=0 --IceGrid.Registry.LMDB.MapSize=1 --IceGrid.Registry.LMDB.Path=C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142-default\cpp\test\IceGrid\replication/registry-Master --IceGrid.Registry.Client.ThreadPool.SizeWarn=0 --IceGrid.Registry.DefaultTemplates="C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142-default\cpp\config\templates.xml" --IceGrid.Registry.Discovery.Interface=127.0.0.1 env={'PATH': 'C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice\\builds\\ice-v142-default\\cpp\\test\\Common\\msbuild\\Win32\\Release;C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice\\builds\\ice-v142-default\\cpp\\msbuild\\packages\\zeroc.ice.v142.3.7.5\\build\\native\\bin\\Win32\\Release'})
ok
starting IceGrid registry Slave1... (C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142-default\cpp\msbuild\packages\zeroc.ice.v142.3.7.5\build\native\bin\Win32\Release\icegridregistry.exe --Ice.Default.Host=127.0.0.1 --Ice.Warn.Connections=0 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --Ice.Admin.Endpoints="tcp -h 127.0.0.1" --Ice.Admin.InstanceName=Server --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --Ice.Plugin.IceSSL=IceSSL:createIceSSL --IceSSL.Password=password --IceSSL.DefaultDir=C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142-default\certs --IceSSL.CAs=cacert.pem --IceSSL.CertFile=server.p12 --Ice.NullHandleAbort=1 --Ice.PrintStackTraces=1 --IceGrid.InstanceName=TestIceGrid --IceGrid.Registry.PermissionsVerifier=TestIceGrid/NullPermissionsVerifier --IceGrid.Registry.AdminPermissionsVerifier=TestIceGrid/NullPermissionsVerifier --IceGrid.Registry.SSLPermissionsVerifier=TestIceGrid/NullSSLPermissionsVerifier --IceGrid.Registry.AdminSSLPermissionsVerifier=TestIceGrid/NullSSLPermissionsVerifier --IceGrid.Registry.Server.Endpoints=default --IceGrid.Registry.Internal.Endpoints=default --IceGrid.Registry.Client.Endpoints="default -p 12031" --IceGrid.Registry.Discovery.Port=12109 --IceGrid.Registry.SessionManager.Endpoints=default --IceGrid.Registry.AdminSessionManager.Endpoints=default --IceGrid.Registry.SessionTimeout=60 --IceGrid.Registry.ReplicaName=Slave1 --Ice.ProgramName=Slave1 --Ice.PrintAdapterReady=1 --Ice.ThreadPool.Client.SizeWarn=0 --IceGrid.Registry.LMDB.MapSize=1 --IceGrid.Registry.LMDB.Path=C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142-default\cpp\test\IceGrid\replication/registry-Slave1 --IceGrid.Registry.Client.ThreadPool.SizeWarn=0 --IceGrid.Registry.DefaultTemplates="C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142-default\cpp\config\templates.xml" --IceGrid.Registry.Discovery.Interface=127.0.0.1 --Ice.Default.Locator="TestIceGrid/Locator:default -p 12030" env={'PATH': 'C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice\\builds\\ice-v142-default\\cpp\\test\\Common\\msbuild\\Win32\\Release;C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice\\builds\\ice-v142-default\\cpp\\msbuild\\packages\\zeroc.ice.v142.3.7.5\\build\\native\\bin\\Win32\\Release'})
ok
starting IceGrid node localnode... (C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142-default\cpp\msbuild\packages\zeroc.ice.v142.3.7.5\build\native\bin\Win32\Release\icegridnode.exe --Ice.Default.Host=127.0.0.1 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --Ice.Admin.Endpoints="tcp -h 127.0.0.1" --Ice.Admin.InstanceName=Server --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --Ice.Plugin.IceSSL=IceSSL:createIceSSL --IceSSL.Password=password --IceSSL.DefaultDir=C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142-default\certs --IceSSL.CAs=cacert.pem --IceSSL.CertFile=server.p12 --Ice.NullHandleAbort=1 --Ice.PrintStackTraces=1 --IceGrid.InstanceName=TestIceGrid --IceGrid.Node.Endpoints=default --IceGrid.Node.WaitTime=240 --Ice.ProgramName=icegridnode --IceGrid.Node.Trace.Replica=0 --IceGrid.Node.Trace.Activator=0 --IceGrid.Node.Trace.Adapter=0 --IceGrid.Node.Trace.Server=0 --IceGrid.Node.ThreadPool.SizeWarn=0 --IceGrid.Node.PrintServersReady=node --IceGrid.Node.Name=localnode --IceGrid.Node.Data=C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142-default\cpp\test\IceGrid\replication/node-localnode --IceGrid.Node.PropertiesOverride="Ice.Default.Host=127.0.0.1 Ice.Warn.Connections=1 Ice.Default.Protocol=ssl Ice.IPv6=0 Ice.Admin.Endpoints=\"tcp -h 127.0.0.1\" Ice.Admin.InstanceName=Server IceMX.Metrics.Debug.GroupBy=id IceMX.Metrics.Parent.GroupBy=parent IceMX.Metrics.All.GroupBy=none Ice.Plugin.IceSSL=IceSSL:createIceSSL IceSSL.Password=password IceSSL.DefaultDir=C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice\\builds\\ice-v142-default\\certs IceSSL.CAs=cacert.pem IceSSL.CertFile=server.p12 Ice.NullHandleAbort=1 Ice.PrintStackTraces=1 Ice.ThreadPool.Server.Size=1 Ice.ThreadPool.Server.SizeMax=3 Ice.ThreadPool.Server.SizeWarn=0 Ice.PrintAdapterReady=1" --Ice.Default.Locator="TestIceGrid/Locator:default -p 12030:default -p 12031" env={'PATH': 'C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice\\builds\\ice-v142-default\\cpp\\test\\Common\\msbuild\\Win32\\Release;C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice\\builds\\ice-v142-default\\cpp\\msbuild\\packages\\zeroc.ice.v142.3.7.5\\build\\native\\bin\\Win32\\Release;C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice\\builds\\ice-v142-default\\cpp\\test\\Common\\msbuild\\Win32\\Release;C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice\\builds\\ice-v142-default\\cpp\\msbuild\\packages\\zeroc.ice.v142.3.7.5\\build\\native\\bin\\Win32\\Release'})
ok
(C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142-default\cpp\msbuild\packages\zeroc.ice.v142.3.7.5\build\native\bin\Win32\Release\icegridadmin.exe --Ice.Default.Host=127.0.0.1 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --Ice.Admin.Endpoints="tcp -h 127.0.0.1" --Ice.Admin.InstanceName=Client --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --Ice.Plugin.IceSSL=IceSSL:createIceSSL --IceSSL.Password=password --IceSSL.DefaultDir=C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142-default\certs --IceSSL.CAs=cacert.pem --IceSSL.CertFile=client.p12 --Ice.NullHandleAbort=1 --Ice.PrintStackTraces=1 --Ice.Default.Locator="TestIceGrid/Locator:default -p 12030" --IceGridAdmin.Username=admin1 --IceGridAdmin.Password=test1 -r Master -e "application add -n application.xml test.dir=C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice\\builds\\ice-v142-default\\cpp\\test\\IceGrid\\replication java.exe=\"C:\\\\Program Files (x86)\\\\Java\\\\jdk1.8.0_211\\\\bin\\\\java\" icebox.exe=C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice\\builds\\ice-v142-default\\cpp\\msbuild\\packages\\zeroc.ice.v142.3.7.5\\build\\native\\bin\\Win32\\Release\\icebox.exe icegridnode.exe=C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice\\builds\\ice-v142-default\\cpp\\msbuild\\packages\\zeroc.ice.v142.3.7.5\\build\\native\\bin\\Win32\\Release\\icegridnode.exe glacier2router.exe=C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice\\builds\\ice-v142-default\\cpp\\msbuild\\packages\\zeroc.ice.v142.3.7.5\\build\\native\\bin\\Win32\\Release\\glacier2router.exe icepatch2server.exe=C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice\\builds\\ice-v142-default\\cpp\\msbuild\\packages\\zeroc.ice.v142.3.7.5\\build\\native\\bin\\Win32\\Release\\icepatch2server.exe icegridregistry.exe=C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice\\builds\\ice-v142-default\\cpp\\msbuild\\packages\\zeroc.ice.v142.3.7.5\\build\\native\\bin\\Win32\\Release\\icegridregistry.exe properties-override=\"Ice.Default.Host=127.0.0.1 Ice.Warn.Connections=1 Ice.Default.Protocol=ssl Ice.IPv6=0 Ice.Admin.Endpoints=\\\"tcp -h 127.0.0.1\\\" Ice.Admin.InstanceName=Server IceMX.Metrics.Debug.GroupBy=id IceMX.Metrics.Parent.GroupBy=parent IceMX.Metrics.All.GroupBy=none Ice.Plugin.IceSSL=IceSSL:createIceSSL IceSSL.Password=password IceSSL.DefaultDir=C:\\\\Users\\\\vagrant\\\\workspace\\\\ice-dist\\\\3.7\\\\dist-utils\\\\build\\\\ice\\\\builds\\\\ice-v142-default\\\\certs IceSSL.CAs=cacert.pem IceSSL.CertFile=server.p12 Ice.NullHandleAbort=1 Ice.PrintStackTraces=1 Ice.ThreadPool.Server.Size=1 Ice.ThreadPool.Server.SizeMax=3 Ice.ThreadPool.Server.SizeWarn=0 Ice.PrintAdapterReady=1\" dotnet.exe=\"C:\\\\Program Files\\\\dotnet\\\\dotnet.exe\" server.dir=msbuild\\server\\Win32\\Release " env={'PATH': 'C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice\\builds\\ice-v142-default\\cpp\\test\\Common\\msbuild\\Win32\\Release;C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice\\builds\\ice-v142-default\\cpp\\msbuild\\packages\\zeroc.ice.v142.3.7.5\\build\\native\\bin\\Win32\\Release'})
(C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142-default\cpp\test\IceGrid\replication\msbuild\client\Win32\Release\client.exe --Ice.Default.Host=127.0.0.1 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --Ice.Admin.Endpoints="tcp -h 127.0.0.1" --Ice.Admin.InstanceName=Client --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --Ice.Plugin.IceSSL=IceSSL:createIceSSL --IceSSL.Password=password --IceSSL.DefaultDir=C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142-default\certs --IceSSL.CAs=cacert.pem --IceSSL.CertFile=client.p12 --Ice.NullHandleAbort=1 --Ice.PrintStackTraces=1 --Ice.Default.Locator="TestIceGrid/Locator:default -p 12030" --ServerDir=msbuild\server\Win32\Release --Ice.Trace.Network=2 --Ice.Trace.Retry=1 --Ice.Trace.Protocol=1 --Ice.ACM.Client.Heartbeat=2 --Ice.LogFile=C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142-default\cpp\test\IceGrid\replication\client-011921-1143.log env={'PATH': 'C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice\\builds\\ice-v142-default\\cpp\\test\\Common\\msbuild\\Win32\\Release;C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice\\builds\\ice-v142-default\\cpp\\msbuild\\packages\\zeroc.ice.v142.3.7.5\\build\\native\\bin\\Win32\\Release'})
error: C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142\cpp\src\Ice\ConnectionI.cpp:2194: ::Ice::ConnectTimeoutException:
timeout while establishing a connection
saved C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142-default\cpp\test\IceGrid\replication\client-011921-1143.log
(C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142-default\cpp\msbuild\packages\zeroc.ice.v142.3.7.5\build\native\bin\Win32\Release\icegridadmin.exe --Ice.Default.Host=127.0.0.1 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --Ice.Admin.Endpoints="tcp -h 127.0.0.1" --Ice.Admin.InstanceName=Client --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --Ice.Plugin.IceSSL=IceSSL:createIceSSL --IceSSL.Password=password --IceSSL.DefaultDir=C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142-default\certs --IceSSL.CAs=cacert.pem --IceSSL.CertFile=client.p12 --Ice.NullHandleAbort=1 --Ice.PrintStackTraces=1 --Ice.Default.Locator="TestIceGrid/Locator:default -p 12030" --IceGridAdmin.Username=admin1 --IceGridAdmin.Password=test1 -r Master -e "application remove Test" env={'PATH': 'C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice\\builds\\ice-v142-default\\cpp\\test\\Common\\msbuild\\Win32\\Release;C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice\\builds\\ice-v142-default\\cpp\\msbuild\\packages\\zeroc.ice.v142.3.7.5\\build\\native\\bin\\Win32\\Release'})
(C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142-default\cpp\msbuild\packages\zeroc.ice.v142.3.7.5\build\native\bin\Win32\Release\icegridadmin.exe --Ice.Default.Host=127.0.0.1 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --Ice.Admin.Endpoints="tcp -h 127.0.0.1" --Ice.Admin.InstanceName=Client --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --Ice.Plugin.IceSSL=IceSSL:createIceSSL --IceSSL.Password=password --IceSSL.DefaultDir=C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142-default\certs --IceSSL.CAs=cacert.pem --IceSSL.CertFile=client.p12 --Ice.NullHandleAbort=1 --Ice.PrintStackTraces=1 --Ice.Default.Locator="TestIceGrid/Locator:default -p 12030" --IceGridAdmin.Username=admin1 --IceGridAdmin.Password=test1 -r Master -e "node shutdown localnode" env={'PATH': 'C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice\\builds\\ice-v142-default\\cpp\\test\\Common\\msbuild\\Win32\\Release;C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice\\builds\\ice-v142-default\\cpp\\msbuild\\packages\\zeroc.ice.v142.3.7.5\\build\\native\\bin\\Win32\\Release'})
(C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142-default\cpp\msbuild\packages\zeroc.ice.v142.3.7.5\build\native\bin\Win32\Release\icegridadmin.exe --Ice.Default.Host=127.0.0.1 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --Ice.Admin.Endpoints="tcp -h 127.0.0.1" --Ice.Admin.InstanceName=Client --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --Ice.Plugin.IceSSL=IceSSL:createIceSSL --IceSSL.Password=password --IceSSL.DefaultDir=C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142-default\certs --IceSSL.CAs=cacert.pem --IceSSL.CertFile=client.p12 --Ice.NullHandleAbort=1 --Ice.PrintStackTraces=1 --Ice.Default.Locator="TestIceGrid/Locator:default -p 12030" --IceGridAdmin.Username=admin1 --IceGridAdmin.Password=test1 -r Master -e "registry shutdown Master" env={'PATH': 'C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice\\builds\\ice-v142-default\\cpp\\test\\Common\\msbuild\\Win32\\Release;C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice\\builds\\ice-v142-default\\cpp\\msbuild\\packages\\zeroc.ice.v142.3.7.5\\build\\native\\bin\\Win32\\Release'})
(C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142-default\cpp\msbuild\packages\zeroc.ice.v142.3.7.5\build\native\bin\Win32\Release\icegridadmin.exe --Ice.Default.Host=127.0.0.1 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --Ice.Admin.Endpoints="tcp -h 127.0.0.1" --Ice.Admin.InstanceName=Client --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --Ice.Plugin.IceSSL=IceSSL:createIceSSL --IceSSL.Password=password --IceSSL.DefaultDir=C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142-default\certs --IceSSL.CAs=cacert.pem --IceSSL.CertFile=client.p12 --Ice.NullHandleAbort=1 --Ice.PrintStackTraces=1 --Ice.Default.Locator="TestIceGrid/Locator:default -p 12031" --IceGridAdmin.Username=admin1 --IceGridAdmin.Password=test1 -r Slave1 -e "registry shutdown Slave1" env={'PATH': 'C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice\\builds\\ice-v142-default\\cpp\\test\\Common\\msbuild\\Win32\\Release;C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice\\builds\\ice-v142-default\\cpp\\msbuild\\packages\\zeroc.ice.v142.3.7.5\\build\\native\\bin\\Win32\\Release'})
Traceback (most recent call last):
  File "C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142-default\cpp\..\scripts\Util.py", line 1714, in run
    self.runWithDriver(current)
  File "C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142-default\cpp\..\scripts\IceGridUtil.py", line 286, in runWithDriver
    current.driver.runClientServerTestCase(current)
  File "C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142-default\cpp\..\scripts\LocalDriver.py", line 565, in runClientServerTestCase
    self.runner.runClientSide(client, current, host)
  File "C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142-default\cpp\..\scripts\LocalDriver.py", line 197, in runClientSide
    testcase._runClientSide(current, host)
  File "C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142-default\cpp\..\scripts\Util.py", line 1691, in _runClientSide
    self.runClientSide(current)
  File "C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142-default\cpp\..\scripts\Util.py", line 1583, in runClientSide
    self._runClient(current, client)
  File "C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142-default\cpp\..\scripts\Util.py", line 1703, in _runClient
    client.run(current)
  File "C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142-default\cpp\..\scripts\Util.py", line 1207, in run
    process.waitSuccess(exitstatus=exitstatus, timeout=30)
  File "C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142-default\cpp\..\scripts\Expect.py", line 632, in waitSuccess
    self.testExitStatus(exitstatus)
  File "C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142-default\cpp\..\scripts\Expect.py", line 667, in testExitStatus
    test(self.exitstatus, exitstatus)
  File "C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142-default\cpp\..\scripts\Expect.py", line 653, in test
    raise RuntimeError("unexpected exit status: expected: {0}, got {1}\n".format(expected, result))
RuntimeError: unexpected exit status: expected: 0, got 1
```

**Comment by bentoi** [comment]
We should check the content of the client log file to check the network tracing.

**Comment by pepone** [comment]
The log file is not there anymore
