### ISSUE TITLE
Ice/faultTolerance test hang on Windows 10

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#1251]
```
$ jstack.exe -l 10520
2021-01-19 17:25:57
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.211-b12 mixed mode):

"Ice.Timer" #13 prio=5 os_prio=0 tid=0x000000001f7e2000 nid=0x28f0 waiting on condition [0x00000000207fe000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x000000076b6a9e38> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1081)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
        at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - None

"Ice.ThreadPool.Server-0" #12 prio=5 os_prio=0 tid=0x000000001fbcf800 nid=0x13a0 runnable [0x00000000205fe000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
        at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:296)
        at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(WindowsSelectorImpl.java:278)
        at sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:159)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        - locked <0x000000076c1c20b0> (a sun.nio.ch.Util$3)
        - locked <0x000000076c1c20a0> (a java.util.Collections$UnmodifiableSet)
        - locked <0x000000076c1c1f50> (a sun.nio.ch.WindowsSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
        at com.zeroc.IceInternal.Selector.select(Selector.java:250)
        at com.zeroc.IceInternal.ThreadPool.run(ThreadPool.java:432)
        at com.zeroc.IceInternal.ThreadPool.access$500(ThreadPool.java:7)
        at com.zeroc.IceInternal.ThreadPool$EventHandlerThread.run(ThreadPool.java:784)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - None

"Ice.ThreadPool.Client-0" #11 prio=5 os_prio=0 tid=0x000000001f9fe800 nid=0x2cbc runnable [0x00000000202fe000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
        at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:296)
        at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(WindowsSelectorImpl.java:278)
        at sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:159)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        - locked <0x000000076b730338> (a sun.nio.ch.Util$3)
        - locked <0x000000076b7302b0> (a java.util.Collections$UnmodifiableSet)
        - locked <0x000000076b72fe30> (a sun.nio.ch.WindowsSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
        at com.zeroc.IceInternal.Selector.select(Selector.java:250)
        at com.zeroc.IceInternal.ThreadPool.run(ThreadPool.java:432)
        at com.zeroc.IceInternal.ThreadPool.access$500(ThreadPool.java:7)
        at com.zeroc.IceInternal.ThreadPool$EventHandlerThread.run(ThreadPool.java:784)
        at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
        - None

"Service Thread" #10 daemon prio=9 os_prio=0 tid=0x000000001e897000 nid=0x261c runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"C1 CompilerThread3" #9 daemon prio=9 os_prio=2 tid=0x000000001e7f9000 nid=0x2e84 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"C2 CompilerThread2" #8 daemon prio=9 os_prio=2 tid=0x000000001e7f2000 nid=0xe0c waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"C2 CompilerThread1" #7 daemon prio=9 os_prio=2 tid=0x000000001e7f0800 nid=0x2a2c waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"C2 CompilerThread0" #6 daemon prio=9 os_prio=2 tid=0x000000001e800000 nid=0x2860 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"Attach Listener" #5 daemon prio=5 os_prio=2 tid=0x000000001e7fe800 nid=0x1038 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"Signal Dispatcher" #4 daemon prio=9 os_prio=2 tid=0x000000001e7fd800 nid=0x1eec runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

   Locked ownable synchronizers:
        - None

"Finalizer" #3 daemon prio=8 os_prio=1 tid=0x000000001e7e0800 nid=0x2c74 in Object.wait() [0x000000001edbf000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x000000076ab08ed0> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
        - locked <0x000000076ab08ed0> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)

   Locked ownable synchronizers:
        - None

"Reference Handler" #2 daemon prio=10 os_prio=2 tid=0x000000001c9bc800 nid=0x940 in Object.wait() [0x000000001ecbf000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x000000076ab06bf8> (a java.lang.ref.Reference$Lock)
        at java.lang.Object.wait(Object.java:502)
        at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
        - locked <0x000000076ab06bf8> (a java.lang.ref.Reference$Lock)
        at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

   Locked ownable synchronizers:
        - None

"main" #1 prio=5 os_prio=0 tid=0x0000000002da4800 nid=0x25bc in Object.wait() [0x0000000002c9f000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x000000076c53ca48> (a test.Ice.faultTolerance.AllTests$PidCallback)
        at java.lang.Object.wait(Object.java:502)
        at test.Ice.faultTolerance.AllTests$Callback.check(AllTests.java:34)
        - locked <0x000000076c53ca48> (a test.Ice.faultTolerance.AllTests$PidCallback)
        at test.Ice.faultTolerance.AllTests.allTests(AllTests.java:147)
        at test.Ice.faultTolerance.Client.run(Client.java:52)
        at test.TestDriver.main(TestDriver.java:17)

   Locked ownable synchronizers:
        - None

"VM Thread" os_prio=2 tid=0x000000001c9b8000 nid=0x28b0 runnable

"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x0000000002dba800 nid=0x2600 runnable

"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x0000000002dbd000 nid=0xef8 runnable

"GC task thread#2 (ParallelGC)" os_prio=0 tid=0x0000000002dbe800 nid=0x198c runnable

"GC task thread#3 (ParallelGC)" os_prio=0 tid=0x0000000002dc0000 nid=0x2654 runnable

"GC task thread#4 (ParallelGC)" os_prio=0 tid=0x0000000002dc2000 nid=0x2030 runnable

"GC task thread#5 (ParallelGC)" os_prio=0 tid=0x0000000002dc4000 nid=0x1cf0 runnable

"GC task thread#6 (ParallelGC)" os_prio=0 tid=0x0000000002dc7000 nid=0x2320 runnable

"GC task thread#7 (ParallelGC)" os_prio=0 tid=0x0000000002dc8000 nid=0x2f54 runnable

"VM Periodic Task Thread" os_prio=2 tid=0x000000001e7f9800 nid=0x1554 waiting on condition

JNI global references: 346
```

**Comment by bentoi** [comment]
I've added tracing, let's re-open if this shows up again.
