### ISSUE TITLE
NullPointerException in IceBT.TransceiverI.runConnectThread (FileDescriptor must not be null)

### ISSUE THREAD

**Issue by mopfattn** [zeroc-ice/ice#1263]
**Version(please complete the following information):**
 - Ice Version: 3.7.4, 3.7.5
 - OS: Android
 - Distribution: https://mvnrepository.com/artifact/com.zeroc/ice/3.7.5

**Describe the bug**
We can see some crash reports on the Google Play Store where the app seems to crash while establishing an Ice connection via Bluetooth:

```
java.lang.NullPointerException: FileDescriptor must not be null
  at android.os.ParcelFileDescriptor.<init>(ParcelFileDescriptor.java:187)
  at android.os.ParcelFileDescriptor$1.createFromParcel(ParcelFileDescriptor.java:1045)
  at android.os.ParcelFileDescriptor$1.createFromParcel(ParcelFileDescriptor.java:1037)
  at android.bluetooth.IBluetooth$Stub$Proxy.connectSocket(IBluetooth.java:1916)
  at android.bluetooth.BluetoothSocket.connect(BluetoothSocket.java:362)
  at IceBT.TransceiverI.runConnectThread(TransceiverI.java:421)
  at IceBT.TransceiverI.access$200(TransceiverI.java:14)
  at IceBT.TransceiverI$1.run(TransceiverI.java:357)
```

**Comment by bentoi** [comment]
The exception is different but it's the same problem as #1262 so I'm closing it.
