### ISSUE TITLE
nodejs Ice/LocalException module not found

### ISSUE THREAD

**Issue by 3g0r** [zeroc-ice/ice#1290]
**Version(please complete the following information):**
 - Ice Version 3.7.6
 - OS: Linux
 - Distribution: npm

**Describe the bug**
The latest patch release broke nodejs module loading.

**Expected behavior**
Normal module loading.

**Additional context**
Error log:
```
# ice-health-check
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '../Ice/LocalException'
Require stack:
- /npm-global/lib/node_modules/ice-health-check/node_modules/ice/src/Ice/Protocol.js
- /npm-global/lib/node_modules/ice-health-check/node_modules/ice/src/Ice/Initialize.js
- /npm-global/lib/node_modules/ice-health-check/node_modules/ice/src/Ice/Ice.js
- /npm-global/lib/node_modules/ice-health-check/node_modules/ice/src/index.js
- /npm-global/lib/node_modules/ice-health-check/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at /npm-global/lib/node_modules/ice-health-check/node_modules/ice/src/Ice/ModuleRegistry.js:25:23
    at Array.forEach (<anonymous>)
    at Function.require (/npm-global/lib/node_modules/ice-health-check/node_modules/ice/src/Ice/ModuleRegistry.js:23:15)
    at Object.<anonymous> (/npm-global/lib/node_modules/ice-health-check/node_modules/ice/src/Ice/Protocol.js:6:21)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/npm-global/lib/node_modules/ice-health-check/node_modules/ice/src/Ice/Protocol.js',
    '/npm-global/lib/node_modules/ice-health-check/node_modules/ice/src/Ice/Initialize.js',
    '/npm-global/lib/node_modules/ice-health-check/node_modules/ice/src/Ice/Ice.js',
    '/npm-global/lib/node_modules/ice-health-check/node_modules/ice/src/index.js',
    '/npm-global/lib/node_modules/ice-health-check/index.js'
  ]
}
```

Content of 3.7.6 package:
```
# yarn add ice@3.7.6
# ls -la node_modules/ice/src/Ice/ | grep Exc
-rw-r--r-- 1 root root  1752 Jun 23 10:12 Exception.d.ts
-rw-r--r-- 1 root root  5851 Jun 23 10:12 Exception.js
-rw-r--r-- 1 root root   610 Jun 23 10:12 RetryException.js
```

Content of 3.7.5 package:
```
# yarn add ice@3.7.5
# ls -la node_modules/ice/src/Ice/ | grep Exc
-rw-r--r-- 1 root root  1752 Jun 23 21:06 Exception.d.ts
-rw-r--r-- 1 root root  5851 Jun 23 21:06 Exception.js
-rw-r--r-- 1 root root 34658 Jun 23 21:06 LocalException.d.ts
-rw-r--r-- 1 root root 39373 Jun 23 21:06 LocalException.js
-rw-r--r-- 1 root root   610 Jun 23 21:06 RetryException.js
```

**Comment by pepone** [comment]
Can you try with `3.7.7-pre.1` 3.7.6 is missing some files due to an error with the publish.

**Comment by 3g0r** [comment]
Hi, I checked `3.7.7-pre.1` and `3.3.60` - it's worked, thanks. 👍
