### ISSUE TITLE
NullPointerException in icegridgui 

### ISSUE THREAD

**Issue by iivdam** [zeroc-ice/ice#1399]
**Version(please complete the following information):**
 - Ice Version 3.78
 - OS: Windows

**Describe the bug**
When I click in the 'Live Deployment Tab' on a 'Server Run Time Component' icegridgui fires a NullPointerException and the 'Server Properties' panel at the right is not shown.

`Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at com.zeroc.IceGridGUI.LiveDeployment.Node.expand(Node.java:272)
        at com.zeroc.IceGridGUI.LiveDeployment.Node.expand(Node.java:277)
        at com.zeroc.IceGridGUI.LiveDeployment.Server.getProperties(Server.java:890)
        at com.zeroc.IceGridGUI.LiveDeployment.ServerEditor.show(ServerEditor.java:120)
        at com.zeroc.IceGridGUI.LiveDeployment.Server.getEditor(Server.java:373)
        at com.zeroc.IceGridGUI.LiveDeploymentPane.showCurrentNode(LiveDeploymentPane.java:257)
        at com.zeroc.IceGridGUI.LiveDeploymentPane.showNode(LiveDeploymentPane.java:99)
        at com.zeroc.IceGridGUI.LiveDeploymentPane$SelectionListener.valueChanged(LiveDeploymentPane.java:296)
        at javax.swing.JTree.fireValueChanged(Unknown Source)
        at javax.swing.JTree$TreeSelectionRedirector.valueChanged(Unknown Source)
        at javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(Unknown Source)
        at javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(Unknown Source)
        at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(Unknown Source)
        at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(Unknown Source)
        at javax.swing.JTree.setSelectionPath(Unknown Source)
        at javax.swing.plaf.basic.BasicTreeUI.selectPathForEvent(Unknown Source)
        at javax.swing.plaf.basic.BasicTreeUI$Handler.handleSelection(Unknown Source)
        at javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressed(Unknown Source)
        at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
        at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)`

Side note: there is a 404 on 'Help->Contents'

Regards,
Emko

**Comment by pepone** [comment]
Hi Emko,

I try to reproduce this issue using one of our [IceGrid simple demo](https://github.com/zeroc-ice/ice-demos/tree/3.7/cpp98/IceGrid/simple) but I didn't get the NPE.

What Java version are you using? can you provide more details about how to reproduce the issue, including your application descriptor?

> Side note: there is a 404 on 'Help->Contents'

There is a typo in the code that constructs the URL we will push a fix, thanks for reporting it.

Cheers,
Jose

**Comment by iivdam** [comment]
Hi Jose,

I think I made a mistake in the 'Properties Descriptor' with refid. The following descriptor reproduce the issue:

[application.xml.txt](https://github.com/zeroc-ice/ice/files/10134917/application.xml.txt)

It works with 'refid="defaults"' and failes with 'refid="${node}-defaults"'.

Cheers,
Emko
