### ISSUE TITLE
Timeout overrides test failures with .NET 7.0 on macOS monterey

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#1457]
```
Running on ice-ci-macos-monterey-dev-3.7
[ running client/server test - 02/28/23 09:19:08 ]
- Config: ssl,shared,net7.0
(/Users/vagrant/workspace/ice/3.7/csharp/test/Ice/timeout/msbuild/server/netstandard2.0/net7.0/server --Ice.Default.Host=127.0.0.1 --Test.BasePort=14000 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --Ice.Plugin.IceSSL=/Users/vagrant/workspace/ice/3.7/csharp/lib/netstandard2.0/IceSSL.dll:IceSSL.PluginFactory --IceSSL.Password=password --IceSSL.DefaultDir=/Users/vagrant/workspace/ice/3.7/certs --IceSSL.CAs=cacert.pem --IceSSL.VerifyPeer=2 --IceSSL.CertFile=server.p12 --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 --Ice.Trace.Network=2 --Ice.Trace.Retry=1 --Ice.Trace.Protocol=1 --Ice.LogFile=/Users/vagrant/workspace/ice/3.7/csharp/test/Ice/timeout/server-022823-0919.log)
(/Users/vagrant/workspace/ice/3.7/csharp/test/Ice/timeout/msbuild/client/netstandard2.0/net7.0/client --Ice.Default.Host=127.0.0.1 --Test.BasePort=14000 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --Ice.Plugin.IceSSL=/Users/vagrant/workspace/ice/3.7/csharp/lib/netstandard2.0/IceSSL.dll:IceSSL.PluginFactory --IceSSL.Password=password --IceSSL.DefaultDir=/Users/vagrant/workspace/ice/3.7/certs --IceSSL.CAs=cacert.pem --IceSSL.VerifyPeer=2 --IceSSL.CertFile=client.p12 --Ice.Trace.Network=2 --Ice.Trace.Retry=1 --Ice.Trace.Protocol=1 --Ice.LogFile=/Users/vagrant/workspace/ice/3.7/csharp/test/Ice/timeout/client-022823-0919.log)
testing connect timeout... ok
testing connection timeout... ok
testing invocation timeout... ok
testing close timeout... ok
testing timeout overrides... Ice.ConnectTimeoutException
   at Ice.ObjectPrxHelperBase.ice_getConnection() in /Users/vagrant/workspace/ice/3.7/csharp/src/Ice/Proxy.cs:line 2273
   at Ice.timeout.AllTests.connect(ObjectPrx prx) in /Users/vagrant/workspace/ice/3.7/csharp/test/Ice/timeout/AllTests.cs:line 62
   at Ice.timeout.AllTests.allTestsWithController(TestHelper helper, ControllerPrx controller) in /Users/vagrant/workspace/ice/3.7/csharp/test/Ice/timeout/AllTests.cs:line 409
   at Ice.timeout.AllTests.allTests(TestHelper helper) in /Users/vagrant/workspace/ice/3.7/csharp/test/Ice/timeout/AllTests.cs:line 74
   at Ice.timeout.Client.run(String[] args) in /Users/vagrant/workspace/ice/3.7/csharp/test/Ice/timeout/Client.cs:line 32
   at Test.TestDriver.runTest[T](String[] args) in /Users/vagrant/workspace/ice/3.7/csharp/test/TestCommon/TestHelper.cs:line 227
saved /Users/vagrant/workspace/ice/3.7/csharp/test/Ice/timeout/client-022823-0919.log
saved /Users/vagrant/workspace/ice/3.7/csharp/test/Ice/timeout/server-022823-0919.log
```

**Comment by externl** [comment]
I can't reproduce this locally either.
