### ISSUE TITLE
Ice C# metrics test sporadic failure

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#1476]
```
testing invocation metrics... 
im1.current: 1
im1.total: 2
im1.failures: 0
im1.retry: 0
failed:
   at Test.TestHelper.fail(String message, String detailMessage) in C:\Users\vagrant\workspace\ice\3.7\csharp\test\TestCommon\TestHelper.cs:line 178
   at Test.TestHelper.TestTraceListener.Fail(String message, String detailMessage) in C:\Users\vagrant\workspace\ice\3.7\csharp\test\TestCommon\TestHelper.cs:line 39
   at System.Diagnostics.TraceInternal.Fail(String message, String detailMessage)
   at System.Diagnostics.TraceInternal.TraceProvider.Fail(String message, String detailMessage)
   at System.Diagnostics.Debug.Fail(String message, String detailMessage)
   at Test.AllTests.test(Boolean b) in C:\Users\vagrant\workspace\ice\3.7\csharp\test\TestCommon\TestHelper.cs:line 212
   at AllTests.allTests(TestHelper helper, CommunicatorObserverI obsv) in C:\Users\vagrant\workspace\ice\3.7\csharp\test\Ice\metrics\AllTests.cs:line 1310
   at Client.run(String[] args) in C:\Users\vagrant\workspace\ice\3.7\csharp\test\Ice\metrics\Client.cs:line 31
   at Test.TestDriver.runTest[T](String[] args) in C:\Users\vagrant\workspace\ice\3.7\csharp\test\TestCommon\TestHelper.cs:line 227
   at Client.Main(String[] args) in C:\Users\vagrant\workspace\ice\3.7\csharp\test\Ice\metrics\Client.cs:line 38
```

**Comment by pepone** [comment]
Cannot reproduce with Apple hardware, only happens in the VMware Montery VM
