### ISSUE TITLE
Ice/dispatcher test failure with C# / dotnet on macOS

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice#167]
Looks like the dispatcher didn't get use for the invocation timeout.

```
[ running client/server test - 07/04/18 02:46:41 ]
- Config: ws,serialize,compress,mx,ipv6
(dotnet /Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice-3.7/builds/ice-clang-default/csharp/test/Ice/dispatcher/msbuild/server/netstandard2.0/netcoreapp2.0/server.dll --Ice.Warn.Connections=1 --Ice.Override.Compress=1 --Ice.PrintAdapterReady=1 --Ice.ThreadPool.Server.Serialize=1 --Ice.Admin.InstanceName=Server --Ice.PreferIPv6Address=1 --Ice.Default.Protocol=ws --Ice.ThreadPool.Server.Size=1 --Ice.Default.Host=::1 --Ice.IPv6=1 --IceMX.Metrics.Parent.GroupBy=parent --Ice.ThreadPool.Server.SizeMax=3 --IceMX.Metrics.Debug.GroupBy=id --Test.BasePort=14300 --IceMX.Metrics.All.GroupBy=none --Ice.Admin.Endpoints="default -h localhost" --Ice.ThreadPool.Server.SizeWarn=0)
(dotnet /Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice-3.7/builds/ice-clang-default/csharp/test/Ice/dispatcher/msbuild/client/netstandard2.0/netcoreapp2.0/client.dll --Ice.Warn.Connections=1 --Ice.Override.Compress=1 --Ice.ThreadPool.Server.Serialize=1 --Ice.Admin.InstanceName=Client --Ice.PreferIPv6Address=1 --Ice.Default.Protocol=ws --Ice.Default.Host=::1 --Ice.IPv6=1 --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.Debug.GroupBy=id --Test.BasePort=14300 --IceMX.Metrics.All.GroupBy=none --Ice.Admin.Endpoints="default -h localhost")
testing dispatcher... ok
testing dispatcher with continuations... System.AggregateException: One or more errors occurred. (Exception of type 'System.Exception' was thrown.) ---> System.Exception: Exception of type 'System.Exception' was thrown.
at Test.AllTests.test(Boolean b) in /Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice-3.7/builds/ice-clang-default/csharp/test/TestCommon/TestHelper.cs:line 128
at AllTests.<>c.<allTests>b__2_4(Task previous) in /Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice-3.7/builds/ice-clang-default/csharp/test/Ice/dispatcher/AllTests.cs:line 214
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of inner exception stack trace ---
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
at AllTests.allTests(TestHelper helper) in /Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice-3.7/builds/ice-clang-default/csharp/test/Ice/dispatcher/AllTests.cs:line 224
at Client.run(String[] args) in /Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice-3.7/builds/ice-clang-default/csharp/test/Ice/dispatcher/Client.cs:line 36
at Test.TestDriver.runTest[T](String[] args) in /Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice-3.7/builds/ice-clang-default/csharp/test/TestCommon/TestHelper.cs:line 156
---> (Inner Exception #0) System.Exception: Exception of type 'System.Exception' was thrown.
at Test.AllTests.test(Boolean b) in /Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice-3.7/builds/ice-clang-default/csharp/test/TestCommon/TestHelper.cs:line 128
at AllTests.<>c.<allTests>b__2_4(Task previous) in /Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice-3.7/builds/ice-clang-default/csharp/test/Ice/dispatcher/AllTests.cs:line 214
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)<---
```

**Comment by pepone** [comment]
We hit this again with high sierra VMs

```
esting dispatcher with continuations... System.AggregateException: One or more errors occurred. (Exception of type 'System.Exception' was thrown.) ---> System.Exception: Exception of type 'System.Exception' was thrown.
   at Test.AllTests.test(Boolean b) in /Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-clang-default/csharp/test/TestCommon/TestHelper.cs:line 167
   at AllTests.<>c.<allTests>b__2_4(Task previous) in /Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-clang-default/csharp/test/Ice/dispatcher/AllTests.cs:line 212
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at AllTests.allTests(TestHelper helper) in /Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-clang-default/csharp/test/Ice/dispatcher/AllTests.cs:line 222
   at Client.run(String[] args) in /Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-clang-default/csharp/test/Ice/dispatcher/Client.cs:line 31
   at Test.TestDriver.runTest[T](String[] args) in /Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-clang-default/csharp/test/TestCommon/TestHelper.cs:line 180
---> (Inner Exception #0) System.Exception: Exception of type 'System.Exception' was thrown.
   at Test.AllTests.test(Boolean b) in /Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-clang-default/csharp/test/TestCommon/TestHelper.cs:line 167
   at AllTests.<>c.<allTests>b__2_4(Task previous) in /Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-clang-default/csharp/test/Ice/dispatcher/AllTests.cs:line 212
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)<---
```
