### ISSUE TITLE
csharp/IceSSL/configuration intermittent failure

### ISSUE THREAD

**Issue by externl** [zeroc-ice/ice#1745]
We're getting this on `main` ci, ubuntu-latest.

```
*** [49/54] Running csharp/IceSSL/configuration tests ***
[ running client/server test - 01/31/24 22:01:27 ]
(dotnet /home/runner/work/ice/ice/csharp/test/IceSSL/configuration/msbuild/server/net6.0/server.dll --Ice.Default.Host=127.0.0.1 --Test.BasePort=14000 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp --Ice.IPv6=0 --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 "/home/runner/work/ice/ice/csharp/test/IceSSL/configuration")
(dotnet /home/runner/work/ice/ice/csharp/test/IceSSL/configuration/msbuild/client/net6.0/client.dll --Ice.Default.Host=127.0.0.1 --Test.BasePort=14000 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp --Ice.IPv6=0 "/home/runner/work/ice/ice/csharp/test/IceSSL/configuration")
testing manual initialization... ok
testing certificate verification... ok
testing certificate chains... ok
testing custom certificate verifier... ok
testing protocols... ok
testing expired certificates... ok
testing multiple CA certificates... ok
testing DER CA certificate... ok
testing passwords... ok
testing IceSSL.TrustOnly... ok
testing IceSSL.TrustOnly.Client... -! 01/31/2024 22:01:41:383 client: warning: connection exception:
   Ice.ConnectionLostException
       error = 0
      at IceInternal.StreamSocket.finishRead(Buffer buf) in /home/runner/work/ice/ice/csharp/src/Ice/StreamSocket.cs:line 229
      at Ice.ConnectionI.finishAsync(Int32 operation) in /home/runner/work/ice/ice/csharp/src/Ice/ConnectionI.cs:line 1145
   local address = 127.0.0.1:54380
   remote address = 127.0.0.1:14000
Ice.ConnectionLostException
    error = 0
   at Test.ServerFactoryPrxHelper.destroyServer(ServerPrx srv, OptionalContext context) in /home/runner/work/ice/ice/csharp/test/IceSSL/configuration/msbuild/client/generated/Test.cs:line 642
   at AllTests.allTests(TestHelper helper, String testDir) in /home/runner/work/ice/ice/csharp/test/IceSSL/configuration/AllTests.cs:line 2038
   at Client.run(String[] args) in /home/runner/work/ice/ice/csharp/test/IceSSL/configuration/Client.cs:line 26
   at Test.TestDriver.runTest[T](String[] args) in /home/runner/work/ice/ice/csharp/test/TestCommon/TestHelper.cs:line 226
```

**Comment by bernardnormier** [comment]
There was the same failure on Ubuntu in my PR build.

**Comment by pepone** [comment]
On main I get a similar error with this test:

```
*** [1/1 loop=67] Running csharp/IceSSL/configuration tests ***
[ running client/server test - 09/05/24 12:41:04 ]
(dotnet /workspaces/ice/csharp/test/IceSSL/configuration/msbuild/server/net8.0/server.dll --Ice.Default.Host=127.0.0.1 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp --Ice.IPv6=0 --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 "/workspaces/ice/csharp/test/IceSSL/configuration")
(dotnet /workspaces/ice/csharp/test/IceSSL/configuration/msbuild/client/net8.0/client.dll --Ice.Default.Host=127.0.0.1 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp --Ice.IPv6=0 "/workspaces/ice/csharp/test/IceSSL/configuration")
client validates server certificate using validation callback... ok
client validates server certificate using system trusted root certificates... ok
client rejects server certificate using validation callback... ok
client rejects server certificate using default validation callback... ok
server validates client certificate using validation callback... ok
server rejects client certificate using validation callback... ok
server rejects client certificate using default validation callback... ok
server hot certificate reload... ok
testing certificate without password... ok
testing certificate verification... -! 9/5/2024 12:41:06:027 client: warning: connection exception:
   Ice.ConnectionLostException: Exception of type 'Ice.ConnectionLostException' was thrown.
      at Ice.Internal.StreamSocket.finishRead(Buffer buf) in /workspaces/ice/csharp/src/Ice/Internal/StreamSocket.cs:line 207
      at Ice.Internal.TcpTransceiver.finishRead(Buffer buf) in /workspaces/ice/csharp/src/Ice/Internal/TcpTransceiver.cs:line 61
      at Ice.Internal.IdleTimeoutTransceiverDecorator.finishRead(Buffer buf) in /workspaces/ice/csharp/src/Ice/Internal/IdleTimeoutTransceiverDecorator.cs:line 56
      at Ice.ConnectionI.finishAsync(Int32 operation) in /workspaces/ice/csharp/src/Ice/ConnectionI.cs:line 706
   local address = 127.0.0.1:46926
   remote address = 127.0.0.1:12010
Ice.ConnectionLostException: Exception of type 'Ice.ConnectionLostException' was thrown.
   at Test.ServerFactoryPrxHelper.destroyServer(ServerPrx srv, Dictionary`2 context) in /workspaces/ice/csharp/test/IceSSL/configuration/msbuild/client/generated/Test.cs:line 325
   at AllTests.allTests(TestHelper helper, String testDir) in /workspaces/ice/csharp/test/IceSSL/configuration/AllTests.cs:line 525
   at Client.run(String[] args) in /workspaces/ice/csharp/test/IceSSL/configuration/Client.cs:line 24
   at Test.TestHelper.runAsync(String[] args) in /workspaces/ice/csharp/test/TestCommon/TestHelper.cs:line 55
   at Test.TestDriver.runTestAsync[T](String[] args) in /workspaces/ice/csharp/test/TestCommon/TestHelper.cs:line 232
Traceback (most recent call last):
  File "/workspaces/ice/csharp/../s
```

The error seems to always happen when calling `destroyServer` which uses a plain TCP connection.

**Comment by pepone** [comment]
Interestingly the test doesn't fail when the calls to createServer/destroyServer are done from the main communicator.

With the current setup we do then from the temporary communicators that are created with the SSL setup for each sub-test.

**Comment by bernardnormier** [comment]
Failed again here (Ubuntu/debug):
https://github.com/zeroc-ice/ice/actions/runs/11257814148/job/31312779820

```
*** [100/305] Running csharp/IceSSL/configuration tests ***
[ running client/server test - 10/09/24 18:31:14 ]
(dotnet /home/runner/work/ice/ice/csharp/test/IceSSL/configuration/msbuild/server/net8.0/server.dll --Ice.Default.Host=127.0.0.1 --Test.BasePort=14000 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp --Ice.IPv6=0 --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 "/home/runner/work/ice/ice/csharp/test/IceSSL/configuration")
(dotnet /home/runner/work/ice/ice/csharp/test/IceSSL/configuration/msbuild/client/net8.0/client.dll --Ice.Default.Host=127.0.0.1 --Test.BasePort=14000 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp --Ice.IPv6=0 "/home/runner/work/ice/ice/csharp/test/IceSSL/configuration")
client validates server certificate using validation callback... ok
client validates server certificate using system trusted root certificates... ok
client rejects server certificate using validation callback... ok
client rejects server certificate using default validation callback... ok
server validates client certificate using validation callback... ok
server rejects client certificate using validation callback... ok
server rejects client certificate using default validation callback... ok
server hot certificate reload... ok
testing certificate without password... ok
testing certificate verification... Ice.ConnectionLostException: Exception of type 'Ice.ConnectionLostException' was thrown.
   at Test.ServerFactoryPrxHelper.destroyServer(ServerPrx srv, Dictionary`2 context) in /home/runner/work/ice/ice/csharp/test/IceSSL/configuration/msbuild/client/generated/Test.cs:line 325
   at AllTests.allTests(TestHelper helper, String testDir) in /home/runner/work/ice/ice/csharp/test/IceSSL/configuration/AllTests.cs:line 388
   at Client.run(String[] args) in /home/runner/work/ice/ice/csharp/test/IceSSL/configuration/Client.cs:line 24
   at Test.TestHelper.runAsync(String[] args) in /home/runner/work/ice/ice/csharp/test/TestCommon/TestHelper.cs:line 55
   at Test.TestDriver.runTestAsync[T](String[] args) in /home/runner/work/ice/ice/csharp/test/TestCommon/TestHelper.cs:line 232

test in IceSSL/configuration failed:
Traceback (most recent call last):
  File "/home/runner/work/ice/ice/scripts/Util.py", line 1998, in run
    self.runWithDriver(current)
  File "/home/runner/work/ice/ice/scripts/Util.py", line 2029, in runWithDriver
    current.driver.runClientServerTestCase(current)
  File "/home/runner/work/ice/ice/scripts/LocalDriver.py", line 680, in runClientServerTestCase
    self.runner.runClientSide(client, current, host)
  File "/home/runner/work/ice/ice/scripts/LocalDriver.py", line 207, in runClientSide
    testcase._runClientSide(current, host)
  File "/home/runner/work/ice/ice/scripts/Util.py", line 1975, in _runClientSide
    self.runClientSide(current)
  File "/home/runner/work/ice/ice/scripts/Util.py", line 1861, in runClientSide
    self._runClient(current, client)
  File "/home/runner/work/ice/ice/scripts/Util.py", line 1987, in _runClient
    client.run(current)
  File "/home/runner/work/ice/ice/scripts/Util.py", line 1391, in run
    process.waitSuccess(exitstatus=exitstatus, timeout=30)
  File "/home/runner/work/ice/ice/scripts/Expect.py", line 691, in waitSuccess
    self.testExitStatus(exitstatus)
  File "/home/runner/work/ice/ice/scripts/Expect.py", line 735, in testExitStatus
    test(self.exitstatus, exitstatus)
  File "/home/runner/work/ice/ice/scripts/Expect.py", line 717, in test
    raise RuntimeError(
RuntimeError: unexpected exit status: expected: 0, got 1
```

**Comment by pepone** [comment]
I debugged this a while ago and dotnet crash when this happens, but I was not able to get core dump for the dotnet native process.

**Comment by bernardnormier** [comment]
Failed again here:
https://github.com/zeroc-ice/ice/actions/runs/11584385677/job/32251411071

**Comment by pepone** [comment]
The dotnet process crash here when this happens https://github.com/dotnet/runtime/issues/109689

**Comment by pepone** [comment]
Attached core dump for the dotnet crash

[dotnet-core.zip](https://github.com/user-attachments/files/17736699/dotnet-core.zip)

**Comment by pepone** [comment]
See updates in https://github.com/dotnet/runtime/issues/109689#issuecomment-2697668131
