### ISSUE TITLE
C++ Ice/background test failures with CI

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#1893]
Saw this with the CI windows build.

```
2024-03-01T20:52:37.5885298Z D:\a\ice\ice\cpp\test\Ice\background\AllTests.cpp:150: assertion `f1.wait_for(chrono::milliseconds(0)) != future_status::ready' failed
2024-03-01T20:52:37.5886905Z !! 03/01/24 20:48:19308 error: communicator not destroyed during global destruction.
2024-03-01T20:52:37.5887788Z 
2024-03-01T20:52:37.5887978Z test in Ice/background failed:
2024-03-01T20:52:37.5888480Z Traceback (most recent call last):
2024-03-01T20:52:37.5889347Z   File "D:\a\ice\ice\scripts\Util.py", line 2050, in run
2024-03-01T20:52:37.5890027Z     self.runWithDriver(current)
2024-03-01T20:52:37.5890770Z   File "D:\a\ice\ice\scripts\Util.py", line 2081, in runWithDriver
2024-03-01T20:52:37.5892462Z     current.driver.runClientServerTestCase(current)
2024-03-01T20:52:37.5893566Z   File "D:\a\ice\ice\scripts\LocalDriver.py", line 680, in runClientServerTestCase
2024-03-01T20:52:37.5894580Z     self.runner.runClientSide(client, current, host)
2024-03-01T20:52:37.5895538Z   File "D:\a\ice\ice\scripts\LocalDriver.py", line 207, in runClientSide
2024-03-01T20:52:37.5897647Z     testcase._runClientSide(current, host)
2024-03-01T20:52:37.5898992Z   File "D:\a\ice\ice\scripts\Util.py", line 2027, in _runClientSide
2024-03-01T20:52:37.5899869Z     self.runClientSide(current)
2024-03-01T20:52:37.5900687Z   File "D:\a\ice\ice\scripts\Util.py", line 1913, in runClientSide
2024-03-01T20:52:37.5901523Z     self._runClient(current, client)
2024-03-01T20:52:37.5902342Z   File "D:\a\ice\ice\scripts\Util.py", line 2039, in _runClient
2024-03-01T20:52:37.5903135Z     client.run(current)
2024-03-01T20:52:37.5903950Z   File "D:\a\ice\ice\scripts\Util.py", line 1441, in run
2024-03-01T20:52:37.5904868Z     process.waitSuccess(exitstatus=exitstatus, timeout=30)
2024-03-01T20:52:37.5905820Z   File "D:\a\ice\ice\scripts\Expect.py", line 691, in waitSuccess
2024-03-01T20:52:37.5906610Z     self.testExitStatus(exitstatus)
2024-03-01T20:52:37.5907355Z   File "D:\a\ice\ice\scripts\Expect.py", line 735, in testExitStatus
2024-03-01T20:52:37.5908075Z     test(self.exitstatus, exitstatus)
2024-03-01T20:52:37.5908785Z   File "D:\a\ice\ice\scripts\Expect.py", line 717, in test
2024-03-01T20:52:37.5909448Z     raise RuntimeError(
2024-03-01T20:52:37.5910083Z RuntimeError: unexpected exit status: expected: 0, got 3221226505
```

**Comment by pepone** [comment]
https://github.com/zeroc-ice/ice/blob/b25e0940b8b0899070a562f90123319e8ee06067/cpp/test/Ice/background/AllTests.cpp#L134-L151

What are we testing here?

We call `backgroundController->pauseCall("findAdapterById");` to make the locator call block until resume is called.

Then, we test that the call to `opAsync` doesn't complete immediately, which sometimes fails on Windows CI.

My understanding is that `findAdapterById` isn't called here because the adapter ID is already in the locator cache.

Using `chrono::milliseconds(0)` is problematic, as it seems to assume that if the locator didn't block, the call must complete immediately, which is a brittle assumption.

If I add a large delay, the test fails consistently, which shouldn't happen if the test's assumption was correct.

If I disable the locator cache, the test works, even with the large delay.

I don't see how testing locator and router facilities is relevant in this test, I think we better remove them from this test.

**Comment by bentoi** [comment]
It's surprising that we get this failure now. Did we ever get it before? 

The tests from `Ice/background` are there to make sure that an asynchronous invocation never blocks the application thread. We tests all the conditions where the async call could be blocking: hanging locator/router, various spots that could hang on connection establishment, etc.

If the locator or router hangs, `opAsync` should always return without blocking and the returned `std::future` should never be "ready", at least not until the locator/router call returns. That's what the locator and router tests are about.

> My understanding is that findAdapterById isn't called here because the adapter ID is already in the locator cache.

Why would it already be in the locator cache? Because of the `ice_ping` call which is called before? In theory the `Test` adapter ID should not be cached because the `findAdapterById` call should fail with an invocation timeout.

> Using chrono::milliseconds(0) is problematic, as it seems to assume that if the locator didn't block, the call must complete immediately, which is a brittle assumption.

`wait_for(chrono::milliseconds(0))` is just a way to check the status of the future. The status should never be equal to ready since the adapter ID shouldn't be cached and the `opAsync` call should always hang on the "under-the-hood" locator `findAdapterId` call.

It does sound like the adapter ID is indeed cached but it's not clear to me when. If you can easily reproduce, it would be good to figure out if and when the adapter ID gets cached before `opAsync` is called.

**Comment by pepone** [comment]
This call to ice_ping is causing the cache of the adapterId

https://github.com/zeroc-ice/ice/blob/f983d5ea3a469835dea7c76ae64ab53108f7e5b8/cpp/test/Ice/background/AllTests.cpp#L134-L137

The original code in 3.7, is a bit different

https://github.com/zeroc-ice/ice/blob/e545e8bf03ff6771d96f162229276d6287ddca6f/cpp/test/Ice/background/AllTests.cpp#L269-L272

The 3.7 version pings the locator proxy, and sets a locator in the locator proxy (there is no need to set the locator there)

> wait_for(chrono::milliseconds(0)) is just a way to check the status of the future.

Right, but I think  a large delay 10ms would have catch this issue early.
