### ISSUE TITLE
C# Ice/hold failures

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#1907]
This test is failing with CI

```
2024-03-06T22:05:57.8075075Z testing waitForHold... ok
2024-03-06T22:05:57.8075681Z changing state to hold and shutting down server... ok
2024-03-06T22:05:57.8076722Z -! 03/06/2024 22:05:47:774 server: warning: dispatch exception:
2024-03-06T22:05:57.8077482Z    identity: hold
2024-03-06T22:05:57.8077877Z    facet: 
2024-03-06T22:05:57.8078252Z    operation: setOneway
2024-03-06T22:05:57.8078768Z    remote host: ::1 remote port: 57248
2024-03-06T22:05:57.8079699Z    System.Exception: Exception of type 'System.Exception' was thrown.
2024-03-06T22:05:57.8081406Z       at Ice.hold.HoldI.setOneway(Int32 value, Int32 expected, Current current) in /home/runner/work/ice/ice/csharp/test/Ice/hold/HoldI.cs:line 94
2024-03-06T22:05:57.8084098Z       at Ice.hold.Test.HoldDisp_.iceD_setOneway(Hold obj, Incoming inS, Current current) in /home/runner/work/ice/ice/csharp/test/Ice/hold/msbuild/server/generated/Test.cs:line 591
2024-03-06T22:05:57.8086910Z       at IceInternal.Incoming.invoke(ServantManager servantManager, InputStream stream) in /home/runner/work/ice/ice/csharp/src/Ice/Incoming.cs:line 214
2024-03-06T22:05:57.8089015Z    --- End of stack trace from previous location ---
2024-03-06T22:05:57.8090486Z       at IceInternal.Incoming.handleException(Exception exc, Boolean amd) in /home/runner/work/ice/ice/csharp/src/Ice/Incoming.cs:line 639
2024-03-06T22:05:57.8092267Z -! 03/06/2024 22:05:47:777 server: warning: dispatch exception:
2024-03-06T22:05:57.8093024Z    identity: hold
```

**Comment by bernardnormier** [comment]
This bug appears to be fixed.
