### ISSUE TITLE
MATLAB slicing test failures

### ISSUE THREAD

**Issue by externl** [zeroc-ice/ice#1945]
```
*** [8/10] Running matlab/Ice/slicing/exceptions tests ***
[ running client/server test - 03/15/24 16:28:54 ]
- Config: tcp
("/usr/bin/python3"  /home/runner/work/ice/ice/python/test/TestHelper.py Server --Ice.Default.Host=127.0.0.1 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp --Ice.IPv6=0 --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 env={'LD_LIBRARY_PATH': '/home/runner/work/ice/ice/cpp/lib/x86_64-linux-gnu', 'PYTHONPATH': '/home/runner/work/ice/ice/python/python:/home/runner/work/ice/ice/python/test/Ice/slicing/exceptions'})
(/usr/local/bin/run-matlab-command "cd '/home/runner/work/ice/ice/matlab/test/lib', runTest /home/runner/work/ice/ice/matlab/test/Ice/slicing/exceptions /home/runner/work/ice/ice/matlab/lib/x86_64-linux-gnu --Ice.Default.Host=127.0.0.1 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp --Ice.IPv6=0" env={'LD_LIBRARY_PATH': '/home/runner/work/ice/ice/cpp/lib/x86_64-linux-gnu'})
testing stringToProxy... ok
testing checked cast... ok
base... ok
base (AMI)... ok
slicing of unknown derived... ok
slicing of unknown derived (AMI)... ok
non-slicing of known derived as base... ok
non-slicing of known derived as base (AMI)... ok
non-slicing of known derived as derived... ok
non-slicing of known derived as derived (AMI)... ok
slicing of unknown intermediate as base... ok
slicing of unknown intermediate as base (AMI)... ok
slicing of known intermediate as base... ok
slicing of known intermediate as base (AMI)... ok
slicing of known most derived as base... ok
slicing of known most derived as base (AMI)... ok
non-slicing of known intermediate as intermediate... ok
non-slicing of known intermediate as intermediate (AMI)... ok
non-slicing of known most derived as intermediate... ok
non-slicing of known most derived as intermediate (AMI)... ok
non-slicing of known most derived as most derived... ok
non-slicing of known most derived as most derived (AMI)... ok
slicing of unknown most derived, known intermediate as base... ok
slicing of unknown most derived, known intermediate as base (AMI)... ok
slicing of unknown most derived, known intermediate as intermediate... ok
slicing of unknown most derived, known intermediate as intermediate (AMI)... ok
slicing of unknown most derived, unknown intermediate thrown as base... ok
slicing of unknown most derived, unknown intermediate thrown as base (AMI)... ok
unknown most derived in compact format... ok
preserved exceptions... Error using Test.TestIntfPrx/unknownPreservedAsBase
::Ice::OperationNotExistException

Error in AllTests.allTests (line 493)
                test.unknownPreservedAsBase();

Error in Client (line 14)
    test = AllTests.allTests(helper);

Error in runTest (line 28)
        Client(varargin);
exit status 1
Traceback (most recent call last):
  File "/home/runner/work/ice/ice/scripts/Util.py", line 2050, in run
    self.runWithDriver(current)
  File "/home/runner/work/ice/ice/scripts/Util.py", line 2081, in runWithDriver
    current.driver.runClientServerTestCase(current)
  File "/home/runner/work/ice/ice/scripts/LocalDriver.py", line 680, in runClientServerTestCase
    self.runner.runClientSide(client, current, host)
  File "/home/runner/work/ice/ice/scripts/LocalDriver.py", line 207, in runClientSide
    testcase._runClientSide(current, host)
  File "/home/runner/work/ice/ice/scripts/Util.py", line 2027, in _runClientSide
    self.runClientSide(current)
  File "/home/runner/work/ice/ice/scripts/Util.py", line 1913, in runClientSide
    self._runClient(current, client)
  File "/home/runner/work/ice/ice/scripts/Util.py", line 2039, in _runClient
    client.run(current)
  File "/home/runner/work/ice/ice/scripts/Util.py", line 1441, in run
    process.waitSuccess(exitstatus=exitstatus, timeout=30)
  File "/home/runner/work/ice/ice/scripts/Expect.py", line 691, in waitSuccess
    self.testExitStatus(exitstatus)
  File "/home/runner/work/ice/ice/scripts/Expect.py", line 735, in testExitStatus
    test(self.exitstatus, exitstatus)
  File "/home/runner/work/ice/ice/scripts/Expect.py", line 717, in test
    raise RuntimeError(
RuntimeError: unexpected exit status: expected: 0, got 1
```

```
*** [9/10] Running matlab/Ice/slicing/objects tests ***
[ running client/server test - 03/15/24 16:29:03 ]
- Config: tcp
("/usr/bin/python3"  /home/runner/work/ice/ice/python/test/TestHelper.py Server --Ice.Default.Host=127.0.0.1 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp --Ice.IPv6=0 --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 env={'LD_LIBRARY_PATH': '/home/runner/work/ice/ice/cpp/lib/x86_64-linux-gnu', 'PYTHONPATH': '/home/runner/work/ice/ice/python/python:/home/runner/work/ice/ice/python/test/Ice/slicing/objects'})
(/usr/local/bin/run-matlab-command "cd '/home/runner/work/ice/ice/matlab/test/lib', runTest /home/runner/work/ice/ice/matlab/test/Ice/slicing/objects /home/runner/work/ice/ice/matlab/lib/x86_64-linux-gnu --Ice.Default.Host=127.0.0.1 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp --Ice.IPv6=0" env={'LD_LIBRARY_PATH': '/home/runner/work/ice/ice/cpp/lib/x86_64-linux-gnu'})
testing stringToProxy... ok
testing checked cast... ok
base as Object... ok
base as Object (AMI)... ok
base as Base... ok
base as Base (AMI)... ok
base with known derived as base... ok
base with known derived as base (AMI)... ok
base with known derived as known derived... ok
base with known derived as known derived (AMI)... ok
base with unknown derived as base... ok
base with unknown derived as base (AMI)... ok
unknown with Object as Object... ok
unknown with Object as Object (AMI)... ok
one-element cycle... ok
one-element cycle (AMI)... ok
two-element cycle... ok
two-element cycle (AMI)... ok
known derived pointer slicing as base... ok
known derived pointer slicing as base (AMI)... ok
known derived pointer slicing as derived... ok
known derived pointer slicing as derived (AMI)... ok
unknown derived pointer slicing as base... ok
unknown derived pointer slicing as base (AMI)... ok
param ptr slicing with known first... ok
param ptr slicing with known first (AMI)... ok
param ptr slicing with unknown first... ok
param ptr slicing with unknown first (AMI)... ok
return value identity with known first... ok
return value identity with known first (AMI)... ok
return value identity with unknown first... ok
return value identity with unknown first (AMI)... ok
return value identity for input params known first... Error using assert
Assertion failed.

Error in AllTests.allTests (line 484)
            assert(strcmp(b2.ice_id(), '::Test::B'));  % Sliced by server

Error in Client (line 14)
    test = AllTests.allTests(helper);

Error in runTest (line 28)
        Client(varargin);
exit status 1
Traceback (most recent call last):
  File "/home/runner/work/ice/ice/scripts/Util.py", line 2050, in run
    self.runWithDriver(current)
  File "/home/runner/work/ice/ice/scripts/Util.py", line 2081, in runWithDriver
    current.driver.runClientServerTestCase(current)
  File "/home/runner/work/ice/ice/scripts/LocalDriver.py", line 680, in runClientServerTestCase
    self.runner.runClientSide(client, current, host)
  File "/home/runner/work/ice/ice/scripts/LocalDriver.py", line 207, in runClientSide
    testcase._runClientSide(current, host)
  File "/home/runner/work/ice/ice/scripts/Util.py", line 2027, in _runClientSide
    self.runClientSide(current)
  File "/home/runner/work/ice/ice/scripts/Util.py", line 1913, in runClientSide
    self._runClient(current, client)
  File "/home/runner/work/ice/ice/scripts/Util.py", line 2039, in _runClient
    client.run(current)
  File "/home/runner/work/ice/ice/scripts/Util.py", line 1441, in run
    process.waitSuccess(exitstatus=exitstatus, timeout=30)
  File "/home/runner/work/ice/ice/scripts/Expect.py", line 691, in waitSuccess
    self.testExitStatus(exitstatus)
  File "/home/runner/work/ice/ice/scripts/Expect.py", line 735, in testExitStatus
    test(self.exitstatus, exitstatus)
  File "/home/runner/work/ice/ice/scripts/Expect.py", line 717, in test
    raise RuntimeError(
RuntimeError: unexpected exit status: expected: 0, got 1
```

**Comment by bernardnormier** [comment]
To reenable these tests, see:
https://github.com/zeroc-ice/ice/blob/7ebe256825c6ca101d0edcebab1e7081c7befb8a/.github/workflows/ci.yml#L86

**Comment by bernardnormier** [comment]
I commented out the portions of the tests that fail and reenabled CI for these two tests.
