### ISSUE TITLE
python Ice/info failure

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#215]
```
[ running client/server test - 09/25/18 17:25:15 ]
- Config: tcp,shared
("/usr/bin/python" /home/vagrant/workspace/ice/3.7/python/test/TestHelper.py Server.py --Ice.Warn.Connections=1 --Ice.PrintAdapterReady=1 --Ice.ThreadPool.Server.Size=1 --Ice.Default.Protocol=tcp --Ice.Default.Host=127.0.0.1 --Ice.IPv6=0 --Ice.ThreadPool.Server.SizeMax=3 --Test.BasePort=14100 --Ice.ThreadPool.Server.SizeWarn=0 env={'PYTHONPATH': '/home/vagrant/workspace/ice/3.7/python/python:/home/vagrant/workspace/ice/3.7/python/test/Ice/info', 'LD_LIBRARY_PATH': '/home/vagrant/workspace/ice/3.7/cpp/lib64'})
("/usr/bin/python" /home/vagrant/workspace/ice/3.7/python/test/TestHelper.py Client.py --Ice.Default.Host=127.0.0.1 --Test.BasePort=14100 --Ice.IPv6=0 --Ice.Default.Protocol=tcp --Ice.Warn.Connections=1 env={'PYTHONPATH': '/home/vagrant/workspace/ice/3.7/python/python:/home/vagrant/workspace/ice/3.7/python/test/Ice/info', 'LD_LIBRARY_PATH': '/home/vagrant/workspace/ice/3.7/cpp/lib64'})
testing proxy endpoint information... ok
test object adapter endpoint information... Traceback (most recent call last):
File "/home/vagrant/workspace/ice/3.7/python/test/TestHelper.py", line 99, in run
helper.run(sys.argv[2:])
File "/home/vagrant/workspace/ice/3.7/python/test/Ice/info/Client.py", line 20, in run
AllTests.allTests(self, communicator)
File "/home/vagrant/workspace/ice/3.7/python/test/Ice/info/AllTests.py", line 109, in allTests
adapter = communicator.createObjectAdapter("TestAdapter")
File "/home/vagrant/workspace/ice/3.7/python/python/Ice/__init__.py", line 961, in createObjectAdapter
adapter = self._impl.createObjectAdapter(name)
SocketException: Ice.SocketException:
Address already in use
```

**Comment by nereaaaa** [comment]
¿conseguiste solucionarlo? , me sale el mismo error
