### ISSUE TITLE
java-compat Ice/interrupt test failure

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#216]
```[ running collocated test - 09/26/18 04:51:35 ]
- Config: Release,x64
(C:\Program Files\Java\jdk1.8.0_181\bin\java -Dtest.class=test.Ice.interrupt.Collocated test.TestDriver --Ice.Default.Host=127.0.0.1 --Test.BasePort=14000 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp --Ice.IPv6=0 env={'CLASSPATH': 'C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice-3.7\\builds\\ice-VC140-default\\java-compat\\lib\\test.jar'})
testing client interrupt... -! 9/26/18 04:51:38:172 warning: Ice.ThreadPool.Server-0: dispatch exception:
identity: test
facet:
operation: opIdempotent
Ice.UnknownException
unknown = ""
at test.Ice.interrupt.TestI.opIdempotent(TestI.java:29)
at test.Ice.interrupt.Test._TestIntfDisp._iceD_opIdempotent(_TestIntfDisp.java:107)
at test.Ice.interrupt.Test._TestIntfDisp._iceDispatch(_TestIntfDisp.java:194)
at IceInternal.Incoming.invoke(Incoming.java:214)
at IceInternal.CollocatedRequestHandler.invokeAll(CollocatedRequestHandler.java:325)
at IceInternal.CollocatedRequestHandler.access$100(CollocatedRequestHandler.java:12)
at IceInternal.CollocatedRequestHandler$InvokeAllAsync.run(CollocatedRequestHandler.java:29)
at IceInternal.ThreadPool.dispatchFromThisThread(ThreadPool.java:355)
at IceInternal.ThreadPoolCurrent.dispatchFromThisThread(ThreadPoolCurrent.java:43)
at IceInternal.DispatchWorkItem.execute(DispatchWorkItem.java:34)
at IceInternal.ThreadPoolWorkQueue.message(ThreadPoolWorkQueue.java:79)
at IceInternal.ThreadPool.run(ThreadPool.java:401)
at IceInternal.ThreadPool.access$500(ThreadPool.java:12)
at IceInternal.ThreadPool$EventHandlerThread.run(ThreadPool.java:770)
at java.lang.Thread.run(Thread.java:748)
-! 9/26/18 04:51:38:174 warning: Ice.ThreadPool.Server-0: dispatch exception:
identity: test
facet:
operation: opIdempotent
Ice.UnknownException
unknown = ""
at test.Ice.interrupt.TestI.opIdempotent(TestI.java:29)
at test.Ice.interrupt.Test._TestIntfDisp._iceD_opIdempotent(_TestIntfDisp.java:107)
at test.Ice.interrupt.Test._TestIntfDisp._iceDispatch(_TestIntfDisp.java:194)
at IceInternal.Incoming.invoke(Incoming.java:214)
at IceInternal.CollocatedRequestHandler.invokeAll(CollocatedRequestHandler.java:325)
at IceInternal.CollocatedRequestHandler.access$100(CollocatedRequestHandler.java:12)
at IceInternal.CollocatedRequestHandler$InvokeAllAsync.run(CollocatedRequestHandler.java:29)
at IceInternal.ThreadPool.dispatchFromThisThread(ThreadPool.java:355)
at IceInternal.ThreadPoolCurrent.dispatchFromThisThread(ThreadPoolCurrent.java:43)
at IceInternal.DispatchWorkItem.execute(DispatchWorkItem.java:34)
at IceInternal.ThreadPoolWorkQueue.message(ThreadPoolWorkQueue.java:79)
at IceInternal.ThreadPool.run(ThreadPool.java:401)
at IceInternal.ThreadPool.access$500(ThreadPool.java:12)
at IceInternal.ThreadPool$EventHandlerThread.run(ThreadPool.java:770)
at java.lang.Thread.run(Thread.java:748)
java.lang.RuntimeException: Ice.UnknownException
unknown = ""
at test.Ice.interrupt.Collocated.run(Collocated.java:48)
at test.TestDriver.main(TestDriver.java:22)
Caused by: Ice.UnknownException
unknown = ""
at IceInternal.AsyncResultI.waitForResponseOrUserEx(AsyncResultI.java:270)
at Ice.ObjectPrxHelperBase._end(ObjectPrxHelperBase.java:2708)
at test.Ice.interrupt.Test.TestIntfPrxHelper.end_opIdempotent(TestIntfPrxHelper.java:249)
at test.Ice.interrupt.Test.TestIntfPrxHelper._iceI_opIdempotent(TestIntfPrxHelper.java:154)
at test.Ice.interrupt.Test.TestIntfPrxHelper.opIdempotent(TestIntfPrxHelper.java:144)
at test.Ice.interrupt.AllTests.allTests(AllTests.java:259)
at test.Ice.interrupt.Collocated.run(Collocated.java:44)
... 1 more
test in Ice/interrupt failed:
Traceback (most recent call last):
File "..\scripts\Util.py", line 1567, in run
self.runWithDriver(current)
File "..\scripts\Util.py", line 1585, in runWithDriver
current.driver.runTestCase(current)
File "..\scripts\LocalDriver.py", line 598, in runTestCase
current.testcase._runClientSide(current)
File "..\scripts\Util.py", line 1544, in _runClientSide
self.runClientSide(current)
File "..\scripts\Util.py", line 1440, in runClientSide
self._runClient(current, client)
File "..\scripts\Util.py", line 1556, in _runClient
client.run(current)
File "..\scripts\Util.py", line 1089, in run
process.waitSuccess(exitstatus=exitstatus, timeout=30)
File "..\scripts\Expect.py", line 638, in waitSuccess
test(self.exitstatus, exitstatus)
File "..\scripts\Expect.py", line 625, in test
raise RuntimeError("unexpected exit status: expected: %d, got %d\n" % (expected, result))
RuntimeError: unexpected exit status: expected: 0, got 1
Traceback (most recent call last):
File "..\scripts\LocalDriver.py", line 500, in runTestSuite
testcase.run(current)
File "..\scripts\Util.py", line 1567, in run
self.runWithDriver(current)
File "..\scripts\Util.py", line 1585, in runWithDriver
current.driver.runTestCase(current)
File "..\scripts\LocalDriver.py", line 598, in runTestCase
current.testcase._runClientSide(current)
File "..\scripts\Util.py", line 1544, in _runClientSide
self.runClientSide(current)
File "..\scripts\Util.py", line 1440, in runClientSide
self._runClient(current, client)
File "..\scripts\Util.py", line 1556, in _runClient
client.run(current)
File "..\scripts\Util.py", line 1089, in run
process.waitSuccess(exitstatus=exitstatus, timeout=30)
File "..\scripts\Expect.py", line 638, in waitSuccess
test(self.exitstatus, exitstatus)
File "..\scripts\Expect.py", line 625, in test
raise RuntimeError("unexpected exit status: expected: %d, got %d\n" % (expected, result))
RuntimeError: unexpected exit status: expected: 0, got 1
```

**Comment by pepone** [comment]
https://github.com/zeroc-ice/ice/commit/8568cc74116826984d82d90e2035366e145d0eb6
