### ISSUE TITLE
Ice/timeout failure in CI with xcodesdk

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#2480]
```
*** [35/36] Running cpp/Ice/timeout tests ***
[ running client/server test - 07/12/24 19:36:11 ]
- Config: ssl,xcodesdk,iphonesimulator
(executing `Ice/timeout/server' on `iOS Simulator (iOS-18-0)' args = ['--Ice.Default.Host=127.0.0.1', '--Ice.Warn.Connections=1', '--Ice.Default.Protocol=ssl', '--Ice.IPv6=0', '--IceSSL.***', '--IceSSL.DefaultDir=/Users/runner/work/ice/ice/certs', '--IceSSL.CAs=cacert.pem', '--IceSSL.CertFile=server.p12', '--IceSSL.KeychainPassword=password', '--IceSSL.Keychain=server.keychain', '--Ice.PrintStackTraces=1', '--Ice.ThreadPool.Server.Size=1', '--Ice.ThreadPool.Server.SizeMax=3', '--Ice.ThreadPool.Server.SizeWarn=0'])
(executing `Ice/timeout/client' on `iOS Simulator (iOS-18-0)' args = ['--Ice.Default.Host=127.0.0.1', '--Ice.Warn.Connections=1', '--Ice.Default.Protocol=ssl', '--Ice.IPv6=0', '--IceSSL.***', '--IceSSL.DefaultDir=/Users/runner/work/ice/ice/certs', '--IceSSL.CAs=cacert.pem', '--IceSSL.CertFile=client.p12', '--IceSSL.KeychainPassword=password', '--IceSSL.Keychain=client.keychain', '--Ice.PrintStackTraces=1'])
testing connect timeout... unexpected exception while running `Ice/timeout client':
connection establishment timed out
Traceback (most recent call last):
  File "/Users/runner/work/ice/ice/cpp/../scripts/Util.py", line 1407, in run
    process.waitSuccess(exitstatus=exitstatus, timeout=30)
  File "/Users/runner/work/ice/ice/cpp/../scripts/Util.py", line 2501, in waitSuccess
    raise RuntimeError(
RuntimeError: unexpected exit status: expected: 0, got 1
```

**Comment by bernardnormier** [comment]
Most likely fixed by #3215.
