### ISSUE TITLE
Python Ice/ami test failures

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#2523]
```
testing sent callback... C:\Users\jose\source\repos\3.8\ice\python\test\Ice\ami\AllTests.py:324: DeprecationWarning: currentThread() is deprecated, use current_thread() instead
  self._thread = threading.currentThread()
C:\Users\jose\source\repos\3.8\ice\python\test\Ice\ami\AllTests.py:330: DeprecationWarning: currentThread() is deprecated, use current_thread() instead
  test(self._thread != threading.currentThread())
ok
testing batch requests with proxy... C:\Users\jose\source\repos\3.8\ice\python\test\Ice\ami\AllTests.py:337: DeprecationWarning: currentThread() is deprecated, use current_thread() instead
  self._thread = threading.currentThread()
C:\Users\jose\source\repos\3.8\ice\python\test\Ice\ami\AllTests.py:344: DeprecationWarning: currentThread() is deprecated, use current_thread() instead
  test(self._thread != threading.currentThread())
Traceback (most recent call last):
  File "C:\Users\jose\source\repos\3.8\ice\python\test\TestHelper.py", line 89, in run
    helper.run(sys.argv[2:])
  File "C:\Users\jose\source\repos\3.8\ice\python\test\Ice\ami\Collocated.py", line 47, in run
    AllTests.allTestsFuture(self, communicator, True)
  File "C:\Users\jose\source\repos\3.8\ice\python\test\Ice\ami\AllTests.py", line 796, in allTestsFuture
    test(f.done())
  File "C:\Users\jose\source\repos\3.8\ice\python\test\Ice\ami\AllTests.py", line 15, in test
    raise RuntimeError("test assertion failed")
RuntimeError: test assertion failed
unexpected exit status: expected: 0, got 1
```

Failure corresponds with this code:

https://github.com/zeroc-ice/ice/blob/45a69a1fe2f1f973af990e5d8642b3172bb5258d/python/test/Ice/ami/AllTests.py#L790-L796

Seems to only fail with the collocated test case. I hit this with python_d on Windows in case this matters.

**Comment by pepone** [comment]
cannot reproduce
