### ISSUE TITLE
csharp/Ice/metrics failure (CI, release ubuntu)

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#2567]
From https://github.com/zeroc-ice/ice/actions/runs/10084670618/job/27883975019?pr=2566 (a Ruby PR)

```
*** [125/301] Running csharp/Ice/metrics tests ***
[ running client/server test - 07/24/24 22:47:32 ]
- Config: tcp
(dotnet /home/runner/work/ice/ice/csharp/test/Ice/metrics/msbuild/server/net8.0/server.dll --Ice.Default.Host=127.0.0.1 --Test.BasePort=14200 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp --Ice.IPv6=0 --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 --Ice.Trace.Network=2 --Ice.Trace.Retry=1 --Ice.Trace.Protocol=1 --Ice.LogFile=/home/runner/work/ice/ice/csharp/test/Ice/metrics/server-072424-2247.log)
(dotnet /home/runner/work/ice/ice/csharp/test/Ice/metrics/msbuild/client/net8.0/client.dll --Ice.Default.Host=127.0.0.1 --Test.BasePort=14200 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp --Ice.IPv6=0 --Ice.Trace.Network=2 --Ice.Trace.Retry=1 --Ice.Trace.Protocol=1 --Ice.LogFile=/home/runner/work/ice/ice/csharp/test/Ice/metrics/client-072424-2247.log)
testing metrics admin facet checkedCast... ok
testing group by none...ok
testing group by id...ok
testing connection metrics... ok
testing connection establishment metrics... ok
testing endpoint lookup metrics... ok
testing dispatch metrics... ok
testing dispatch metrics with forwarding object adapter... ok
testing invocation metrics... ok
testing metrics view enable/disable...ok
testing instrumentation observer delegate... ok
[ running client/server test - 07/24/24 22:47:35 ]
- Config: ssl,serialize,mx
(dotnet /home/runner/work/ice/ice/csharp/test/Ice/metrics/msbuild/server/net8.0/server.dll --Ice.Default.Host=127.0.0.1 --Test.BasePort=14200 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.ThreadPool.Server.Serialize=1 --Ice.IPv6=0 --Ice.Admin.Endpoints="tcp -h 127.0.0.1" --Ice.Admin.InstanceName=Server --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --IceSSL.*** --IceSSL.DefaultDir=/home/runner/work/ice/ice/certs --IceSSL.CAs=cacert.pem --IceSSL.VerifyPeer=2 --IceSSL.CertFile=server.p12 --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 --Ice.Trace.Network=2 --Ice.Trace.Retry=1 --Ice.Trace.Protocol=1 --Ice.LogFile=/home/runner/work/ice/ice/csharp/test/Ice/metrics/server-072424-2247.log)
(dotnet /home/runner/work/ice/ice/csharp/test/Ice/metrics/msbuild/client/net8.0/client.dll --Ice.Default.Host=127.0.0.1 --Test.BasePort=14200 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.ThreadPool.Server.Serialize=1 --Ice.IPv6=0 --Ice.Admin.Endpoints="tcp -h 127.0.0.1" --Ice.Admin.InstanceName=Client --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --IceSSL.*** --IceSSL.DefaultDir=/home/runner/work/ice/ice/certs --IceSSL.CAs=cacert.pem --IceSSL.VerifyPeer=2 --IceSSL.CertFile=client.p12 --Ice.Trace.Network=2 --Ice.Trace.Retry=1 --Ice.Trace.Protocol=1 --Ice.LogFile=/home/runner/work/ice/ice/csharp/test/Ice/metrics/client-072424-2247.log)
testing metrics admin facet checkedCast... ok
testing group by none...ok
testing group by id...ok
testing connection metrics... ok
testing connection establishment metrics... ok
testing endpoint lookup metrics... ok
testing dispatch metrics... ok
testing dispatch metrics with forwarding object adapter... ok
testing invocation metrics... 
im1.current: 1
im1.total: 2
im1.failures: 0
im1.retry: 0
Ice.UnknownException: System.NullReferenceException: Object reference not set to an instance of an object.
   at IceMX.MetricsFailures.ice_write(OutputStream ostr, MetricsFailures v) in /home/runner/work/ice/ice/csharp/src/Ice/generated/Metrics.cs:line 159
   at IceMX.MetricsAdmin.iceD_getMetricsFailuresAsync(MetricsAdmin obj, IncomingRequest request) in /home/runner/work/ice/ice/csharp/src/Ice/generated/Metrics.cs:line 1614
   at IceMX.MetricsAdminDisp_.dispatchAsync(IncomingRequest request) in /home/runner/work/ice/ice/csharp/src/Ice/generated/Metrics.cs:line 1498
   at Ice.Internal.ServantManager.dispatchAsync(IncomingRequest request) in /home/runner/work/ice/ice/csharp/src/Ice/Internal/ServantManager.cs:line 26
   at Ice.Internal.ObserverMiddleware.<>c__DisplayClass2_0.<<dispatchAsync>g__performDispatchAsync|0>d.MoveNext() in /home/runner/work/ice/ice/csharp/src/Ice/Internal/ObserverMiddleware.cs:line 29
   at IceMX.MetricsAdminPrxHelper.getMetricsFailures(String view, String map, String id, Dictionary`2 context) in /home/runner/work/ice/ice/csharp/src/Ice/generated/Metrics.cs:line 1139
   at AllTests.allTests(TestHelper helper, CommunicatorObserverI obsv) in /home/runner/work/ice/ice/csharp/test/Ice/metrics/AllTests.cs:line 1256
   at Client.runAsync(String[] args) in /home/runner/work/ice/ice/csharp/test/Ice/metrics/Client.cs:line 27
   at Test.TestDriver.runTestAsync[T](String[] args) in /home/runner/work/ice/ice/csharp/test/TestCommon/TestHelper.cs:line 232
saved /home/runner/work/ice/ice/csharp/test/Ice/metrics/client-072424-2247.log
saved /home/runner/work/ice/ice/csharp/test/Ice/metrics/server-072424-2247.log
```

**Comment by bernardnormier** [comment]
Same failure with https://github.com/zeroc-ice/ice/actions/runs/10083898519/job/27881518226?pr=2565
