### ISSUE TITLE
cpp/Glacier2/ssl failure (CI windows debug)

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#2568]
From https://github.com/zeroc-ice/ice/actions/runs/10084670618/job/27883976222?pr=2566 (a Ruby PR):

```
*** [70/85] Running cpp/Glacier2/ssl tests ***
[ running client/server test - 07/24/24 22:34:11 ]
- Config: ssl,mx,x64,Debug
starting Glacier2 router... (D:\a\ice\ice\cpp\bin\x64\Debug\glacier2router.exe --Ice.Default.Host=127.0.0.1 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --Ice.Admin.Endpoints="tcp -p 14102" --Ice.Admin.InstanceName=Glacier2 --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --IceSSL.*** --IceSSL.DefaultDir=D:\a\ice\ice\certs --IceSSL.CAs=cacert.pem --IceSSL.CertFile=server.p12 --Ice.PrintStackTraces=1 --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 --Glacier2.Client.Endpoints="tcp -p 14100:ssl -p 14101" --Glacier2.Server.Endpoints=tcp --Glacier2.CryptPasswords=D:\a\ice\ice\cpp\test\Glacier2\ssl\passwords --Ice.Warn.Dispatch=0 --Glacier2.AddConnectionContext=1 --Glacier2.SessionManager="sessionmanager:tcp -p 14103" --Glacier2.PermissionsVerifier="verifier:tcp -p 14103" --Glacier2.SSLSessionManager="sslsessionmanager:tcp -p 14103" --Glacier2.SSLPermissionsVerifier="sslverifier:tcp -p 14103" env={'PATH': 'D:\\a\\ice\\ice\\cpp\\test\\Common\\msbuild\\x64\\Debug;D:\\a\\ice\\ice\\cpp\\bin\\x64\\Debug'})
ok
(D:\a\ice\ice\cpp\test\Glacier2\ssl\msbuild\server\x64\Debug\server.exe --Ice.Default.Host=127.0.0.1 --Test.BasePort=14100 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --Ice.Admin.Endpoints="tcp -h 127.0.0.1" --Ice.Admin.InstanceName=Server --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --IceSSL.*** --IceSSL.DefaultDir=D:\a\ice\ice\certs --IceSSL.CAs=cacert.pem --IceSSL.CertFile=server.p12 --Ice.PrintStackTraces=1 --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 env={'PATH': 'D:\\a\\ice\\ice\\cpp\\test\\Common\\msbuild\\x64\\Debug;D:\\a\\ice\\ice\\cpp\\bin\\x64\\Debug'})
(D:\a\ice\ice\cpp\test\Glacier2\ssl\msbuild\client\x64\Debug\client.exe --Ice.Default.Host=127.0.0.1 --Test.BasePort=14100 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --Ice.Admin.Endpoints="tcp -h 127.0.0.1" --Ice.Admin.InstanceName=Client --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --IceSSL.*** --IceSSL.DefaultDir=D:\a\ice\ice\certs --IceSSL.CAs=cacert.pem --IceSSL.CertFile=client.p12 --Ice.PrintStackTraces=1 env={'PATH': 'D:\\a\\ice\\ice\\cpp\\test\\Common\\msbuild\\x64\\Debug;D:\\a\\ice\\ice\\cpp\\bin\\x64\\Debug'})
creating non-ssl session with tcp connection... ok
creating ssl session with tcp connection... ok
creating non-ssl session with ssl connection... ok
creating ssl session with ssl connection... ok
abort() has been called

test in Glacier2/ssl failed:
Traceback (most recent call last):
  File "D:\a\ice\ice\cpp\..\scripts\Util.py", line 1508, in stop
    process.waitSuccess(exitstatus=exitstatus, timeout=30)
  File "D:\a\ice\ice\cpp\..\scripts\Expect.py", line 691, in waitSuccess
    self.testExitStatus(exitstatus)
  File "D:\a\ice\ice\cpp\..\scripts\Expect.py", line 735, in testExitStatus
    test(self.exitstatus, exitstatus)
  File "D:\a\ice\ice\cpp\..\scripts\Expect.py", line 717, in test
    raise RuntimeError(
RuntimeError: unexpected exit status: expected: 0, got 3221226505

```

**Comment by bernardnormier** [comment]
I can't reproduce this bug. It's unclear where the "abort() has been called" message comes from.
