### ISSUE TITLE
JavaScript timeout test failure on Safari

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice#262]
```
[ running client/server test - 10/29/18 16:56:39 ]
- Config: wss,es5,worker,Safari:7050
(/Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice-3.7/builds/ice-clang-default/cpp/test/Ice/timeout/build/macosx/shared/server --Ice.Plugin.IceSSL=IceSSL:createIceSSL --Ice.PrintAdapterReady=1 --Ice.Trace.Protocol=1 --Ice.NullHandleAbort=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.Size=1 --Ice.Warn.Connections=1 --Ice.ThreadPool.Server.SizeWarn=0 --IceSSL.CertFile=server.p12 --Ice.Trace.Retry=1 --IceSSL.KeychainPassword=password --IceSSL.DefaultDir=/Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice-3.7/builds/ice-clang-default/certs --Ice.PrintStackTraces=1 --IceSSL.Password=password --IceSSL.Keychain=server.keychain --Ice.Trace.Network=2 --Ice.Default.Protocol=wss --Ice.Default.Host=127.0.0.1 --Ice.IPv6=0 --Ice.LogFile=/Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice-3.7/builds/ice-clang-default/js/test/Ice/timeout/server-102918-1656.log --IceSSL.CAs=cacert.pem --IceSSL.VerifyPeer=0)
(executing `Ice/timeout/Client' on `<selenium.webdriver.safari.webdriver.WebDriver (session="2E323970-DC79-4C0B-82E8-D57C1D81A40B")>' args = ['--Ice.Default.Host=127.0.0.1', '--Ice.Warn.Connections=1', '--Ice.IPv6=0', '--Ice.Default.Protocol=wss'])
testing connect timeout... ok
testing connection timeout... ok
testing invocation timeout... ok
testing close timeout... ok
testing timeout overrides... unexpected exception while running test: Error: test failed
unexpected exception while running test: Error: test failed
saved /Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice-3.7/builds/ice-clang-default/js/test/Ice/timeout/server-102918-1656.log
```

**Comment by pepone** [comment]
I cannot reproduce this with Safari 12 on macOS Mojave

**Comment by bentoi** [comment]
It still occurs with dist testing
```
 running client/server test - 11/12/18 12:09:11 ]
- Config: es5,wss,worker,Safari:7050
(/Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice-3.7/builds/ice-clang-default/cpp/test/Ice/timeout/build/macosx/shared/server --Ice.Plugin.IceSSL=IceSSL:createIceSSL --Ice.PrintAdapterReady=1 --Ice.Trace.Protocol=1 --Ice.NullHandleAbort=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.Size=1 --Ice.Warn.Connections=1 --Ice.ThreadPool.Server.SizeWarn=0 --IceSSL.CertFile=server.p12 --Ice.Trace.Retry=1 --IceSSL.KeychainPassword=password --IceSSL.DefaultDir=/Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice-3.7/builds/ice-clang-default/certs --Ice.PrintStackTraces=1 --IceSSL.Password=password --IceSSL.Keychain=server.keychain --Ice.Trace.Network=2 --Ice.Default.Protocol=wss --Ice.Default.Host=127.0.0.1 --Ice.IPv6=0 --Ice.LogFile=/Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice-3.7/builds/ice-clang-default/js/test/Ice/timeout/server-111218-1209.log --IceSSL.CAs=cacert.pem --IceSSL.VerifyPeer=0)
(executing `Ice/timeout/Client' on `<selenium.webdriver.safari.webdriver.WebDriver (session="F7E0D6BF-5C3B-4859-9E3F-8EF7EB59D60C")>' args = ['--Ice.Default.Host=127.0.0.1', '--Ice.Warn.Connections=1', '--Ice.IPv6=0', '--Ice.Default.Protocol=wss'])
testing connect timeout... ok
testing connection timeout... ok
testing invocation timeout... ok
testing close timeout... ok
testing timeout overrides... unexpected exception while running test: Error: test failed
unexpected exception while running test: Error: test failed
saved /Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice-3.7/builds/ice-clang-default/js/test/Ice/timeout/server-111218-1209.log
Traceback (most recent call last):
File "../scripts/Util.py", line 1637, in run
self.runWithDriver(current)
File "../scripts/Util.py", line 1666, in runWithDriver
current.driver.runClientServerTestCase(current)
File "../scripts/LocalDriver.py", line 564, in runClientServerTestCase
self.runner.runClientSide(client, current, host)
File "../scripts/LocalDriver.py", line 202, in runClientSide
testcase._runClientSide(current, host)
File "../scripts/Util.py", line 1614, in _runClientSide
self.runClientSide(current)
File "../scripts/Util.py", line 1506, in runClientSide
self._runClient(current, client)
File "../scripts/Util.py", line 1626, in _runClient
client.run(current)
File "../scripts/Util.py", line 1150, in run
self.stop(current, True, exitstatus)
File "../scripts/Util.py", line 1214, in stop
process.waitSuccess(exitstatus=exitstatus, timeout=30)
File "../scripts/Util.py", line 2080, in waitSuccess
raise RuntimeError("unexpected exit status: expected: %d, got %d\n" % (exitstatus, result))
RuntimeError: unexpected exit status: expected: 0, got 1
```

**Comment by pepone** [comment]
Happen on Windows server 2016 too

```
testing timeout overrides... unexpected exception while running test: Error: test failed
Error: test failed
at test (http://127.0.0.1:8080/test/es5/Common/TestHelper.js:197:11)
at _callee2$ (http://127.0.0.1:8080/test/es5/Ice/timeout/Client.js:665:19)
at tryCatch (http://127.0.0.1:8080/node_modules/@babel/polyfill/dist/polyfill.js:5901:7)
at invoke (http://127.0.0.1:8080/node_modules/@babel/polyfill/dist/polyfill.js:6135:9)
at prototype[method] (http://127.0.0.1:8080/node_modules/@babel/polyfill/dist/polyfill.js:5953:9)
at asyncGeneratorStep (http://127.0.0.1:8080/test/es5/Ice/timeout/Client.js:13:84)
at _next (http://127.0.0.1:8080/test/es5/Ice/timeout/Client.js:15:194)
at run (http://127.0.0.1:8080/node_modules/@babel/polyfill/dist/polyfill.js:4237:13)
at Anonymous function (http://127.0.0.1:8080/node_modules/@babel/polyfill/dist/polyfill.js:4254:30)
at flush (http://127.0.0.1:8080/node_modules/@babel/polyfill/dist/polyfill.js:1422:9)
unexpected exception while running test: Error: test failed
Error: test failed
at test (http://127.0.0.1:8080/test/es5/Common/TestHelper.js:197:11)
at _callee2$ (http://127.0.0.1:8080/test/es5/Ice/timeout/Client.js:665:19)
at tryCatch (http://127.0.0.1:8080/node_modules/@babel/polyfill/dist/polyfill.js:5901:7)
```

It is failing in the es5 generated code corresponding with

https://github.com/zeroc-ice/ice/blob/c3ae583dc8c184bc1a094a1ae7d1be769c69b9fb/js/test/Ice/timeout/Client.js#L368

**Comment by bentoi** [comment]
Happened on mojave distribution testing build 620.

```
[ running client/server test - 12/10/18 05:18:23 ]
- Config: es5,wss,worker,Safari:7050
(/Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice-3.7/builds/ice-clang-default/cpp/test/Ice/timeout/build/macosx/shared/server --Ice.Plugin.IceSSL=IceSSL:createIceSSL --Ice.PrintAdapterReady=1 --Ice.Trace.Protocol=1 --Ice.NullHandleAbort=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.Size=1 --Ice.Warn.Connections=1 --Ice.ThreadPool.Server.SizeWarn=0 --IceSSL.CertFile=server.p12 --Ice.Trace.Retry=1 --IceSSL.KeychainPassword=password --IceSSL.DefaultDir=/Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice-3.7/builds/ice-clang-default/certs --Ice.PrintStackTraces=1 --IceSSL.Password=password --IceSSL.Keychain=server.keychain --Ice.Trace.Network=2 --Ice.Default.Protocol=wss --Ice.Default.Host=127.0.0.1 --Ice.IPv6=0 --Ice.LogFile=/Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice-3.7/builds/ice-clang-default/js/test/Ice/timeout/server-121018-0518.log --IceSSL.CAs=cacert.pem --IceSSL.VerifyPeer=0)
(executing `Ice/timeout/Client' on `<selenium.webdriver.safari.webdriver.WebDriver (session="0A503328-B7EF-4220-9DEE-303B3D254C3B")>' args = ['--Ice.Default.Host=127.0.0.1', '--Ice.Warn.Connections=1', '--Ice.IPv6=0', '--Ice.Default.Protocol=wss'])
testing connect timeout... ok
testing connection timeout... ok
testing invocation timeout... ok
testing close timeout... ok
testing timeout overrides... unexpected exception while running test: Error: test failed
Error: destroy take 20103 ms, expected less than 8000 ms
undefined
unexpected exception while running test: Error: test failed
Error: destroy take 20103 ms, expected less than 8000 ms
undefined
saved /Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice-3.7/builds/ice-clang-default/js/test/Ice/timeout/server-121018-0518.log
Traceback (most recent call last):
File "../scripts/Util.py", line 1635, in run
self.runWithDriver(current)
File "../scripts/Util.py", line 1664, in runWithDriver
current.driver.runClientServerTestCase(current)
File "../scripts/LocalDriver.py", line 570, in runClientServerTestCase
self.runner.runClientSide(client, current, host)
File "../scripts/LocalDriver.py", line 202, in runClientSide
testcase._runClientSide(current, host)
File "../scripts/Util.py", line 1612, in _runClientSide
self.runClientSide(current)
File "../scripts/Util.py", line 1504, in runClientSide
self._runClient(current, client)
File "../scripts/Util.py", line 1624, in _runClient
client.run(current)
File "../scripts/Util.py", line 1148, in run
self.stop(current, True, exitstatus)
File "../scripts/Util.py", line 1212, in stop
process.waitSuccess(exitstatus=exitstatus, timeout=30)
File "../scripts/Util.py", line 2070, in waitSuccess
raise RuntimeError("unexpected exit status: expected: %d, got %d\n" % (exitstatus, result))
RuntimeError: unexpected exit status: expected: 0, got 1
```
