### ISSUE TITLE
cpp/java IceSSL/configuration failure in CI

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#2667]
Windows:
```
*** [63/261] Running cpp/IceSSL/configuration tests ***
[ running client/server test - 08/21/24 14:09:35 ]
- Config: x64
(D:\a\ice\ice\cpp\test\IceSSL\configuration\msbuild\server\x64\Release\server.exe --Ice.Default.Host=127.0.0.1 --Test.BasePort=14200 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp --Ice.IPv6=0 --Ice.PrintStackTraces=1 --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 "D:\a\ice\ice\cpp\test\IceSSL\configuration" env={'PATH': 'D:\\a\\ice\\ice\\cpp\\test\\Common\\msbuild\\x64\\Release;D:\\a\\ice\\ice\\cpp\\bin\\x64\\Release'})
(D:\a\ice\ice\cpp\test\IceSSL\configuration\msbuild\client\x64\Release\client.exe --Ice.Default.Host=127.0.0.1 --Test.BasePort=14200 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp --Ice.IPv6=0 --Ice.PrintStackTraces=1 "D:\a\ice\ice\cpp\test\IceSSL\configuration" env={'PATH': 'D:\\a\\ice\\ice\\cpp\\test\\Common\\msbuild\\x64\\Release;D:\\a\\ice\\ice\\cpp\\bin\\x64\\Release'})
testing with Schannel native APIs...
client validates server certificate setting trusted root certificates... ok
client validates server certificate using validation callback... ok
client validates server using system trusted root certificates... error: D:\a\ice\ice\cpp\src\Ice\ConnectionI.cpp:2355 ::Ice::ConnectTimeoutException connection establishment timed out
stack trace:
  0 Ice::LocalException::LocalException at D:\a\ice\ice\cpp\include\Ice\LocalException.h:25
  1 Ice::TimeoutException::TimeoutException
  2 Ice::ConnectTimeoutException::ConnectTimeoutException at D:\a\ice\ice\cpp\include\Ice\LocalExceptions.h:314
  3 `anonymous namespace'::ConnectTimerTask::runTimerTask at D:\a\ice\ice\cpp\src\Ice\ConnectionI.cpp:50
  4 IceInternal::ThreadObserverTimer::runTimerTask at D:\a\ice\ice\cpp\src\Ice\Instance.cpp:254
  5 Ice::Timer::run at D:\a\ice\ice\cpp\src\Ice\Timer.cpp:128
  6 std::thread::_Invoke<std::tuple<void (__cdecl IceInternal::ThreadPool::EventHandlerThread::*)(void),IceInternal::ThreadPool::EventHandlerThread *>,0,1> at C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.40.33807\include\thread:61
  7 00007fff41c66b4c
  8 00007fff43154cb0
  9 00007fff43ebeceb
!! 08/21/24 14:10:56715 error: communicator not destroyed during global destruction.
```

macOS:
```
*** [131/332] Running java/IceSSL/configuration tests ***
[ running client/server test - 08/21/24 13:43:54 ]
(/Users/runner/hostedtoolcache/Java_Oracle_jdk/17/arm64/Contents/Home/bin/java -ea -Dtest.class=test.IceSSL.configuration.Server test.TestDriver --Ice.Default.Host=127.0.0.1 --Test.BasePort=14200 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp --Ice.IPv6=0 --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 "/Users/runner/work/ice/ice/java/test/src/main/java/test/IceSSL/configuration" env={'CLASSPATH': '/Users/runner/work/ice/ice/java/lib/test.jar'})
(/Users/runner/hostedtoolcache/Java_Oracle_jdk/17/arm64/Contents/Home/bin/java -ea -Dtest.class=test.IceSSL.configuration.Client test.TestDriver --Ice.Default.Host=127.0.0.1 --Test.BasePort=14200 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp --Ice.IPv6=0 "/Users/runner/work/ice/ice/java/test/src/main/java/test/IceSSL/configuration" env={'CLASSPATH': '/Users/runner/work/ice/ice/java/lib/test.jar'})
client validates server certificate using trust store... ok
client validates server certificate using default trust store... com.zeroc.Ice.ConnectTimeoutException: Connect timed out.
java.lang.RuntimeException: com.zeroc.Ice.ConnectTimeoutException: Connect timed out.
	at test.IceSSL.configuration.PlatformTests.clientValidatesServerUsingDefaultTrustStore(PlatformTests.java:158)
	at test.IceSSL.configuration.PlatformTests.allTests(PlatformTests.java:386)
	at test.IceSSL.configuration.Client.run(Client.java:21)
	at test.TestDriver.main(TestDriver.java:14)
Caused by: com.zeroc.Ice.ConnectTimeoutException: Connect timed out.
	at com.zeroc.IceInternal.OutgoingAsync.waitForResponseOrUserEx(OutgoingAsync.java:108)
	at com.zeroc.IceInternal.OutgoingAsync.waitForResponse(OutgoingAsync.java:91)
	at com.zeroc.Ice._ObjectPrxI.ice_ping(_ObjectPrxI.java:61)
	at com.zeroc.Ice._ObjectPrxI.ice_ping(_ObjectPrxI.java:57)
	at test.IceSSL.configuration.PlatformTests.clientValidatesServerUsingDefaultTrustStore(PlatformTests.java:153)
	... 3 more

test in IceSSL/configuration failed:
```

See https://github.com/zeroc-ice/ice/actions/runs/10479215969/job/29058747485?pr=2652

**Comment by externl** [comment]
Sounds like the certs probably expired
