### ISSUE TITLE
js/Ice/operations failure:  Ice.MarshalException: Attempting to unmarshal past the end of the buffer.

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#2696]
```
*** [219/265] Running js/Ice/operations tests ***
[ running client/server test - 08/29/24 20:18:46 ]
- Config: tcp,x64
(D:\a\ice\ice\cpp\test\Ice\echo\msbuild\x64\Release\server.exe --Ice.Default.Host=127.0.0.1 --Test.BasePort=14000 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp --Ice.IPv6=0 --Ice.PrintStackTraces=1 --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 --Ice.MessageSizeMax=8192 env={'PATH': 'D:\\a\\ice\\ice\\cpp\\test\\Common\\msbuild\\x64\\Release;D:\\a\\ice\\ice\\cpp\\bin\\x64\\Release'})
(node D:\a\ice\ice\js\test\Common/run.js file://D:\a\ice\ice\js\test\Ice/operations\Server.js Server --Ice.Default.Host=127.0.0.1 --Test.BasePort=14000 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp --Ice.IPv6=0 --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1)
(node D:\a\ice\ice\js\test\Common/run.js file://D:\a\ice\ice\js\test\Ice/operations\Client.js Client --Ice.Default.Host=127.0.0.1 --Test.BasePort=14000 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp --Ice.IPv6=0)
testing twoway operations... ok
testing oneway operations... ok
testing batch oneway operations... Ice.MarshalException: Attempting to unmarshal past the end of the buffer.
    at InputStream.readInt (file:///D:/a/ice/ice/js/node_modules/ice/src/Ice/InputStream.js:1387:19)
    at helper.read (file:///D:/a/ice/ice/js/node_modules/ice/src/Ice/StreamHelpers.js:19:25)
    at readParam (file:///D:/a/ice/ice/js/node_modules/ice/src/Ice/Operation.js:174:36)
    at unmarshalParams (file:///D:/a/ice/ice/js/node_modules/ice/src/Ice/Operation.js:191:9)
    at unmarshalFn (file:///D:/a/ice/ice/js/node_modules/ice/src/Ice/Operation.js:470:17)
    at ObjectPrx._completed (file:///D:/a/ice/ice/js/node_modules/ice/src/Ice/ObjectPrxExtensions.js:439:23)
    at file:///D:/a/ice/ice/js/node_modules/ice/src/Ice/ObjectPrxExtensions.js:407:14
    at OutgoingAsync.markFinished (file:///D:/a/ice/ice/js/node_modules/ice/src/Ice/AsyncResult.js:64:13)
    at OutgoingAsync.completed (file:///D:/a/ice/ice/js/node_modules/ice/src/Ice/OutgoingAsync.js:499:18)
    at ConnectionI.upcall (file:///D:/a/ice/ice/js/node_modules/ice/src/Ice/ConnectionI.js:641:31)
```

from https://github.com/zeroc-ice/ice/actions/runs/10621325791/job/29443072480 (release on windows-2022 for PR #2684)

**Comment by pepone** [comment]
Can not reproduce locally, with node 22

Seems the image uses Node 18, I will check with this next.

**Comment by pepone** [comment]
cannot reproduce, let's reopen if it happens again.
