### ISSUE TITLE
IceBridge test failure (debug macos)

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#2702]
From CI - unable to reproduce it.

https://github.com/zeroc-ice/ice/actions/runs/10634057238/job/29480536823?pr=2697

```
*** [231/335] Running cpp/IceBridge/simple tests ***
[ running client/server test - 08/30/24 14:34:46 ]
- Config: ssl,mx
starting IceBridge... (/Users/runner/work/ice/ice/cpp/bin/icebridge --Ice.Default.Host=127.0.0.1 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --Ice.Admin.Endpoints="tcp -p 14102" --Ice.Admin.InstanceName=IceBridge --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --IceSSL.*** --IceSSL.DefaultDir=/Users/runner/work/ice/ice/certs --IceSSL.CAs=cacert.pem --IceSSL.CertFile=server.p12 --IceSSL.KeychainPassword=password --IceSSL.Keychain=server.keychain --Ice.PrintStackTraces=1 --Ice.PrintAdapterReady=1 --Ice.Warn.Dispatch=0 --IceBridge.Target.Endpoints="default -p 14100:udp -p 14100" --IceBridge.Source.Endpoints="default -p 14101:udp -p 14101")
ok
(/Users/runner/work/ice/ice/cpp/test/IceBridge/simple/build/macosx/shared/server --Ice.Default.Host=127.0.0.1 --Test.BasePort=14100 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --Ice.Admin.Endpoints="tcp -h 127.0.0.1" --Ice.Admin.InstanceName=Server --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --IceSSL.*** --IceSSL.DefaultDir=/Users/runner/work/ice/ice/certs --IceSSL.CAs=cacert.pem --IceSSL.CertFile=server.p12 --IceSSL.KeychainPassword=password --IceSSL.Keychain=server.keychain --Ice.PrintStackTraces=1 --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1)
(/Users/runner/work/ice/ice/cpp/test/IceBridge/simple/build/macosx/shared/client --Ice.Default.Host=127.0.0.1 --Test.BasePort=14100 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --Ice.Admin.Endpoints="tcp -h 127.0.0.1" --Ice.Admin.InstanceName=Client --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --IceSSL.*** --IceSSL.DefaultDir=/Users/runner/work/ice/ice/certs --IceSSL.CAs=cacert.pem --IceSSL.CertFile=client.p12 --IceSSL.KeychainPassword=password --IceSSL.Keychain=client.keychain --Ice.PrintStackTraces=1)
testing connection to bridge... ok
testing datagrams... ok
testing connection close... ok
testing multiple connections... ok
testing ordering... ok
testing bi-dir callbacks... ok
testing datagram bi-dir callbacks... ok
testing router... ok
testing server shutdown... ok
testing bridge shutdown... ok
libc++abi: terminating due to uncaught exception of type std::__1::bad_function_call: std::exception

test in IceBridge/simple failed:
Traceback (most recent call last):
  File "/Users/runner/work/ice/ice/scripts/Util.py", line 1508, in stop
    process.waitSuccess(exitstatus=exitstatus, timeout=30)
  File "/Users/runner/work/ice/ice/scripts/Expect.py", line 691, in waitSuccess
    self.testExitStatus(exitstatus)
  File "/Users/runner/work/ice/ice/scripts/Expect.py", line 735, in testExitStatus
    test(self.exitstatus, exitstatus)
  File "/Users/runner/work/ice/ice/scripts/Expect.py", line 717, in test
    raise RuntimeError(
RuntimeError: unexpected exit status: expected: 0, got -6
```

**Comment by externl** [comment]
I was able to reproduce. See attached core dump
