### ISSUE TITLE
 Ice/adapterDeactivation test failure in Java

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#2711]
```
2024-09-03T16:58:35.9319568Z testing whether server is gone... ok
2024-09-03T16:58:35.9320293Z testing server idle time...!!!!!!!!!!! unhandled exception in thread Thread-12: java.lang.RuntimeException
2024-09-03T16:58:35.9321179Z java.lang.RuntimeException
2024-09-03T16:58:35.9321659Z 	at test.Ice.adapterDeactivation.AllTests.test(AllTests.java:13)
2024-09-03T16:58:35.9322325Z 	at test.Ice.adapterDeactivation.AllTests.lambda$allTests$1(AllTests.java:236)
2024-09-03T16:58:35.9322886Z 	at java.base/java.lang.Thread.run(Thread.java:842)
2024-09-03T16:58:35.9323173Z 
2024-09-03T16:58:35.9323306Z test in Ice/adapterDeactivation failed:
2024-09-03T16:58:35.9323663Z Traceback (most recent call last):
2024-09-03T16:58:35.9324088Z   File "D:\a\ice\ice\scripts\Util.py", line 2015, in run
2024-09-03T16:58:35.9324500Z     self.runWithDriver(current)
2024-09-03T16:58:35.9324941Z   File "D:\a\ice\ice\scripts\Util.py", line 2046, in runWithDriver
2024-09-03T16:58:35.9325451Z     current.driver.runClientServerTestCase(current)
2024-09-03T16:58:35.9326045Z   File "D:\a\ice\ice\scripts\LocalDriver.py", line 680, in runClientServerTestCase
2024-09-03T16:58:35.9326622Z     self.runner.runClientSide(client, current, host)
2024-09-03T16:58:35.9327179Z   File "D:\a\ice\ice\scripts\LocalDriver.py", line 207, in runClientSide
2024-09-03T16:58:35.9327664Z     testcase._runClientSide(current, host)
2024-09-03T16:58:35.9328126Z   File "D:\a\ice\ice\scripts\Util.py", line 1992, in _runClientSide
2024-09-03T16:58:35.9328561Z     self.runClientSide(current)
2024-09-03T16:58:35.9328982Z   File "D:\a\ice\ice\scripts\Util.py", line 1878, in runClientSide
2024-09-03T16:58:35.9329409Z     self._runClient(current, client)
2024-09-03T16:58:35.9329824Z   File "D:\a\ice\ice\scripts\Util.py", line 2004, in _runClient
2024-09-03T16:58:35.9330228Z     client.run(current)
2024-09-03T16:58:35.9330621Z   File "D:\a\ice\ice\scripts\Util.py", line 1408, in run
2024-09-03T16:58:35.9331144Z     process.waitSuccess(exitstatus=exitstatus, timeout=30)
2024-09-03T16:58:35.9332574Z   File "D:\a\ice\ice\scripts\Expect.py", line 691, in waitSuccess
2024-09-03T16:58:35.9333086Z     self.testExitStatus(exitstatus)
2024-09-03T16:58:35.9333612Z   File "D:\a\ice\ice\scripts\Expect.py", line 735, in testExitStatus
2024-09-03T16:58:35.9334132Z     test(self.exitstatus, exitstatus)
2024-09-03T16:58:35.9334578Z   File "D:\a\ice\ice\scripts\Expect.py", line 717, in test
2024-09-03T16:58:35.9343165Z     raise RuntimeError(
2024-09-03T16:58:35.9343747Z RuntimeError: unexpected exit status: expected: 0, got 1
```
From this PR:

https://github.com/zeroc-ice/ice/actions/runs/10686574506/job/29622123030?pr=2706

**Comment by bernardnormier** [comment]
The stack trace is no longer current. Please post a new stack trace / PR log when it reoccurs.

**Comment by bernardnormier** [comment]
Failed again (Java/Windows):
https://github.com/zeroc-ice/ice/actions/runs/11223758308/job/31199076087

```
[ running client/server test - 10/07/24 21:43:06 ]
- Config: ws,compress,ipv6,serialize,mx,x64
(C:\hostedtoolcache\windows\Java_Oracle_jdk\17\x64\bin\java -ea -Dtest.class=test.Ice.adapterDeactivation.Server test.TestDriver --Ice.Default.Host=::1 --Test.BasePort=14200 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ws --Ice.Override.Compress=1 --Ice.ThreadPool.Server.Serialize=1 --Ice.IPv6=1 --Ice.PreferIPv6Address=1 --Ice.Admin.Endpoints="tcp -h \"::1\"" --Ice.Admin.InstanceName=Server --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 env={'CLASSPATH': 'D:\\a\\ice\\ice\\java\\lib\\test.jar'})
(C:\hostedtoolcache\windows\Java_Oracle_jdk\17\x64\bin\java -ea -Dtest.class=test.Ice.adapterDeactivation.Client test.TestDriver --Ice.Default.Host=::1 --Test.BasePort=14200 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ws --Ice.Override.Compress=1 --Ice.ThreadPool.Server.Serialize=1 --Ice.IPv6=1 --Ice.PreferIPv6Address=1 --Ice.Admin.Endpoints="tcp -h \"::1\"" --Ice.Admin.InstanceName=Client --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none env={'CLASSPATH': 'D:\\a\\ice\\ice\\java\\lib\\test.jar'})
testing stringToProxy... ok
testing checked cast... ok
creating/destroying/recreating object adapter... ok
creating/activating/deactivating object adapter in one operation... ok
testing connection closure... ok
testing object adapter published endpoints... ok
testing object adapter published host... ok
testing object adapter with bi-dir connection... ok
testing object adapter with router... ok
testing object adapter creation with port in use... ok
deactivating object adapter in the server... ok
testing whether server is gone... ok
testing server idle time...!!!!!!! unhandled exception in thread Thread-12: java.lang.RuntimeException
java.lang.RuntimeException
	at test.Ice.adapterDeactivation.AllTests.test(AllTests.java:16)
	at test.Ice.adapterDeactivation.AllTests.lambda$allTests$1(AllTests.java:388)
	at java.base/java.lang.Thread.run(Thread.java:842)

test in Ice/adapterDeactivation failed:
Traceback (most recent call last):
```

https://github.com/zeroc-ice/ice/blob/9ab4adbe63adacacc0ed523e7ba0e6c2108cbec4/java/test/src/main/java/test/Ice/adapterDeactivation/AllTests.java#L388

**Comment by bernardnormier** [comment]
It also fails with colloc:
https://github.com/zeroc-ice/ice/actions/runs/11405736736/job/31737871184?pr=2932

```
[ running collocated test - 10/18/24 15:33:00 ]
- Config: x64
(C:\hostedtoolcache\windows\Java_Oracle_jdk\17\x64\bin\java -ea -Dtest.class=test.Ice.adapterDeactivation.Collocated test.TestDriver --Ice.Default.Host=127.0.0.1 --Test.BasePort=14100 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp --Ice.IPv6=0 env={'CLASSPATH': 'D:\\a\\ice\\ice\\java\\lib\\test.jar'})
testing stringToProxy... ok
testing checked cast... ok
creating/destroying/recreating object adapter... ok
creating/activating/deactivating object adapter in one operation... ok
testing connection closure... ok
testing object adapter published endpoints... ok
testing object adapter published host... ok
testing object adapter with router... ok
testing object adapter creation with port in use... ok
deactivating object adapter in the server... ok
testing whether server is gone... ok
testing server idle time...!!!!!!! unhandled exception in thread Thread-12: java.lang.RuntimeException
java.lang.RuntimeException
	at test.Ice.adapterDeactivation.AllTests.test(AllTests.java:16)
	at test.Ice.adapterDeactivation.AllTests.lambda$allTests$1(AllTests.java:417)
	at java.base/java.lang.Thread.run(Thread.java:833)


```

**Comment by bernardnormier** [comment]
It failed again (Windows, release):
https://github.com/zeroc-ice/ice/actions/runs/11694580839/job/32568469602

```
*** [157/271] Running java/Ice/adapterDeactivation tests ***
[ running client/server test - 11/06/24 00:59:23 ]
- Config: ssl,x64
(C:\hostedtoolcache\windows\Java_Oracle_jdk\17\x64\bin\java -ea -Dtest.class=test.Ice.adapterDeactivation.Server test.TestDriver --Ice.Default.Host=127.0.0.1 --Test.BasePort=14100 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --IceSSL.*** --IceSSL.DefaultDir=D:\a\ice\ice\certs --IceSSL.Keystore=server.jks --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 env={'CLASSPATH': 'D:\\a\\ice\\ice\\java\\lib\\test.jar'})
(C:\hostedtoolcache\windows\Java_Oracle_jdk\17\x64\bin\java -ea -Dtest.class=test.Ice.adapterDeactivation.Client test.TestDriver --Ice.Default.Host=127.0.0.1 --Test.BasePort=14100 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --IceSSL.*** --IceSSL.DefaultDir=D:\a\ice\ice\certs --IceSSL.Keystore=client.jks env={'CLASSPATH': 'D:\\a\\ice\\ice\\java\\lib\\test.jar'})
testing stringToProxy... ok
testing checked cast... ok
creating/destroying/recreating object adapter... ok
creating/activating/deactivating object adapter in one operation... ok
testing connection closure... ok
testing object adapter published endpoints... ok
testing object adapter published host... ok
testing object adapter with bi-dir connection... ok
testing object adapter with router... ok
testing object adapter creation with port in use... ok
deactivating object adapter in the server... ok
testing whether server is gone... ok
testing server idle time...!!!!!!! unhandled exception in thread Thread-12: java.lang.RuntimeException
java.lang.RuntimeException
	at test.Ice.adapterDeactivation.AllTests.test(AllTests.java:18)
	at test.Ice.adapterDeactivation.AllTests.lambda$allTests$1(AllTests.java:419)
	at java.base/java.lang.Thread.run(Thread.java:833)

test in Ice/adapterDeactivation failed:

```
