### ISSUE TITLE
max concurrent dispatches test failure

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#2714]
```
'D:\\a\\ice\\ice\\cpp\\test\\Common\\msbuild\\x64\\Debug;D:\\a\\ice\\ice\\cpp\\bin\\x64\\Debug'})
testing max dispatches max = 100... failed!
D:\a\ice\ice\cpp\test\Ice\maxDispatches\AllTests.cpp:30: assertion `maxConcurrentDispatches == maxCount' failed
abort() has been called
-! 09/04/24 10:04:26801 D:/a/ice/ice/cpp/test/Ice/maxDispatches/msbuild/server/x64/Debug/server.exe: warning: connection exception:
   D:\a\ice\ice\cpp\src\Ice\StreamSocket.cpp:442 ::Ice::ConnectionLostException connection lost: The specified network name is no longer available.
   stack trace:
     0 Ice::Exception::Exception at D:\a\ice\ice\cpp\src\Ice\Exception.cpp:514
     1 Ice::LocalException::LocalException at D:\a\ice\ice\cpp\include\Ice\LocalException.h:25
     2 Ice::SyscallException::SyscallException at D:\a\ice\ice\cpp\src\Ice\LocalExceptions.cpp:218
     3 Ice::SocketException::SocketException
     4 Ice::ConnectionLostException::ConnectionLostException at D:\a\ice\ice\cpp\src\Ice\LocalExceptions.cpp:314
     5 IceInternal::StreamSocket::finishRead at D:\a\ice\ice\cpp\src\Ice\StreamSocket.cpp:442
     6 IceInternal::TcpTransceiver::finishRead at D:\a\ice\ice\cpp\src\Ice\TcpTransceiver.cpp:80
     7 Ice::SSL::Schannel::TransceiverI::finishRead at D:\a\ice\ice\cpp\src\Ice\SSL\SchannelTransceiverI.cpp:868
     8 IceInternal::IdleTimeoutTransceiverDecorator::finishRead at D:\a\ice\ice\cpp\src\Ice\IdleTimeoutTransceiverDecorator.cpp:141
     9 Ice::ConnectionI::finishAsync at D:\a\ice\ice\cpp\src\Ice\ConnectionI.cpp:1096
    10 IceInternal::ThreadPool::startMessage at D:\a\ice\ice\cpp\src\Ice\ThreadPool.cpp:868
    11 IceInternal::ThreadPoolCurrent::startMessage at D:\a\ice\ice\cpp\src\Ice\ThreadPool.h:149
    12 IceInternal::ThreadPoolMessage<Ice::ConnectionI>::IOScope::IOScope at D:\a\ice\ice\cpp\src\Ice\ThreadPool.h:255
    13 Ice::ConnectionI::message at D:\a\ice\ice\cpp\src\Ice\ConnectionI.cpp:1140
    14 IceInternal::ThreadPool::run at D:\a\ice\ice\cpp\src\Ice\ThreadPool.cpp:746
    15 IceInternal::ThreadPool::EventHandlerThread::run at D:\a\ice\ice\cpp\src\Ice\ThreadPool.cpp:1103
    16 std::invoke<void (__cdecl IceInternal::ThreadPool::EventHandlerThread::*)(void),IceInternal::ThreadPool::EventHandlerThread *> at C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.41.34120\include\type_traits:1720
    17 std::thread::_Invoke<std::tuple<void (__cdecl IceInternal::ThreadPool::EventHandlerThread::*)(void),IceInternal::ThreadPool::EventHandlerThread *>,0,1> at C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.41.34120\include\thread:61
    18 00007ffdb9f03010
    19 00007ffde8a84cb0
    20 00007ffdeab5eceb
```

See https://github.com/zeroc-ice/ice/actions/runs/10699083537/job/29659846491

**Comment by pepone** [comment]
Seems it is failing in C# too:

```
2024-09-04T19:17:11.7575740Z testing max dispatches max = 100... failed:
2024-09-04T19:17:11.7578130Z    at Test.TestHelper.fail(String message, String detailMessage) in /Users/runner/work/ice/ice/csharp/test/TestCommon/TestHelper.cs:line 183
2024-09-04T19:17:11.7581430Z    at Test.TestHelper.TestTraceListener.Fail(String message, String detailMessage) in /Users/runner/work/ice/ice/csharp/test/TestCommon/TestHelper.cs:line 35
2024-09-04T19:17:11.7584020Z    at System.Diagnostics.TraceInternal.Fail(String message, String detailMessage)
2024-09-04T19:17:11.7585730Z    at System.Diagnostics.Debug.Fail(String message, String detailMessage)
2024-09-04T19:17:11.7587630Z    at Test.AllTests.test(Boolean b) in /Users/runner/work/ice/ice/csharp/test/TestCommon/TestHelper.cs:line 217
2024-09-04T19:17:11.7590820Z    at Ice.maxDispatches.AllTests.testMaxDispatches(TestIntfPrx p, Int32 maxCount, TextWriter output) in /Users/runner/work/ice/ice/csharp/test/Ice/maxDispatches/AllTests.cs:line 49
2024-09-04T19:17:11.7595270Z    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
```
