### ISSUE TITLE
IceGridGUI can't connect to IceGrid via Glacier2 (main)

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#2761]
Such a connection attempt hangs forever when using the "IceGrid/admin" test registry + router.

**Comment by pepone** [comment]
From my tests what I see is that the registration of the observers timeouts in 

https://github.com/zeroc-ice/ice/blob/4d832c8a485d509ecaf4ca7c0dceea9642adad8f/java/src/IceGridGUI/src/main/java/com/zeroc/IceGridGUI/SessionKeeper.java#L4675

After this calls fails, the handling of TimeoutException calls calling `_communicator.destroy`

```
"AWT-EventQueue-0" #22 [25107] prio=6 os_prio=31 cpu=880.27ms elapsed=369.69s tid=0x000000011c926200 nid=25107 in Object.wait()  [0x000000017446e000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait0(java.base@21.0.2/Native Method)
	- waiting on <no object reference available>
	at java.lang.Object.wait(java.base@21.0.2/Object.java:366)
	at java.lang.Object.wait(java.base@21.0.2/Object.java:339)
	at com.zeroc.Ice.ConnectionI.waitUntilFinished(ConnectionI.java:241)
	- locked <0x000000061f727248> (a com.zeroc.Ice.ConnectionI)
	at com.zeroc.Ice.OutgoingConnectionFactory.waitUntilFinished(OutgoingConnectionFactory.java:88)
	at com.zeroc.Ice.Instance.destroy(Instance.java:1168)
	at com.zeroc.Ice.Communicator.destroy(Communicator.java:41)
	at com.zeroc.IceGridGUI.Coordinator.destroyCommunicator(Coordinator.java:3074)
	at com.zeroc.IceGridGUI.Coordinator.setConnected(Coordinator.java:3216)
	at com.zeroc.IceGridGUI.SessionKeeper$Session.close(SessionKeeper.java:264)
	at com.zeroc.IceGridGUI.SessionKeeper$Session.logout(SessionKeeper.java:174)
	at com.zeroc.IceGridGUI.SessionKeeper.logout(SessionKeeper.java:4973)
	at com.zeroc.IceGridGUI.SessionKeeper.lambda$loginSuccess$1(SessionKeeper.java:4696)
	at com.zeroc.IceGridGUI.SessionKeeper$$Lambda/0x00000070012a3a68.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(java.desktop@21.0.2/InvocationEvent.java:308)
```

**Comment by pepone** [comment]
Wonder if this is related to #2595 and the workaround added here:

https://github.com/zeroc-ice/ice/blob/4d832c8a485d509ecaf4ca7c0dceea9642adad8f/java/src/Ice/src/main/java/com/zeroc/Ice/ConnectionI.java#L2254

If my suspicious is correct the upCall for this requests is never decremented, and this will cause the connection waitUntilFinished call to wait for ever.

**Comment by pepone** [comment]
The registration of the observers was failing due to #2826, and the communicator destroy hang because #2595 was not yet fixed.

Both issues are now fixed.
