### ISSUE TITLE
Glacier2/callback NullPointerException with Java11

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice#287]
I'm seeing this on macOS Mojave when running the java/Glacier2 callback client with Java11:
```
MacBookPro:~/Devel/GitHub/ice-demos/java/Glacier2/callback$ java -jar build/libs/client.jar
This demo accepts any user-id / password combination.
user id: test
password: test
!! 11/8/18 18:18:37:581 Client: error: Ice.ThreadPool.Client-0: exception in `Ice.ThreadPool.Client':
   java.lang.NullPointerException
        at java.base/sun.security.ssl.OutputRecord.changeWriteCiphers(OutputRecord.java:173)
        at java.base/sun.security.ssl.ChangeCipherSpec$T10ChangeCipherSpecProducer.produce(ChangeCipherSpec.java:112)
        at java.base/sun.security.ssl.Finished$T12FinishedProducer.onProduceFinished(Finished.java:392)
        at java.base/sun.security.ssl.Finished$T12FinishedProducer.produce(Finished.java:376)
        at java.base/sun.security.ssl.SSLHandshake.produce(SSLHandshake.java:436)
        at java.base/sun.security.ssl.ServerHelloDone$ServerHelloDoneConsumer.consume(ServerHelloDone.java:173)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1065)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1052)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:999)
        at com.zeroc.IceSSL.TransceiverI.handshakeNonBlocking(TransceiverI.java:343)
        at com.zeroc.IceSSL.TransceiverI.initialize(TransceiverI.java:61)
        at com.zeroc.Ice.ConnectionI.initialize(ConnectionI.java:2111)
        at com.zeroc.Ice.ConnectionI.message(ConnectionI.java:1093)
        at com.zeroc.IceInternal.ThreadPool.run(ThreadPool.java:417)
        at com.zeroc.IceInternal.ThreadPool.access$500(ThreadPool.java:12)
        at com.zeroc.IceInternal.ThreadPool$EventHandlerThread.run(ThreadPool.java:786)
        at java.base/java.lang.Thread.run(Thread.java:834)
   
   event handler: local address = <not available>
   remote address = 127.0.0.1:4064
```

**Comment by bernardnormier** [comment]
This apparently corresponds to:
http://hg.openjdk.java.net/jdk/jdk11/file/1ddf9a99e4ad/src/java.base/share/classes/sun/security/ssl/OutputRecord.java#l173

**Comment by bentoi** [comment]
I've submitted a bug on https://bugs.java.com (internal ID: 9058040)

This is triggered because we have an old property settings that was added to workaround a SecureTransport bug:
```
# Required for a Java 1.8 client to talk to a C++ server on OSX
IceSSL.ProtocolVersionMax=tls1_1
```

It works without this so I'll remove it.

**Comment by bentoi** [comment]
See https://github.com/zeroc-ice/ice-demos/commit/52cdb2f0035dbf4841327d9e2bdf0898b8944226
