### ISSUE TITLE
java/Ice/maxConnections failure (debug Ubuntu)

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#2881]
From
https://github.com/zeroc-ice/ice/actions/runs/11261761158/job/31315911872?pr=2879

```
*** [229/305] Running java/Ice/maxConnections tests ***
[ running client/server test - 10/09/24 19:59:27 ]
- Config: ssl
(/opt/hostedtoolcache/Java_Oracle_jdk/17/x64/bin/java -ea -Djdk.net.URLClassPath.disableClassPathURLCheck=true -Dtest.class=test.Ice.maxConnections.Server test.TestDriver --Ice.Default.Host=127.0.0.1 --Test.BasePort=14200 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --IceSSL.*** --IceSSL.DefaultDir=/home/runner/work/ice/ice/certs --IceSSL.Keystore=server.jks --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 --Ice.Trace.Network=2 --Ice.LogFile=/home/runner/work/ice/ice/java/test/src/main/java/test/Ice/maxConnections/server-100924-1959.log env={'CLASSPATH': '/home/runner/work/ice/ice/java/lib/test.jar'})
(/opt/hostedtoolcache/Java_Oracle_jdk/17/x64/bin/java -ea -Djdk.net.URLClassPath.disableClassPathURLCheck=true -Dtest.class=test.Ice.maxConnections.Client test.TestDriver --Ice.Default.Host=127.0.0.1 --Test.BasePort=14200 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --IceSSL.*** --IceSSL.DefaultDir=/home/runner/work/ice/ice/certs --IceSSL.Keystore=client.jks --Ice.Trace.Network=2 --Ice.LogFile=/home/runner/work/ice/ice/java/test/src/main/java/test/Ice/maxConnections/client-100924-1959.log env={'CLASSPATH': '/home/runner/work/ice/ice/java/lib/test.jar'})
testing the creation of 100 connections... ok
testing the creation of 10 connections with connection lost at 11... ok
testing the creation of 10 connections with connection lost at 11 then recovery... ok
[ running client/server test - 10/09/24 19:59:31 ]
- Config: ws,ipv6,serialize,mx
(/opt/hostedtoolcache/Java_Oracle_jdk/17/x64/bin/java -ea -Djdk.net.URLClassPath.disableClassPathURLCheck=true -Dtest.class=test.Ice.maxConnections.Server test.TestDriver --Ice.Default.Host=::1 --Test.BasePort=14200 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ws --Ice.ThreadPool.Server.Serialize=1 --Ice.IPv6=1 --Ice.PreferIPv6Address=1 --Ice.Admin.Endpoints="tcp -h \"::1\"" --Ice.Admin.InstanceName=Server --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 --Ice.Trace.Network=2 --Ice.LogFile=/home/runner/work/ice/ice/java/test/src/main/java/test/Ice/maxConnections/server-100924-1959.log env={'CLASSPATH': '/home/runner/work/ice/ice/java/lib/test.jar'})
(/opt/hostedtoolcache/Java_Oracle_jdk/17/x64/bin/java -ea -Djdk.net.URLClassPath.disableClassPathURLCheck=true -Dtest.class=test.Ice.maxConnections.Client test.TestDriver --Ice.Default.Host=::1 --Test.BasePort=14200 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ws --Ice.ThreadPool.Server.Serialize=1 --Ice.IPv6=1 --Ice.PreferIPv6Address=1 --Ice.Admin.Endpoints="tcp -h \"::1\"" --Ice.Admin.InstanceName=Client --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --Ice.Trace.Network=2 --Ice.LogFile=/home/runner/work/ice/ice/java/test/src/main/java/test/Ice/maxConnections/client-100924-1959.log env={'CLASSPATH': '/home/runner/work/ice/ice/java/lib/test.jar'})
testing the creation of 100 connections... ok
testing the creation of 10 connections with connection lost at 11... ok
testing the creation of 10 connections with connection lost at 11 then recovery... com.zeroc.Ice.ConnectionLostException
	at com.zeroc.Ice.OutgoingAsync.waitForResponseOrUserEx(OutgoingAsync.java:110)
	at com.zeroc.Ice.OutgoingAsync.waitForResponse(OutgoingAsync.java:93)
	at com.zeroc.Ice._ObjectPrxI.ice_ping(_ObjectPrxI.java:59)
	at com.zeroc.Ice._ObjectPrxFactoryMethods.ice_ping(_ObjectPrxFactoryMethods.java:11)
	at com.zeroc.Ice._ObjectPrxI.ice_ping(_ObjectPrxI.java:55)
	at com.zeroc.Ice._ObjectPrxFactoryMethods.ice_ping(_ObjectPrxFactoryMethods.java:11)
	at test.Ice.maxConnections.AllTests.testCreateConnectionsWithMaxAndRecovery(AllTests.java:111)
	at test.Ice.maxConnections.AllTests.allTests(AllTests.java:21)
	at test.Ice.maxConnections.Client.run(Client.java:12)
	at test.TestDriver.main(TestDriver.java:26)
Caused by: java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
	at com.zeroc.Ice.StreamSocket.read(StreamSocket.java:144)
	at com.zeroc.Ice.StreamSocket.read(StreamSocket.java:116)
	at com.zeroc.Ice.TcpTransceiver.read(TcpTransceiver.java:49)
	at com.zeroc.Ice.WSTransceiver.read(WSTransceiver.java:333)
	at com.zeroc.Ice.IdleTimeoutTransceiverDecorator.read(IdleTimeoutTransceiverDecorator.java:82)
	at com.zeroc.Ice.ConnectionI.read(ConnectionI.java:2450)
	at com.zeroc.Ice.ConnectionI.message(ConnectionI.java:564)
	at com.zeroc.Ice.ThreadPool.run(ThreadPool.java:352)
	at com.zeroc.Ice.ThreadPool$EventHandlerThread.run(ThreadPool.java:662)
	at java.base/java.lang.Thread.run(Thread.java:842)
saved /home/runner/work/ice/ice/java/test/src/main/java/test/Ice/maxConnections/client-100924-1959.log
saved /home/runner/work/ice/ice/java/test/src/main/java/test/Ice/maxConnections/server-100924-1959.log

```

**Comment by bernardnormier** [comment]
This still is still failing:
https://github.com/zeroc-ice/ice/actions/runs/11299281545/job/31429923258

```
- Config: ws,ipv6,serialize,mx
(/opt/hostedtoolcache/Java_Oracle_jdk/17/x64/bin/java -ea -Djdk.net.URLClassPath.disableClassPathURLCheck=true -Dtest.class=test.Ice.maxConnections.Server test.TestDriver --Ice.Default.Host=::1 --Test.BasePort=14000 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ws --Ice.ThreadPool.Server.Serialize=1 --Ice.IPv6=1 --Ice.PreferIPv6Address=1 --Ice.Admin.Endpoints="tcp -h \"::1\"" --Ice.Admin.InstanceName=Server --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 --Ice.Trace.Network=2 --Ice.LogFile=/home/runner/work/ice/ice/java/test/src/main/java/test/Ice/maxConnections/server-101124-2137.log env={'CLASSPATH': '/home/runner/work/ice/ice/java/lib/test.jar'})
(/opt/hostedtoolcache/Java_Oracle_jdk/17/x64/bin/java -ea -Djdk.net.URLClassPath.disableClassPathURLCheck=true -Dtest.class=test.Ice.maxConnections.Client test.TestDriver --Ice.Default.Host=::1 --Test.BasePort=14000 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ws --Ice.ThreadPool.Server.Serialize=1 --Ice.IPv6=1 --Ice.PreferIPv6Address=1 --Ice.Admin.Endpoints="tcp -h \"::1\"" --Ice.Admin.InstanceName=Client --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --Ice.Trace.Network=2 --Ice.LogFile=/home/runner/work/ice/ice/java/test/src/main/java/test/Ice/maxConnections/client-101124-2137.log env={'CLASSPATH': '/home/runner/work/ice/ice/java/lib/test.jar'})
testing the creation of 100 connections... ok
testing the creation of 10 connections with connection lost at 11... ok
testing the creation of 10 connections with connection lost at 11 then recovery... com.zeroc.Ice.ConnectionLostException
	at com.zeroc.Ice.OutgoingAsync.waitForResponseOrUserEx(OutgoingAsync.java:110)
	at com.zeroc.Ice.OutgoingAsync.waitForResponse(OutgoingAsync.java:93)
	at com.zeroc.Ice._ObjectPrxI.ice_ping(_ObjectPrxI.java:59)
	at com.zeroc.Ice._ObjectPrxFactoryMethods.ice_ping(_ObjectPrxFactoryMethods.java:11)
	at com.zeroc.Ice._ObjectPrxI.ice_ping(_ObjectPrxI.java:55)
	at com.zeroc.Ice._ObjectPrxFactoryMethods.ice_ping(_ObjectPrxFactoryMethods.java:11)
	at test.Ice.maxConnections.AllTests.testCreateConnectionsWithMaxAndRecovery(AllTests.java:135)
	at test.Ice.maxConnections.AllTests.allTests(AllTests.java:32)
	at test.Ice.maxConnections.Client.run(Client.java:15)
	at test.TestDriver.main(TestDriver.java:26)
saved /home/runner/work/ice/ice/java/test/src/main/java/test/Ice/maxConnections/client-101124-2137.log
saved /home/runner/work/ice/ice/java/test/src/main/java/test/Ice/maxConnections/server-101124-2137.log
```
