### ISSUE TITLE
js Ice/hold failure (macos)

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#2885]
From https://github.com/zeroc-ice/ice/actions/runs/11280236298/job/31372758574?pr=2883

```
*** [54/334] Running js/Ice/hold tests ***
[ running client/server test - 10/10/24 19:10:11 ]
- Config: tcp
(/Users/runner/work/ice/ice/cpp/test/Ice/hold/build/macosx/shared/server --Ice.Default.Host=127.0.0.1 --Test.BasePort=14200 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1)
(node /Users/runner/work/ice/ice/js/test/Common/run.js file:///Users/runner/work/ice/ice/js/test/Ice/hold/Client.js Client --Ice.Default.Host=127.0.0.1 --Test.BasePort=14200 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp)
changing state between active and hold rapidly... ok
testing without serialize mode... ok
testing with serialize mode... Error: test failed
    at test (file:///Users/runner/work/ice/ice/js/test/Common/TestHelper.js:133:19)
    at Client.allTests (file:///Users/runner/work/ice/ice/js/test/Ice/hold/Client.js:121:13)
    at async Client.run (file:///Users/runner/work/ice/ice/js/test/Ice/hold/Client.js:193:13)
    at async file:///Users/runner/work/ice/ice/js/test/Common/run.js:28:9

test in Ice/hold failed:

```

It's an interesting failure since there is no "hold" in JS.

**Comment by pepone** [comment]
What is the point of having this test on JavaScript? Here we are testing the C++ server hold state.

**Comment by bernardnormier** [comment]
I agree, this test is pointless. A fix could for this issue could be to remove the JS test.
