### ISSUE TITLE
csharp/Ice/maxConnections failure (Ubuntu)

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#2968]
See https://github.com/zeroc-ice/ice/actions/runs/11497902292/job/32002601618

```
*** [286/311] Running csharp/Ice/maxConnections tests ***
[ running client/server test - 10/24/24 11:51:41 ]
- Config: ssl
(dotnet /home/runner/work/ice/ice/csharp/test/Ice/maxConnections/msbuild/server/net8.0/server.dll --Ice.Default.Host=127.0.0.1 --Test.BasePort=14000 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --IceSSL.*** --IceSSL.DefaultDir=/home/runner/work/ice/ice/certs --IceSSL.CAs=cacert.pem --IceSSL.VerifyPeer=2 --IceSSL.CertFile=server.p12 --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 --Ice.Trace.Network=2 --Ice.LogFile=/home/runner/work/ice/ice/csharp/test/Ice/maxConnections/server-102424-1151.log)
(dotnet /home/runner/work/ice/ice/csharp/test/Ice/maxConnections/msbuild/client/net8.0/client.dll --Ice.Default.Host=127.0.0.1 --Test.BasePort=14000 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --IceSSL.*** --IceSSL.DefaultDir=/home/runner/work/ice/ice/certs --IceSSL.CAs=cacert.pem --IceSSL.VerifyPeer=2 --IceSSL.CertFile=client.p12 --Ice.Trace.Network=2 --Ice.LogFile=/home/runner/work/ice/ice/csharp/test/Ice/maxConnections/client-102424-1151.log)
testing the creation of 100 connections... ok
testing the creation of 10 connections with connection lost at 11... ok
testing the creation of 10 connections with connection lost at 11 then recovery... Ice.ConnectionLostException: Exception of type 'Ice.ConnectionLostException' was thrown.
   at Ice.Internal.OutgoingAsyncBase.invokeException() in /home/runner/work/ice/ice/csharp/src/Ice/Internal/OutgoingAsync.cs:line 100
--- End of stack trace from previous location ---
   at Ice.maxConnections.AllTests.testCreateConnectionsWithMaxAndRecovery(TestIntfPrx p, Int32 max, TextWriter output, Func`1 postCloseDelay) in /home/runner/work/ice/ice/csharp/test/Ice/maxConnections/AllTests.cs:line 139
   at Ice.maxConnections.AllTests.allTests(TestHelper helper) in /home/runner/work/ice/ice/csharp/test/Ice/maxConnections/AllTests.cs:line 28
   at Ice.maxConnections.Client.runAsync(String[] args) in /home/runner/work/ice/ice/csharp/test/Ice/maxConnections/Client.cs:line 16
   at Test.TestDriver.runTestAsync[T](String[] args) in /home/runner/work/ice/ice/csharp/test/TestCommon/TestHelper.cs:line 232
saved /home/runner/work/ice/ice/csharp/test/Ice/maxConnections/client-102424-1151.log
saved /home/runner/work/ice/ice/csharp/test/Ice/maxConnections/server-102424-1151.log
```

**Comment by bernardnormier** [comment]
The logs show a small delay between the "close connection" on the client and the corresponding connection closure on the server:

client
```
-- 10/24/2024 11:51:43:169 client: Network: trying to establish ssl connection to 127.0.0.1:14001
-- 10/24/2024 11:51:43:172 client: Network: failed to establish ssl connection
   
   Ice.ConnectionLostException: Exception of type 'Ice.ConnectionLostException' was thrown.
      at Ice.SSL.TransceiverI.finishAuthenticate() in /home/runner/work/ice/ice/csharp/src/Ice/SSL/TransceiverI.cs:line 435
      at Ice.SSL.TransceiverI.finishWrite(Buffer buf) in /home/runner/work/ice/ice/csharp/src/Ice/SSL/TransceiverI.cs:line 270
      at Ice.Internal.IdleTimeoutTransceiverDecorator.finishWrite(Buffer buf) in /home/runner/work/ice/ice/csharp/src/Ice/Internal/IdleTimeoutTransceiverDecorator.cs:line 60
      at Ice.ConnectionI.finishAsync(Int32 operation) in /home/runner/work/ice/ice/csharp/src/Ice/ConnectionI.cs:line 662
-- 10/24/2024 11:51:43:172 client: Network: connection to endpoint failed and no more endpoints to try
   Ice.ConnectionLostException: Exception of type 'Ice.ConnectionLostException' was thrown.
      at Ice.SSL.TransceiverI.finishAuthenticate() in /home/runner/work/ice/ice/csharp/src/Ice/SSL/TransceiverI.cs:line 435
      at Ice.SSL.TransceiverI.finishWrite(Buffer buf) in /home/runner/work/ice/ice/csharp/src/Ice/SSL/TransceiverI.cs:line 270
      at Ice.Internal.IdleTimeoutTransceiverDecorator.finishWrite(Buffer buf) in /home/runner/work/ice/ice/csharp/src/Ice/Internal/IdleTimeoutTransceiverDecorator.cs:line 60
      at Ice.ConnectionI.finishAsync(Int32 operation) in /home/runner/work/ice/ice/csharp/src/Ice/ConnectionI.cs:line 662
-- 10/24/2024 11:51:43:174 client: Network: closed ssl connection <== must complete on the server-side before next attempt
   local address = 127.0.0.1:56634
   remote address = 127.0.0.1:14001
-- 10/24/2024 11:51:43:174 client: Network: trying to establish ssl connection to 127.0.0.1:14001
-- 10/24/2024 11:51:43:177 client: Network: failed to establish ssl connection
   
   Ice.ConnectionLostException: Exception of type 'Ice.ConnectionLostException' was thrown.
      at Ice.SSL.TransceiverI.finishAuthenticate() in /home/runner/work/ice/ice/csharp/src/Ice/SSL/TransceiverI.cs:line 435
      at Ice.SSL.TransceiverI.finishWrite(Buffer buf) in /home/runner/work/ice/ice/csharp/src/Ice/SSL/TransceiverI.cs:line 270
      at Ice.Internal.IdleTimeoutTransceiverDecorator.finishWrite(Buffer buf) in /home/runner/work/ice/ice/csharp/src/Ice/Internal/IdleTimeoutTransceiverDecorator.cs:line 60
      at Ice.ConnectionI.finishAsync(Int32 operation) in /home/runner/work/ice/ice/csharp/src/Ice/ConnectionI.cs:line 662
-- 10/24/2024 11:51:43:177 client: Network: connection to endpoint failed and no more endpoints to try
   Ice.ConnectionLostException: Exception of type 'Ice.ConnectionLostException' was thrown.
      at Ice.SSL.TransceiverI.finishAuthenticate() in /home/runner/work/ice/ice/csharp/src/Ice/SSL/TransceiverI.cs:line 435
      at Ice.SSL.TransceiverI.finishWrite(Buffer buf) in /home/runner/work/ice/ice/csharp/src/Ice/SSL/TransceiverI.cs:line 270
      at Ice.Internal.IdleTimeoutTransceiverDecorator.finishWrite(Buffer buf) in /home/runner/work/ice/ice/csharp/src/Ice/Internal/IdleTimeoutTransceiverDecorator.cs:line 60
      at Ice.ConnectionI.finishAsync(Int32 operation) in /home/runner/work/ice/ice/csharp/src/Ice/ConnectionI.cs:line 662

```

server
```
-- 10/24/2024 11:51:43:167 server: Network: accepted ssl connection
   local address = 127.0.0.1:14001
   remote address = 127.0.0.1:56714
-- 10/24/2024 11:51:43:170 server: Network: rejecting new ssl connection
   local address = 127.0.0.1:14001
   remote address = 127.0.0.1:56728
   because the maximum number of connections has been reached
-- 10/24/2024 11:51:43:175 server: Network: rejecting new ssl connection
   local address = 127.0.0.1:14001
   remote address = 127.0.0.1:56738
   because the maximum number of connections has been reached
-- 10/24/2024 11:51:43:176 server: Network: closed ssl connection  <== too late
   local address = 127.0.0.1:14001
   remote address = 127.0.0.1:56634
```

We have a delay with ws[s]. Not clear why we would need a delay with ssl.
