### ISSUE TITLE
java/Ice/idleTimeout failure on Windows

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#3029]
From https://github.com/zeroc-ice/ice/actions/runs/11614733508/job/32343611358?pr=3024:

```
*** [171/270] Running java/Ice/idleTimeout tests ***
[ running client/server test - 10/31/24 16:16:59 ]
- Config: ssl,x64
(C:\hostedtoolcache\windows\Java_Oracle_jdk\17\x64\bin\java -ea -Dtest.class=test.Ice.idleTimeout.Server test.TestDriver --Ice.Default.Host=127.0.0.1 --Test.BasePort=14100 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --IceSSL.*** --IceSSL.DefaultDir=D:\a\ice\ice\certs --IceSSL.Keystore=server.jks --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 env={'CLASSPATH': 'D:\\a\\ice\\ice\\java\\lib\\test.jar'})
(C:\hostedtoolcache\windows\Java_Oracle_jdk\17\x64\bin\java -ea -Dtest.class=test.Ice.idleTimeout.Client test.TestDriver --Ice.Default.Host=127.0.0.1 --Test.BasePort=14100 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --IceSSL.*** --IceSSL.DefaultDir=D:\a\ice\ice\certs --IceSSL.Keystore=client.jks env={'CLASSPATH': 'D:\\a\\ice\\ice\\java\\lib\\test.jar'})
testing that the idle check does not abort a back-pressured connection... com.zeroc.Ice.ConnectionAbortedException: Connection aborted by the idle check because it did not receive any bytes for 1s.
	at com.zeroc.Ice.OutgoingAsync.waitForResponseOrUserEx(OutgoingAsync.java:110)
	at com.zeroc.Ice.OutgoingAsync.waitForResponse(OutgoingAsync.java:93)
	at test.Ice.idleTimeout.Test.TestIntfPrx.sleep(TestIntfPrx.java:27)
	at test.Ice.idleTimeout.Test.TestIntfPrx.sleep(TestIntfPrx.java:22)
	at test.Ice.idleTimeout.AllTests.testIdleCheckDoesNotAbortBackPressuredConnection(AllTests.java:51)
	at test.Ice.idleTimeout.AllTests.allTests(AllTests.java:25)
	at test.Ice.idleTimeout.Client.run(Client.java:13)
	at test.TestDriver.main(TestDriver.java:26)
```

**Comment by bernardnormier** [comment]
Very hard to reproduce. The fixes from #3156 once applied to Java could help.

**Comment by bernardnormier** [comment]
Unable to reproduce this issue.
