### ISSUE TITLE
Trace: Assertion failed: undefined

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#3101]
I am getting this rather surprising assert in JS when my InputStream constructor fails.

Is this expected?

```
buffer: "Trace: Assertion failed: undefined
    at Debug.assert (file:///Users/bernard/builds/ice/js/node_modules/ice/src/Ice/Debug.js:8:21)
    at TcpTransceiver.close (file:///Users/bernard/builds/ice/js/node_modules/ice/src/Ice/TcpTransceiver.js:121:23)
    at OutgoingConnectionFactory.createConnection (file:///Users/bernard/builds/ice/js/node_modules/ice/src/Ice/OutgoingConnectionFactory.js:244:33)
    at ConnectCallback.nextEndpoint (file:///Users/bernard/builds/ice/js/node_modules/ice/src/Ice/OutgoingConnectionFactory.js:607:37)
    at OutgoingConnectionFactory.getConnection (file:///Users/bernard/builds/ice/js/node_modules/ice/src/Ice/OutgoingConnectionFactory.js:212:16)
    at ConnectCallback.getConnection (file:///Users/bernard/builds/ice/js/node_modules/ice/src/Ice/OutgoingConnectionFactory.js:565:46)
    at ConnectCallback.start (file:///Users/bernard/builds/ice/js/node_modules/ice/src/Ice/OutgoingConnectionFactory.js:559:14)
    at OutgoingConnectionFactory.create (file:///Users/bernard/builds/ice/js/node_modules/ice/src/Ice/OutgoingConnectionFactory.js:67:71)
    at RoutableReference.createConnection (file:///Users/bernard/builds/ice/js/node_modules/ice/src/Ice/Reference.js:1270:18)
    at RoutableReference.getConnectionNoRouterInfo (file:///Users/bernard/builds/ice/js/node_modules/ice/src/Ice/Reference.js:1074:18)
```

**Comment by pepone** [comment]
The `undefined` is bogus, we should not print the message when the assert doesn't include one. Fixed in https://github.com/zeroc-ice/ice/pull/3099

As per why you hit the assert I assume we are not correctly handling non local exceptions. How can I reproduce this? just throwing from InputStream constructor?
