### ISSUE TITLE
Java Ice/ami failure Windows

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#3143]
I got this different failure with Java Ice/ami when trying to reproduce #3049

[logs.zip](https://github.com/user-attachments/files/17723000/logs.zip)

```
[ running client/server test - 11/12/24 21:48:43 ]
- Config: ws,ipv6,mx
testing begin/end invocation... ok
testing local exceptions... ok
testing sent callback... ok
testing sent async callback... ok
testing unexpected exceptions... ok
testing batch requests with proxy... ok
testing batch requests with connection... ok
testing batch requests with communicator... ok
testing future operations... ok
testing connection close... ok
t!!!!!!! unhandled exception in thread Thread-5: com.zeroc.Ice.ConnectionLostException
ecom.zeroc.Ice.ConnectionLostException
sting connection abort...       at com.zeroc.Ice.StreamSocket.read(StreamSocket.java:146)
o       at com.zeroc.Ice.StreamSocket.read(StreamSocket.java:116)
k
        at com.zeroc.Ice.TcpTransceiver.read(TcpTransceiver.java:49)
t       at com.zeroc.Ice.WSTransceiver.read(WSTransceiver.java:379)
esti    at com.zeroc.Ice.IdleTimeoutTransceiverDecorator.read(IdleTimeoutTransceiverDecorator.java:82)
        at com.zeroc.Ice.ConnectionI.read(ConnectionI.java:2458)
ng ic   at com.zeroc.Ice.ConnectionI.message(ConnectionI.java:565)
e_exe   at com.zeroc.Ice.ThreadPool.run(ThreadPool.java:352)
cuto    at com.zeroc.Ice.ThreadPool$EventHandlerThread.run(ThreadPool.java:662)
r       at java.base/java.lang.Thread.run(Thread.java:1583)
... java.util.concurrent.CompletionException: com.zeroc.Ice.ConnectionRefusedException
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:874)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
        at com.zeroc.Ice.ThreadPool$2.run(ThreadPool.java:341)
        at com.zeroc.Ice.ThreadPool.executeFromThisThread(ThreadPool.java:304)
        at com.zeroc.Ice.ThreadPoolCurrent.executeFromThisThread(ThreadPoolCurrent.java:35)
        at com.zeroc.Ice.RunnableThreadPoolWorkItem.execute(RunnableThreadPoolWorkItem.java:23)
        at com.zeroc.Ice.ThreadPoolWorkQueue.message(ThreadPoolWorkQueue.java:56)
        at com.zeroc.Ice.ThreadPool.run(ThreadPool.java:352)
        at com.zeroc.Ice.ThreadPool$EventHandlerThread.run(ThreadPool.java:662)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.zeroc.Ice.ConnectionRefusedException
        at com.zeroc.Ice.Network.doFinishConnect(Network.java:374)
        at com.zeroc.Ice.StreamSocket.connect(StreamSocket.java:71)
        at com.zeroc.Ice.TcpTransceiver.initialize(TcpTransceiver.java:21)
        at com.zeroc.Ice.WSTransceiver.initialize(WSTransceiver.java:28)
        at com.zeroc.Ice.IdleTimeoutTransceiverDecorator.initialize(IdleTimeoutTransceiverDecorator.java:39)
        at com.zeroc.Ice.ConnectionI.initialize(ConnectionI.java:1634)
        at com.zeroc.Ice.ConnectionI.message(ConnectionI.java:683)
        ... 3 more
Caused by: java.net.ConnectException: Connection refused: getsockopt
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:973)
        at com.zeroc.Ice.Network.doFinishConnect(Network.java:355)
        ... 9 more
saved C:\Users\jose\source\repos\3.8\ice\java\test\src\main\java\test\Ice\ami\client-111224-2148.log
saved C:\Users\jose\source\repos\3.8\ice\java\test\src\main\java\test\Ice\ami\server-111224-2148.log
unexpected exit status: expected: 0, got 1
```

**Comment by pepone** [comment]
Fixed by  #3142
