### ISSUE TITLE
C# Ice/timeout failure (Windows)

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#3144]
https://github.com/zeroc-ice/ice/actions/runs/11804450644/job/32884681995

```
2024-11-12T20:39:17.3905228Z Ice.ConnectTimeoutException: Connect timed out.
2024-11-12T20:39:17.3906638Z    at Ice.ObjectPrxHelperBase.ice_isA(String id, Dictionary`2 context) in D:\a\ice\ice\csharp\src\Ice\Proxy.cs:line 581
2024-11-12T20:39:17.3909017Z    at Ice.timeout.Test.ControllerPrxHelper.checkedCast(ObjectPrx b, Dictionary`2 ctx) in D:\a\ice\ice\csharp\test\Ice\timeout\msbuild\client\generated\Test.cs:line 397
2024-11-12T20:39:17.3911511Z    at Ice.timeout.AllTests.allTests(TestHelper helper) in D:\a\ice\ice\csharp\test\Ice\timeout\AllTests.cs:line 29
2024-11-12T20:39:17.3913218Z    at Ice.timeout.Client.runAsync(String[] args) in D:\a\ice\ice\csharp\test\Ice\timeout\Client.cs:line 20
2024-11-12T20:39:17.3914919Z    at Test.TestDriver.runTestAsync[T](String[] args) in D:\a\ice\ice\csharp\test\TestCommon\TestHelper.cs:line 232
2024-11-12T20:39:17.3916538Z saved D:\a\ice\ice\csharp\test\Ice\timeout\client-111224-2039.log
2024-11-12T20:39:17.3917733Z saved D:\a\ice\ice\csharp\test\Ice\timeout\server-111224-2039.log
```

**Comment by bernardnormier** [comment]
The logs don't provide much info. It's the very first connection to the "controller":

client
```
-- 11/12/2024 20:39:15:655 client: Network: trying to establish ssl connection to 127.0.0.1:14201
=== 1 second ===
-- 11/12/2024 20:39:16:673 client: Network: failed to establish ssl connection
   
   Ice.ConnectTimeoutException: Connect timed out.
-- 11/12/2024 20:39:16:673 client: Network: connection to endpoint failed and no more endpoints to try
   Ice.ConnectTimeoutException: Connect timed out.
-- 11/12/2024 20:39:16:675 client: Retry: cannot retry operation call because retry limit has been exceeded
   Ice.ConnectTimeoutException: Connect timed out.
```

server
```
-- 11/12/2024 20:39:15:449 server: Network: attempting to bind to ssl socket 127.0.0.1:14200
-- 11/12/2024 20:39:15:452 server: Network: listening for ssl connections
   local address = 127.0.0.1:14200
-- 11/12/2024 20:39:15:454 server: Network: published endpoints for object adapter 'TestAdapter':
   ssl -h 127.0.0.1 -p 14200 -t 60000
-- 11/12/2024 20:39:15:458 server: Network: accepting ssl connections at 127.0.0.1:14200
-- 11/12/2024 20:39:15:459 server: Network: attempting to bind to ssl socket 127.0.0.1:14201
-- 11/12/2024 20:39:15:459 server: Network: listening for ssl connections
   local address = 127.0.0.1:14201
-- 11/12/2024 20:39:15:459 server: Network: published endpoints for object adapter 'ControllerAdapter':
   ssl -h 127.0.0.1 -p 14201 -t 60000
-- 11/12/2024 20:39:15:459 server: Network: accepting ssl connections at 127.0.0.1:14201
-- 11/12/2024 20:39:15:674 server: Network: trying to accept ssl connection <== connection attempt from client
   local address = 127.0.0.1:14201
   remote address = 127.0.0.1:60558
=== Nothing more ===
```

**Comment by pepone** [comment]
This very first connections, is to the ControllerAdapter initiated by the checked cast in:

https://github.com/zeroc-ice/ice/blob/aaaf89dc8e93f65e342d560b7d6933152dd6c758/csharp/test/Ice/timeout/AllTests.cs#L29-L32

**Comment by bernardnormier** [comment]
I can't reproduce it.
