### ISSUE TITLE
Failure running test suite on Raspberry PI 3B/Android Things

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#315]
Running `./allTests.py --android --device=Android.local:5555 --controller-app --all`.

The test suite failed with:
```
- Ice/checksum
  [ running client/server test - 12/10/18 15:44:39 ]
  - Config: tcp,android,Android.local:5555
  com.zeroc.Ice.SocketException
      error = 0
  [...]
  	at sun.nio.ch.Net.bind(Net.java:442)
  	at sun.nio.ch.Net.bind(Net.java:434)
  	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:224)
  	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
  	at com.zeroc.IceInternal.Network.doBind(Network.java:405)
  	... 8 more
```

**Comment by bernardnormier** [comment]
```*** [7/38] Running java/Ice/checksum tests ***
[ running client/server test - 12/10/18 15:44:39 ]
- Config: tcp,android,Android.local:5555
exception ::Test::Common::ProcessFailedException
{
    reason = com.zeroc.Ice.SocketException
    error = 0
	at com.zeroc.IceInternal.Network.doBind(Network.java:411)
	at com.zeroc.IceInternal.TcpAcceptor.listen(TcpAcceptor.java:41)
	at com.zeroc.IceInternal.IncomingConnectionFactory.createAcceptor(IncomingConnectionFactory.java:681)
	at com.zeroc.IceInternal.IncomingConnectionFactory.<init>(IncomingConnectionFactory.java:498)
	at com.zeroc.Ice.ObjectAdapterI.<init>(ObjectAdapterI.java:1032)
	at com.zeroc.IceInternal.ObjectAdapterFactory.createObjectAdapter(ObjectAdapterFactory.java:185)
	at com.zeroc.Ice.CommunicatorI.createObjectAdapter(CommunicatorI.java:116)
	at test.Ice.checksum.Server.run(Server.java:21)
	at com.zeroc.testcontroller.ControllerApp$ControllerHelperI.run(ControllerApp.java:370)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:442)
	at sun.nio.ch.Net.bind(Net.java:434)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:224)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at com.zeroc.IceInternal.Network.doBind(Network.java:405)
	... 8 more

}

test in Ice/checksum failed:
exception ::Test::Common::ProcessFailedException
{
    reason = com.zeroc.Ice.SocketException
    error = 0
	at com.zeroc.IceInternal.Network.doBind(Network.java:411)
	at com.zeroc.IceInternal.TcpAcceptor.listen(TcpAcceptor.java:41)
	at com.zeroc.IceInternal.IncomingConnectionFactory.createAcceptor(IncomingConnectionFactory.java:681)
	at com.zeroc.IceInternal.IncomingConnectionFactory.<init>(IncomingConnectionFactory.java:498)
	at com.zeroc.Ice.ObjectAdapterI.<init>(ObjectAdapterI.java:1032)
	at com.zeroc.IceInternal.ObjectAdapterFactory.createObjectAdapter(ObjectAdapterFactory.java:185)
	at com.zeroc.Ice.CommunicatorI.createObjectAdapter(CommunicatorI.java:116)
	at test.Ice.checksum.Server.run(Server.java:21)
	at com.zeroc.testcontroller.ControllerApp$ControllerHelperI.run(ControllerApp.java:370)
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:442)
	at sun.nio.ch.Net.bind(Net.java:434)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:224)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at com.zeroc.IceInternal.Network.doBind(Network.java:405)
	... 8 more

}
...
```

**Comment by bentoi** [comment]
Can you still reproduce this failure?
