### ISSUE TITLE
python/Ice/asyncio failure (Windows)

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#3271]
From https://github.com/zeroc-ice/ice/actions/runs/12351181365/job/34465600576?pr=3270:

```
*** [244/271] Running python/Ice/asyncio tests ***
[ running client/server test - 12/16/24 12:03:11 ]
- Config: ssl,x64
("C:\hostedtoolcache\windows\Python\3.13.1\x64\python.exe"  D:\a\ice\ice\python\test\TestHelper.py Server --Ice.Default.Host=127.0.0.1 --Test.BasePort=14000 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --IceSSL.*** --IceSSL.DefaultDir=D:\a\ice\ice\certs --IceSSL.CAs=cacert.pem --IceSSL.CertFile=server.p12 --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 env={'PATH': 'D:\\a\\ice\\ice\\cpp\\bin\\x64\\Release', 'PYTHONPATH': 'D:\\a\\ice\\ice\\python\\python\\x64\\Release;D:\\a\\ice\\ice\\python\\python;D:\\a\\ice\\ice\\python\\test\\Ice\\asyncio'})
("C:\hostedtoolcache\windows\Python\3.13.1\x64\python.exe"  D:\a\ice\ice\python\test\TestHelper.py Client --Ice.Default.Host=127.0.0.1 --Test.BasePort=14000 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --IceSSL.*** --IceSSL.DefaultDir=D:\a\ice\ice\certs --IceSSL.CAs=cacert.pem --IceSSL.CertFile=client.p12 env={'PATH': 'D:\\a\\ice\\ice\\cpp\\bin\\x64\\Release', 'PYTHONPATH': 'D:\\a\\ice\\ice\\python\\python\\x64\\Release;D:\\a\\ice\\ice\\python\\python;D:\\a\\ice\\ice\\python\\test\\Ice\\asyncio'})
testing invocation... Executing <Task pending name='Task-1' coro=<Client.run.<locals>.runAsync() running at D:\a\ice\ice\python\test\Ice\asyncio\Client.py:18> wait_for=<Future pending cb=[wrap_future.<locals>.<lambda>() at D:\a\ice\ice\python\python\Ice\Future.py:48, Task.task_wakeup()] created at C:\hostedtoolcache\windows\Python\3.13.1\x64\Lib\asyncio\base_events.py:459> cb=[_run_until_complete_cb() at C:\hostedtoolcache\windows\Python\3.13.1\x64\Lib\asyncio\base_events.py:181] created at C:\hostedtoolcache\windows\Python\3.13.1\x64\Lib\asyncio\runners.py:100> took 0.132 seconds
ok
testing exceptions... ok
testing cancellation... ok
Executing <Task pending name='Task-1' coro=<Server.run.<locals>.runAsync() running at D:\a\ice\ice\python\test\Ice\asyncio\Server.py:28> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at C:\hostedtoolcache\windows\Python\3.13.1\x64\Lib\asyncio\futures.py:384, Task.task_wakeup()] created at C:\hostedtoolcache\windows\Python\3.13.1\x64\Lib\asyncio\base_events.py:459> cb=[_run_until_complete_cb() at C:\hostedtoolcache\windows\Python\3.13.1\x64\Lib\asyncio\base_events.py:181] created at C:\hostedtoolcache\windows\Python\3.13.1\x64\Lib\asyncio\runners.py:100> took 0.142 seconds
[ running client/server test - 12/16/24 12:03:13 ]
- Config: ws,compress,ipv6,serialize,mx,x64
("C:\hostedtoolcache\windows\Python\3.13.1\x64\python.exe"  D:\a\ice\ice\python\test\TestHelper.py Server --Ice.Default.Host=::1 --Test.BasePort=14000 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ws --Ice.Override.Compress=1 --Ice.ThreadPool.Server.Serialize=1 --Ice.IPv6=1 --Ice.PreferIPv6Address=1 --Ice.Admin.Endpoints="tcp -h \"::1\"" --Ice.Admin.InstanceName=Server --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 env={'PATH': 'D:\\a\\ice\\ice\\cpp\\bin\\x64\\Release', 'PYTHONPATH': 'D:\\a\\ice\\ice\\python\\python\\x64\\Release;D:\\a\\ice\\ice\\python\\python;D:\\a\\ice\\ice\\python\\test\\Ice\\asyncio'})
("C:\hostedtoolcache\windows\Python\3.13.1\x64\python.exe"  D:\a\ice\ice\python\test\TestHelper.py Client --Ice.Default.Host=::1 --Test.BasePort=14000 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ws --Ice.Override.Compress=1 --Ice.ThreadPool.Server.Serialize=1 --Ice.IPv6=1 --Ice.PreferIPv6Address=1 --Ice.Admin.Endpoints="tcp -h \"::1\"" --Ice.Admin.InstanceName=Client --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none env={'PATH': 'D:\\a\\ice\\ice\\cpp\\bin\\x64\\Release', 'PYTHONPATH': 'D:\\a\\ice\\ice\\python\\python\\x64\\Release;D:\\a\\ice\\ice\\python\\python;D:\\a\\ice\\ice\\python\\test\\Ice\\asyncio'})
testing invocation... ok
testing exceptions... ok
testing cancellation... Traceback (most recent call last):
  File "D:\a\ice\ice\python\test\TestHelper.py", line 89, in run
    helper.run(sys.argv[2:])
    ~~~~~~~~~~^^^^^^^^^^^^^^
  File "D:\a\ice\ice\python\test\Ice\asyncio\Client.py", line 20, in run
    asyncio.run(runAsync(), debug=True)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.13.1\x64\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.13.1\x64\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.13.1\x64\Lib\asyncio\base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "D:\a\ice\ice\python\test\Ice\asyncio\Client.py", line 18, in runAsync
    await AllTests.allTestsAsync(self, communicator)
  File "D:\a\ice\ice\python\test\Ice\asyncio\AllTests.py", line 58, in allTestsAsync
    await asyncioFuture
Ice.InvocationCanceledException: invocation canceled
!! 12/16/24 12:03:14809 error: communicator not destroyed during global destruction.

```

**Comment by pepone** [comment]
I have been running this for a while on Windows with Python 3.13.1 but cannot reproduce.

Looking at the code we have

https://github.com/zeroc-ice/ice/blob/075234d69ea3944132670122694b9264e1cc55fd/python/python/Ice/Future.py#L20-L56

Here the wrap future takes care of forwarding state changes between Ice.Future and asyncio.future.

In the failing test the cancel call correspond to `InvocationFuture.cancel`

https://github.com/zeroc-ice/ice/blob/075234d69ea3944132670122694b9264e1cc55fd/python/python/Ice/InvocationFuture.py#L20-L22

Which first cancels the C++ requests through the AsyncInvocationContext, and then cancels the Ice.Future.

My understanding here is that the cancelation of the C++ asynchronous request always set the exception asynchronously.

https://github.com/zeroc-ice/ice/blob/075234d69ea3944132670122694b9264e1cc55fd/cpp/src/Ice/OutgoingAsync.cpp#L293

https://github.com/zeroc-ice/ice/blob/075234d69ea3944132670122694b9264e1cc55fd/cpp/src/Ice/ConnectionI.cpp#L874-L877

https://github.com/zeroc-ice/ice/blob/075234d69ea3944132670122694b9264e1cc55fd/cpp/src/Ice/OutgoingAsync.cpp#L74-L82

So here I would expect that `Future.cancel()` always runs before than the exception handler, because this code is run with the GIL locked, and the C++ exception is set asynchronously, when the IcePy code exception handler runs it have to wait to acquire the GIL.

But the error seems to indicate otherwise, for example it seems like the set_exception callback was run before that `Future.cancel` was called. This will explain why asyncio future was completed with an exception instead of being canceled.

**Comment by externl** [comment]
I got a similar failure in my PR (https://github.com/zeroc-ice/ice/actions/runs/13840779220/job/38727461118?pr=3689):

```
*** [244/270] Running python/Ice/asyncio tests ***
[ running client/server test - 03/13/25 18:28:45 ]
- Config: ssl,x64
("C:\hostedtoolcache\windows\Python\3.13.2\x64\python.exe"  D:\a\ice\ice\python\test\TestHelper.py Server --Ice.Default.Host=127.0.0.1 --Test.BasePort=14200 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --IceSSL.*** --IceSSL.DefaultDir=D:\a\ice\ice\certs --IceSSL.CAs=cacert.pem --IceSSL.CertFile=server.p12 --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 env={'PATH': 'D:\\a\\ice\\ice\\cpp\\bin\\x64\\Release', 'PYTHONPATH': 'D:\\a\\ice\\ice\\python\\python\\x64\\Release;D:\\a\\ice\\ice\\python\\python;D:\\a\\ice\\ice\\python\\test\\Ice\\asyncio'})
("C:\hostedtoolcache\windows\Python\3.13.2\x64\python.exe"  D:\a\ice\ice\python\test\TestHelper.py Client --Ice.Default.Host=127.0.0.1 --Test.BasePort=14200 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --IceSSL.*** --IceSSL.DefaultDir=D:\a\ice\ice\certs --IceSSL.CAs=cacert.pem --IceSSL.CertFile=client.p12 env={'PATH': 'D:\\a\\ice\\ice\\cpp\\bin\\x64\\Release', 'PYTHONPATH': 'D:\\a\\ice\\ice\\python\\python\\x64\\Release;D:\\a\\ice\\ice\\python\\python;D:\\a\\ice\\ice\\python\\test\\Ice\\asyncio'})
testing invocation... ok
testing exceptions... ok
testing cancellation... ok
testing communicator shutdownCompleted... ok
Executing <Task pending name='Task-1' coro=<Server.run.<locals>.runAsync() running at D:\a\ice\ice\python\test\Ice\asyncio\Server.py:31> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at C:\hostedtoolcache\windows\Python\3.13.2\x64\Lib\asyncio\futures.py:384, Task.task_wakeup()] created at C:\hostedtoolcache\windows\Python\3.13.2\x64\Lib\asyncio\base_events.py:459> cb=[_run_until_complete_cb() at C:\hostedtoolcache\windows\Python\3.13.2\x64\Lib\asyncio\base_events.py:181] created at C:\hostedtoolcache\windows\Python\3.13.2\x64\Lib\asyncio\runners.py:100> took 0.106 seconds
[ running client/server test - 03/13/25 18:28:47 ]
- Config: ws,compress,ipv6,serialize,mx,x64
("C:\hostedtoolcache\windows\Python\3.13.2\x64\python.exe"  D:\a\ice\ice\python\test\TestHelper.py Server --Ice.Default.Host=::1 --Test.BasePort=14200 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ws --Ice.Override.Compress=1 --Ice.ThreadPool.Server.Serialize=1 --Ice.IPv6=1 --Ice.PreferIPv6Address=1 --Ice.Admin.Endpoints="tcp -h \"::1\"" --Ice.Admin.InstanceName=Server --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 env={'PATH': 'D:\\a\\ice\\ice\\cpp\\bin\\x64\\Release', 'PYTHONPATH': 'D:\\a\\ice\\ice\\python\\python\\x64\\Release;D:\\a\\ice\\ice\\python\\python;D:\\a\\ice\\ice\\python\\test\\Ice\\asyncio'})
("C:\hostedtoolcache\windows\Python\3.13.2\x64\python.exe"  D:\a\ice\ice\python\test\TestHelper.py Client --Ice.Default.Host=::1 --Test.BasePort=14200 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ws --Ice.Override.Compress=1 --Ice.ThreadPool.Server.Serialize=1 --Ice.IPv6=1 --Ice.PreferIPv6Address=1 --Ice.Admin.Endpoints="tcp -h \"::1\"" --Ice.Admin.InstanceName=Client --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none env={'PATH': 'D:\\a\\ice\\ice\\cpp\\bin\\x64\\Release', 'PYTHONPATH': 'D:\\a\\ice\\ice\\python\\python\\x64\\Release;D:\\a\\ice\\ice\\python\\python;D:\\a\\ice\\ice\\python\\test\\Ice\\asyncio'})
testing invocation... ok
testing exceptions... ok
testing cancellation... ok
testing communicator shutdownCompleted... Fatal Python error: PyThreadState_Get: the function must be called with the GIL held, after Python initialization and before Python finalization, but the GIL is released (the current Python thread state is NULL)
Python runtime state: initialized

Thread 0x00000d04 (most recent call first):
  File "D:\a\ice\ice\python\python\Ice\Communicator.py", line 53 in destroy
  File "D:\a\ice\ice\python\test\Ice\asyncio\AllTests.py", line 93 in destroy_communicator
  File "C:\hostedtoolcache\windows\Python\3.13.2\x64\Lib\threading.py", line 992 in run
  File "C:\hostedtoolcache\windows\Python\3.13.2\x64\Lib\threading.py", line 1041 in _bootstrap_inner
  File "C:\hostedtoolcache\windows\Python\3.13.2\x64\Lib\threading.py", line 1012 in _bootstrap

Thread 0x00001314 (most recent call first):
  File "C:\hostedtoolcache\windows\Python\3.13.2\x64\Lib\threading.py", line 1092 in join
  File "D:\a\ice\ice\python\test\Ice\asyncio\AllTests.py", line 103 in allTestsAsync
  File "D:\a\ice\ice\python\test\Ice\asyncio\Client.py", line 17 in runAsync
  File "C:\hostedtoolcache\windows\Python\3.13.2\x64\Lib\asyncio\events.py", line 89 in _run
  File "C:\hostedtoolcache\windows\Python\3.13.2\x64\Lib\asyncio\base_events.py", line 2032 in _run_once
  File "C:\hostedtoolcache\windows\Python\3.13.2\x64\Lib\asyncio\base_events.py", line 683 in run_forever
  File "C:\hostedtoolcache\windows\Python\3.13.2\x64\Lib\asyncio\base_events.py", line 712 in run_until_complete
  File "C:\hostedtoolcache\windows\Python\3.13.2\x64\Lib\asyncio\runners.py", line 118 in run
  File "C:\hostedtoolcache\windows\Python\3.13.2\x64\Lib\asyncio\runners.py", line 195 in run
  File "D:\a\ice\ice\python\test\Ice\asyncio\Client.py", line 19 in run
  File "D:\a\ice\ice\python\test\TestHelper.py", line 87 in run
  File "D:\a\ice\ice\python\test\TestHelper.py", line 95 in <module>

test in Ice/asyncio failed:
Traceback (most recent call last):
  File "D:\a\ice\ice\scripts\Util.py", line 1936, in run
    self.runWithDriver(current)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\a\ice\ice\scripts\Util.py", line 1967, in runWithDriver
    current.driver.runClientServerTestCase(current)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\a\ice\ice\scripts\LocalDriver.py", line 678, in runClientServerTestCase
    self.runner.runClientSide(client, current, host)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\ice\ice\scripts\LocalDriver.py", line 205, in runClientSide
    testcase._runClientSide(current, host)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\a\ice\ice\scripts\Util.py", line 1913, in _runClientSide
    self.runClientSide(current)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\a\ice\ice\scripts\Util.py", line 1799, in runClientSide
    self._runClient(current, client)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\a\ice\ice\scripts\Util.py", line 1925, in _runClient
    client.run(current)
    ~~~~~~~~~~^^^^^^^^^
  File "D:\a\ice\ice\scripts\Util.py", line 1322, in run
    process.waitSuccess(exitstatus=exitstatus, timeout=30)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\ice\ice\scripts\Expect.py", line 689, in waitSuccess
    self.testExitStatus(exitstatus)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "D:\a\ice\ice\scripts\Expect.py", line 733, in testExitStatus
    test(self.exitstatus, exitstatus)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\ice\ice\scripts\Expect.py", line 715, in test
    raise RuntimeError(
    ...<3 lines>...
    )
RuntimeError: unexpected exit status: expected: 0, got 3221226505


Traceback (most recent call last):
  File "D:\a\ice\ice\scripts\LocalDriver.py", line 604, in runTestSuite
    testcase.run(current)
    ~~~~~~~~~~~~^^^^^^^^^
  File "D:\a\ice\ice\scripts\Util.py", line 1936, in run
    self.runWithDriver(current)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\a\ice\ice\scripts\Util.py", line 1967, in runWithDriver
    current.driver.runClientServerTestCase(current)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\a\ice\ice\scripts\LocalDriver.py", line 678, in runClientServerTestCase
    self.runner.runClientSide(client, current, host)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\ice\ice\scripts\LocalDriver.py", line 205, in runClientSide
    testcase._runClientSide(current, host)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "D:\a\ice\ice\scripts\Util.py", line 1913, in _runClientSide
    self.runClientSide(current)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\a\ice\ice\scripts\Util.py", line 1799, in runClientSide
    self._runClient(current, client)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\a\ice\ice\scripts\Util.py", line 1925, in _runClient
    client.run(current)
    ~~~~~~~~~~^^^^^^^^^
  File "D:\a\ice\ice\scripts\Util.py", line 1322, in run
    process.waitSuccess(exitstatus=exitstatus, timeout=30)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\ice\ice\scripts\Expect.py", line 689, in waitSuccess
    self.testExitStatus(exitstatus)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "D:\a\ice\ice\scripts\Expect.py", line 733, in testExitStatus
    test(self.exitstatus, exitstatus)
    ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\ice\ice\scripts\Expect.py", line 715, in test
    raise RuntimeError(
    ...<3 lines>...
    )
RuntimeError: unexpected exit status: expected: 0, got 3221226505
```

**Comment by pepone** [comment]
There is a fix for this in the connection close PR

**Comment by pepone** [comment]
Cannot reproduce.

**Comment by pepone** [comment]
Before we have the event-loop adapter we were doing:

```
    asyncioFuture = Ice.wrap_future(future)
    future.cancel()
```

With the new version we are canceling the asyncio future, as invocations now returned the future wrapped use the wrapFuture method of the event loop adapter.

From the failure it seems like the GIL was released, and set_exception was able to acquire it before than the future was marked as canceled. 

```
self._asyncInvocationContext.cancel() 
return Future.cancel(self) 
```

Maybe we should do this the other way around, first cancel the future then the invocation context.

**Comment by pepone** [comment]
Reworked InvocationFuture cancel in #3973, let's reopen if we hit this again.
