### ISSUE TITLE
Java  inactivityTimeout test failure on Windows with ssl

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#3276]
From https://github.com/zeroc-ice/ice/actions/runs/12360208005/job/34494612010

```
2024-12-16T20:53:59.7737774Z *** [174/271] Running java/Ice/inactivityTimeout tests ***
2024-12-16T20:53:59.7738413Z [ running client/server test - 12/16/24 20:53:26 ]
2024-12-16T20:53:59.7738917Z - Config: ssl,x64
2024-12-16T20:53:59.7744017Z (C:\hostedtoolcache\windows\Java_Oracle_jdk\17\x64\bin\java -ea -Dtest.class=test.Ice.inactivityTimeout.Server test.TestDriver --Ice.Default.Host=127.0.0.1 --Test.BasePort=14000 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --IceSSL.*** --IceSSL.DefaultDir=D:\a\ice\ice\certs --IceSSL.Keystore=server.jks --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 env={'CLASSPATH': 'D:\\a\\ice\\ice\\java\\lib\\test.jar'})
2024-12-16T20:53:59.7750058Z (C:\hostedtoolcache\windows\Java_Oracle_jdk\17\x64\bin\java -ea -Dtest.class=test.Ice.inactivityTimeout.Client test.TestDriver --Ice.Default.Host=127.0.0.1 --Test.BasePort=14000 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.IPv6=0 --IceSSL.*** --IceSSL.DefaultDir=D:\a\ice\ice\certs --IceSSL.Keystore=client.jks env={'CLASSPATH': 'D:\\a\\ice\\ice\\java\\lib\\test.jar'})
2024-12-16T20:53:59.7752726Z testing that the client side inactivity timeout shuts down the connection... ok
2024-12-16T20:53:59.7755112Z testing that the server side inactivity timeout shuts down the connection... ok
2024-12-16T20:53:59.7756157Z testing the inactivity timeout with an outstanding two-way request... ok
2024-12-16T20:53:59.7757096Z testing the inactivity timeout with an outstanding one-way request... ok
2024-12-16T20:53:59.7757850Z [ running client/server test - 12/16/24 20:53:44 ]
2024-12-16T20:53:59.7758437Z - Config: ws,compress,ipv6,serialize,mx,x64
2024-12-16T20:53:59.7764307Z (C:\hostedtoolcache\windows\Java_Oracle_jdk\17\x64\bin\java -ea -Dtest.class=test.Ice.inactivityTimeout.Server test.TestDriver --Ice.Default.Host=::1 --Test.BasePort=14000 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ws --Ice.Override.Compress=1 --Ice.ThreadPool.Server.Serialize=1 --Ice.IPv6=1 --Ice.PreferIPv6Address=1 --Ice.Admin.Endpoints="tcp -h \"::1\"" --Ice.Admin.InstanceName=Server --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 env={'CLASSPATH': 'D:\\a\\ice\\ice\\java\\lib\\test.jar'})
2024-12-16T20:53:59.7769223Z (C:\hostedtoolcache\windows\Java_Oracle_jdk\17\x64\bin\java -ea -Dtest.class=test.Ice.inactivityTimeout.Client test.TestDriver --Ice.Default.Host=::1 --Test.BasePort=14000 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ws --Ice.Override.Compress=1 --Ice.ThreadPool.Server.Serialize=1 --Ice.IPv6=1 --Ice.PreferIPv6Address=1 --Ice.Admin.Endpoints="tcp -h \"::1\"" --Ice.Admin.InstanceName=Client --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none env={'CLASSPATH': 'D:\\a\\ice\\ice\\java\\lib\\test.jar'})
2024-12-16T20:53:59.7771233Z testing that the client side inactivity timeout shuts down the connection... ok
2024-12-16T20:53:59.7771793Z testing that the server side inactivity timeout shuts down the connection... ok
2024-12-16T20:53:59.7772999Z testing the inactivity timeout with an outstanding two-way request... com.zeroc.Ice.ConnectionAbortedException: Connection aborted by the idle check because it did not receive any bytes for 1s.
2024-12-16T20:53:59.7773913Z 	at com.zeroc.Ice.OutgoingAsync.waitForResponseOrUserEx(OutgoingAsync.java:108)
2024-12-16T20:53:59.7774437Z 	at com.zeroc.Ice.OutgoingAsync.waitForResponse(OutgoingAsync.java:91)
2024-12-16T20:53:59.7774925Z 	at test.Ice.inactivityTimeout.Test.TestIntfPrx.sleep(TestIntfPrx.java:27)
2024-12-16T20:53:59.7775415Z 	at test.Ice.inactivityTimeout.Test.TestIntfPrx.sleep(TestIntfPrx.java:22)
2024-12-16T20:53:59.7775970Z 	at test.Ice.inactivityTimeout.AllTests.testWithOutstandingRequest(AllTests.java:107)
2024-12-16T20:53:59.7776485Z 	at test.Ice.inactivityTimeout.AllTests.allTests(AllTests.java:26)
2024-12-16T20:53:59.7776884Z 	at test.Ice.inactivityTimeout.Client.run(Client.java:18)
2024-12-16T20:53:59.7777202Z 	at test.TestDriver.main(TestDriver.java:26)
2024-12-16T20:53:59.7777661Z -! 12/16/24 20:53:58:817 warning: Ice.ThreadPool.Server-1: connection exception:
2024-12-16T20:53:59.7778019Z    local address = 0:0:0:0:0:0:0:1:14000
2024-12-16T20:53:59.7778261Z    remote address = 0:0:0:0:0:0:0:1:64009
2024-12-16T20:53:59.7778573Z    com.zeroc.Ice.ConnectionLostException
2024-12-16T20:53:59.7778906Z    	at com.zeroc.Ice.StreamSocket.read(StreamSocket.java:155)
2024-12-16T20:53:59.7779404Z    	at com.zeroc.Ice.StreamSocket.read(StreamSocket.java:116)
2024-12-16T20:53:59.7779976Z    	at com.zeroc.Ice.TcpTransceiver.read(TcpTransceiver.java:49)
2024-12-16T20:53:59.7780368Z    	at com.zeroc.Ice.WSTransceiver.read(WSTransceiver.java:379)
2024-12-16T20:53:59.7780913Z    	at com.zeroc.Ice.IdleTimeoutTransceiverDecorator.read(IdleTimeoutTransceiverDecorator.java:76)
2024-12-16T20:53:59.7781446Z    	at com.zeroc.Ice.ConnectionI.read(ConnectionI.java:2466)
2024-12-16T20:53:59.7781909Z    	at com.zeroc.Ice.ConnectionI.message(ConnectionI.java:570)
2024-12-16T20:53:59.7782277Z    	at com.zeroc.Ice.ThreadPool.run(ThreadPool.java:352)
2024-12-16T20:53:59.7783266Z    	at com.zeroc.Ice.ThreadPool$EventHandlerThread.run(ThreadPool.java:662)
2024-12-16T20:53:59.7783664Z    	at java.base/java.lang.Thread.run(Thread.java:833)
2024-12-16T20:53:59.7784006Z    Caused by: java.net.SocketException: Connection reset
2024-12-16T20:53:59.7784556Z    	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
2024-12-16T20:53:59.7785107Z    	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
2024-12-16T20:53:59.7785529Z    	at com.zeroc.Ice.StreamSocket.read(StreamSocket.java:144)
2024-12-16T20:53:59.7785803Z    	... 9 more
```

**Comment by pepone** [comment]
Cannot reproduce locally, let's reopen if it fails with the tracing added in https://github.com/zeroc-ice/ice/commit/910ec57b13da88469f4c54f8fc95d8d6b40d622a
