### ISSUE TITLE
Android NoSuchMethodError

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#3298]
```
Process: com.zeroc.testcontroller, PID: 5879
java.lang.NoSuchMethodError: No interface method toList()Ljava/util/List; in class Ljava/util/stream/Stream; or its super classes (declaration of 'java.util.stream.Stream' appears in /apex/com.android.art/javalib/core-oj.jar)
	at com.zeroc.Ice.ObjectAdapter.computePublishedEndpoints(ObjectAdapter.java:1399)
	at com.zeroc.Ice.ObjectAdapter.<init>(ObjectAdapter.java:1221)
	at com.zeroc.Ice.ObjectAdapterFactory.createObjectAdapter(ObjectAdapterFactory.java:133)
	at com.zeroc.Ice.Communicator.createObjectAdapter(Communicator.java:210)
	at com.zeroc.Ice.Communicator.createObjectAdapter(Communicator.java:179)
	at com.zeroc.testcontroller.ControllerApp$ControllerI.<init>(ControllerApp.java:181)
	at com.zeroc.testcontroller.ControllerApp.startController(ControllerApp.java:137)
	at com.zeroc.testcontroller.ControllerActivity.setup(ControllerActivity.java:129)
	at com.zeroc.testcontroller.ControllerActivity.onStart(ControllerActivity.java:66)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1543)
	at android.app.Activity.performStart(Activity.java:8330)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3670)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by pepone** [comment]
We need minSdkVersion 34 to use Java 17 features.
