### ISSUE TITLE
Android computePublishedEndpoints fails with NetworkOnMainThread

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#3299]
```
Process: com.zeroc.testcontroller, PID: 3661
android.os.NetworkOnMainThreadException
	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1675)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:115)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getLocalHost(InetAddress.java:1488)
	at com.zeroc.Ice.ObjectAdapter.computePublishedEndpoints(ObjectAdapter.java:1423)
```

**Comment by pepone** [comment]
I think we might need to use a hardcoded default for publishedHost on android instead of calling `lookupHostByName`. Otherwise the OA cannot be initialized synchronously on the main thread.

Another option is to require applications to create OA from another thread. But that would require more changes for existing applications.
