### ISSUE TITLE
MaxConnection tests Android failure

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#3300]
```
*** [22/40] Running java/Ice/maxConnections tests ***
[ running client/server test - 12/22/24 19:03:41 ]
- Config: android,Debug,x64
testing the creation of 100 connections... com.zeroc.Ice.CloseTimeoutException: Close timed out.
        at com.zeroc.Ice.QueueExecutorService.execute(QueueExecutorService.java:64)
        at com.zeroc.Ice.QueueExecutorService.executeNoThrow(QueueExecutorService.java:28)
        at com.zeroc.Ice.ConnectionI.close(ConnectionI.java:159)
        at test.Ice.maxConnections.AllTests.testCreateConnections(AllTests.java:57)
        at test.Ice.maxConnections.AllTests.allTests(AllTests.java:35)
        at test.Ice.maxConnections.Client.run(Client.java:15)
        at com.zeroc.testcontroller.ControllerApp$ControllerHelperI.run(ControllerApp.java:328)
```

**Comment by pepone** [comment]
The queue executor thread is paused in `ConnectionI.closeImpl`

```
wait:-1, Object (java.lang)
wait:386, Object (java.lang)
wait:524, Object (java.lang)
closeImpl:193, ConnectionI (com.zeroc.Ice)
-$$Nest$mcloseImpl:-1, ConnectionI (com.zeroc.Ice)
call:163, ConnectionI$2 (com.zeroc.Ice)
call:160, ConnectionI$2 (com.zeroc.Ice)
run:264, FutureTask (java.util.concurrent)
runWorker:1145, ThreadPoolExecutor (java.util.concurrent)
run:644, ThreadPoolExecutor$Worker (java.util.concurrent)
run:1012, Thread (java.lang)
```

And we have `ConnectionI.finished` is waiting to execute `finish` on the executor.

```
park:-1, Unsafe (jdk.internal.misc)
park:211, LockSupport (java.util.concurrent.locks)
awaitDone:447, FutureTask (java.util.concurrent)
get:190, FutureTask (java.util.concurrent)
execute:54, QueueExecutorService (com.zeroc.Ice)
executeNoThrow:28, QueueExecutorService (com.zeroc.Ice)
finished:939, ConnectionI (com.zeroc.Ice)
execute:29, ThreadPool$FinishedWorkItem (com.zeroc.Ice)
message:56, ThreadPoolWorkQueue (com.zeroc.Ice)
run:352, ThreadPool (com.zeroc.Ice)
-$$Nest$mrun:-1, ThreadPool (com.zeroc.Ice)
run:662, ThreadPool$EventHandlerThread (com.zeroc.Ice)
run:1012, Thread (java.lang)
```

This executor has a single thread, so threads get starved and eventually close times out.

**Comment by pepone** [comment]
Increasing the executor thread pool size fixes the test. Not clear why we have a single thread executor.

**Comment by bernardnormier** [comment]
We can reproduce it on "non-Android" with:

```
% python3 allTests.py Ice/maxConnections --debug --cprops=Ice.ThreadInterruptSafe=1 
*** [1/1] Running java/Ice/maxConnections tests ***
[ running client/server test - 01/07/25 17:34:19 ]
- Config: ['Ice.ThreadInterruptSafe=1']
(java -ea -Dtest.class=test.Ice.maxConnections.Server test.TestDriver --Ice.Default.Host=127.0.0.1 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp --Ice.IPv6=0 --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 --Ice.Trace.Network=2 --Ice.LogFile=/Users/bernard/builds/ice/java/test/src/main/java/test/Ice/maxConnections/server-010725-1734.log env={'CLASSPATH': '/Users/bernard/builds/ice/java/lib/test.jar'})
(java -ea -Dtest.class=test.Ice.maxConnections.Client test.TestDriver --Ice.Default.Host=127.0.0.1 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp --Ice.IPv6=0 --Ice.ThreadInterruptSafe=1 --Ice.Trace.Network=2 --Ice.LogFile=/Users/bernard/builds/ice/java/test/src/main/java/test/Ice/maxConnections/client-010725-1734.log env={'CLASSPATH': '/Users/bernard/builds/ice/java/lib/test.jar'})
testing the creation of 100 connections... com.zeroc.Ice.CloseTimeoutException: Close timed out.
	at com.zeroc.Ice.QueueExecutorService.execute(QueueExecutorService.java:64)
	at com.zeroc.Ice.QueueExecutorService.executeNoThrow(QueueExecutorService.java:28)
	at com.zeroc.Ice.ConnectionI.close(ConnectionI.java:159)
	at test.Ice.maxConnections.AllTests.testCreateConnections(AllTests.java:57)
	at test.Ice.maxConnections.AllTests.allTests(AllTests.java:35)
	at test.Ice.maxConnections.Client.run(Client.java:15)
	at test.TestDriver.main(TestDriver.java:26)
saved /Users/bernard/builds/ice/java/test/src/main/java/test/Ice/maxConnections/client-010725-1734.log
saved /Users/bernard/builds/ice/java/test/src/main/java/test/Ice/maxConnections/server-010725-1734.log
```

It's unfortunate the cprops don't show-up with --debug.
