### ISSUE TITLE
Sometime IceInternal.Outgoing.invoke method ends in infinite loop and creates high cpu utilization

### ISSUE THREAD

**Issue by hansraj2** [zeroc-ice/ice#336]
Our application use case is we use ICE api to commuicate with our upstream for fetching data.

We have 6 threads which are trying to get data for different queries. All these made a async calls to get data as we have mentioned our application timeout for them. All works fine until we have use case when one of thread doesn't get data on time and when another request comes and threads are trying to serve request starts getting in hung state and never returns from ICE calls. Stack trace of these threads.

Can you please help to understand what kind of race condition causing this issue.

"historicalEventQueryService-6@18093" prio=5 tid=0xa2 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	 blocks historicalEventQueryService-5@17972
	  at Ice.ConnectionI.sendRequest(ConnectionI.java:534)
	  - locked <0x45d1> (a Ice.ConnectionI)
	  at IceInternal.Outgoing.invoke(Outgoing.java:72)
	  at Common.Remote.Interfaces._IFXMISRemoteServiceDelM.SubmitRequest(_IFXMISRemoteServiceDelM.java:71)
	  at Common.Remote.Interfaces.IFXMISRemoteServicePrxHelper.SubmitRequest(IFXMISRemoteServicePrxHelper.java:87)
	  at Common.Remote.Interfaces.IFXMISRemoteServicePrxHelper.SubmitRequest(IFXMISRemoteServicePrxHelper.java:61)

"historicalEventQueryService-5@17972" prio=5 tid=0xa1 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 blocks historicalEventQueryService-4@17691
	 blocks historicalEventQueryService-3@18124
	 blocks historicalEventQueryService-1@18113
	 waiting for historicalEventQueryService-6@18093 to release lock on <0x45d1> (a Ice.ConnectionI)
	  at Ice.ConnectionI.isFinished(ConnectionI.java:320)
	  at IceInternal.OutgoingConnectionFactory.create(OutgoingConnectionFactory.java:134)
	  - locked <0x4776> (a IceInternal.OutgoingConnectionFactory)
	  at IceInternal.RoutableReference.createConnection(RoutableReference.java:433)
	  at IceInternal.DirectReference.getConnection(DirectReference.java:199)
	  at Ice._ObjectDelM.setup(_ObjectDelM.java:258)
	  at Ice.ObjectPrxHelperBase.__getDelegate(ObjectPrxHelperBase.java:1055)
	  - locked <0x45d4> (a Common.Remote.Interfaces.IFXMISRemoteServicePrxHelper)
	  at Common.Remote.Interfaces.IFXMISRemoteServicePrxHelper.SubmitRequest(IFXMISRemoteServicePrxHelper.java:85)
	  at Common.Remote.Interfaces.IFXMISRemoteServicePrxHelper.SubmitRequest(IFXMISRemoteServicePrxHelper.java:61)

Submit request method

  private String SubmitRequest(RequestBase request, IResponseListenerPrx listener, Map<String, String> __ctx, boolean __explicitCtx) {
        if(__explicitCtx && __ctx == null) {
            __ctx = _emptyContext;
        }

        int __cnt = 0;

        while(true) {
            _ObjectDel __delBase = null;

            try {
                this.__checkTwowayOnly("SubmitRequest");
                __delBase = this.__getDelegate();
                _IFXMISRemoteServiceDel __del = (_IFXMISRemoteServiceDel)__delBase;
                return __del.SubmitRequest(request, listener, __ctx);
            } catch (LocalExceptionWrapper var8) {
                this.__handleExceptionWrapper(__delBase, var8);
            } catch (LocalException var9) {
                __cnt = this.__handleException(__delBase, var9, __cnt);
            }
        }
    }

**Comment by bentoi** [comment]
Which Ice version do you use and on which platform? Can you provide the full thread dump of the JVM when the hang occurs (attached in a separate text file)?

**Comment by hansraj2** [comment]
"Ice.ThreadPool.Server-0@18212" prio=5 tid=0x86 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(WindowsSelectorImpl.java:-1)
	  at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:273)
	  at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(WindowsSelectorImpl.java:255)
	  at sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:136)
	  at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:69)
	  - locked <0x4785> (a sun.nio.ch.WindowsSelectorImpl)
	  - locked <0x4786> (a java.util.Collections$UnmodifiableSet)
	  - locked <0x4787> (a sun.nio.ch.Util$2)
	  at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:80)
	  at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:84)
	  at IceInternal.ThreadPool.select(ThreadPool.java:1105)
	  at IceInternal.ThreadPool.run(ThreadPool.java:482)
	  at IceInternal.ThreadPool.access$100(ThreadPool.java:12)
	  at IceInternal.ThreadPool$EventHandlerThread.run(ThreadPool.java:1242)

"Ice.ThreadPool.Server-1@18177" prio=5 tid=0xb0 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:485)
	  at IceInternal.ThreadPool.run(ThreadPool.java:896)
	  at IceInternal.ThreadPool.access$100(ThreadPool.java:12)
	  at IceInternal.ThreadPool$EventHandlerThread.run(ThreadPool.java:1242)

"Ice.ThreadPool.Server-2@18166" prio=5 tid=0xbf nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(WindowsSelectorImpl.java:-1)
	  at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:273)
	  at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(WindowsSelectorImpl.java:255)
	  at sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:136)
	  at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:69)
	  - locked <0x4772> (a sun.nio.ch.WindowsSelectorImpl)
	  - locked <0x4773> (a java.util.Collections$UnmodifiableSet)
	  - locked <0x4774> (a sun.nio.ch.Util$2)
	  at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:80)
	  at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:84)
	  at IceInternal.ThreadPool.select(ThreadPool.java:1105)
	  at IceInternal.ThreadPool.run(ThreadPool.java:482)
	  at IceInternal.ThreadPool.access$100(ThreadPool.java:12)
	  at IceInternal.ThreadPool$EventHandlerThread.run(ThreadPool.java:1242)
"Ice.ThreadPool.Server-4@18165" prio=5 tid=0xc2 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:485)
	  at IceInternal.ThreadPool.run(ThreadPool.java:896)
	  at IceInternal.ThreadPool.access$100(ThreadPool.java:12)
	  at IceInternal.ThreadPool$EventHandlerThread.run(ThreadPool.java:1242)


"Ice.ThreadPool.Client-0@18214" prio=5 tid=0x82 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(WindowsSelectorImpl.java:-1)
	  at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:273)
	  at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(WindowsSelectorImpl.java:255)
	  at sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:136)
	  at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:69)
	  - locked <0x4789> (a sun.nio.ch.WindowsSelectorImpl)
	  - locked <0x478a> (a java.util.Collections$UnmodifiableSet)
	  - locked <0x478b> (a sun.nio.ch.Util$2)
	  at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:80)
	  at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:84)
	  at IceInternal.ThreadPool.select(ThreadPool.java:1105)
	  at IceInternal.ThreadPool.run(ThreadPool.java:482)
	  at IceInternal.ThreadPool.access$100(ThreadPool.java:12)
	  at IceInternal.ThreadPool$EventHandlerThread.run(ThreadPool.java:1242)

"Ice.ThreadPool.Client-1@18213" prio=5 tid=0x83 nid=NA waiting
  java.lang.Thread.State: WAITING
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:485)
	  at IceInternal.ThreadPool.run(ThreadPool.java:896)
	  at IceInternal.ThreadPool.access$100(ThreadPool.java:12)
	  at IceInternal.ThreadPool$EventHandlerThread.run(ThreadPool.java:1242)

"historicalEventQueryService-1@18113" prio=5 tid=0x9d nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 waiting for historicalEventQueryService-5@17972 to release lock on <0x45d4> (a abclfm.FX.xyz.Common.Remote.Interfaces.IFXxyzRemoteServicePrxHelper)
	  at Ice.ObjectPrxHelperBase.__handleExceptionWrapper(ObjectPrxHelperBase.java:982)
	  at abclfm.FX.xyz.Common.Remote.Interfaces.IFXxyzRemoteServicePrxHelper.SubmitRequest(IFXxyzRemoteServicePrxHelper.java:91)
	  at abclfm.FX.xyz.Common.Remote.Interfaces.IFXxyzRemoteServicePrxHelper.SubmitRequest(IFXxyzRemoteServicePrxHelper.java:61)
	  at com.abclfm.pelm.dm.query.historical.xyz.xyzConnectionImpl.doAsyncQuery(xyzConnectionImpl.java:303)
	  at com.abclfm.pelm.dm.query.historical.xyz.xyzConnectionImpl.doQuery(xyzConnectionImpl.java:201)
	  at com.abclfm.pelm.dm.query.historical.xyz.xyzEventQueryDAO$1.run(xyzEventQueryDAO.java:105)
	  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	  at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	  at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	  at java.lang.Thread.run(Thread.java:662)

"historicalEventQueryService-2@18191" prio=5 tid=0x9e nid=NA waiting
  java.lang.Thread.State: WAITING
	  at sun.xyzc.Unsafe.park(Unsafe.java:-1)
	  at java.util.concurrent.locks.LockSupport.park(LockSupport.java:156)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1987)
	  at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:399)
	  at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:957)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:917)
	  at java.lang.Thread.run(Thread.java:662)

"historicalEventQueryService-3@18124" prio=5 tid=0x9f nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 waiting for historicalEventQueryService-5@17972 to release lock on <0x45d4> (a abclfm.FX.xyz.Common.Remote.Interfaces.IFXxyzRemoteServicePrxHelper)
	  at Ice.ObjectPrxHelperBase.__handleExceptionWrapper(ObjectPrxHelperBase.java:982)
	  at abclfm.FX.xyz.Common.Remote.Interfaces.IFXxyzRemoteServicePrxHelper.SubmitRequest(IFXxyzRemoteServicePrxHelper.java:91)
	  at abclfm.FX.xyz.Common.Remote.Interfaces.IFXxyzRemoteServicePrxHelper.SubmitRequest(IFXxyzRemoteServicePrxHelper.java:61)
	  at com.abclfm.pelm.dm.query.historical.xyz.xyzConnectionImpl.doAsyncQuery(xyzConnectionImpl.java:303)
	  at com.abclfm.pelm.dm.query.historical.xyz.xyzConnectionImpl.doQuery(xyzConnectionImpl.java:201)
	  at com.abclfm.pelm.dm.query.historical.xyz.xyzEventQueryDAO$1.run(xyzEventQueryDAO.java:105)
	  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	  at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	  at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	  at java.lang.Thread.run(Thread.java:662)

"historicalEventQueryService-4@17691" prio=5 tid=0xa0 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 waiting for historicalEventQueryService-5@17972 to release lock on <0x45d4> (a abclfm.FX.xyz.Common.Remote.Interfaces.IFXxyzRemoteServicePrxHelper)
	  at Ice.ObjectPrxHelperBase.__handleExceptionWrapper(ObjectPrxHelperBase.java:982)
	  at abclfm.FX.xyz.Common.Remote.Interfaces.IFXxyzRemoteServicePrxHelper.SubmitRequest(IFXxyzRemoteServicePrxHelper.java:91)
	  at abclfm.FX.xyz.Common.Remote.Interfaces.IFXxyzRemoteServicePrxHelper.SubmitRequest(IFXxyzRemoteServicePrxHelper.java:61)
	  at com.abclfm.pelm.dm.query.historical.xyz.xyzConnectionImpl.doAsyncQuery(xyzConnectionImpl.java:303)
	  at com.abclfm.pelm.dm.query.historical.xyz.xyzConnectionImpl.doQuery(xyzConnectionImpl.java:201)
	  at com.abclfm.pelm.dm.query.historical.xyz.xyzEventQueryDAO$1.run(xyzEventQueryDAO.java:105)
	  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	  at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	  at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	  at java.lang.Thread.run(Thread.java:662)
"historicalEventQueryService-5@17972" prio=5 tid=0xa1 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 blocks historicalEventQueryService-4@17691
	 blocks historicalEventQueryService-3@18124
	 blocks historicalEventQueryService-1@18113
	 waiting for historicalEventQueryService-6@18093 to release lock on <0x45d1> (a Ice.ConnectionI)
	  at Ice.ConnectionI.isFinished(ConnectionI.java:320)
	  at IceInternal.OutgoingConnectionFactory.create(OutgoingConnectionFactory.java:134)
	  - locked <0x4776> (a IceInternal.OutgoingConnectionFactory)
	  at IceInternal.RoutableReference.createConnection(RoutableReference.java:433)
	  at IceInternal.DirectReference.getConnection(DirectReference.java:199)
	  at Ice._ObjectDelM.setup(_ObjectDelM.java:258)
	  at Ice.ObjectPrxHelperBase.__getDelegate(ObjectPrxHelperBase.java:1055)
	  - locked <0x45d4> (a abclfm.FX.xyz.Common.Remote.Interfaces.IFXxyzRemoteServicePrxHelper)
	  at abclfm.FX.xyz.Common.Remote.Interfaces.IFXxyzRemoteServicePrxHelper.SubmitRequest(IFXxyzRemoteServicePrxHelper.java:85)
	  at abclfm.FX.xyz.Common.Remote.Interfaces.IFXxyzRemoteServicePrxHelper.SubmitRequest(IFXxyzRemoteServicePrxHelper.java:61)
	  at com.abclfm.pelm.dm.query.historical.xyz.xyzConnectionImpl.doAsyncQuery(xyzConnectionImpl.java:303)
	  at com.abclfm.pelm.dm.query.historical.xyz.xyzConnectionImpl.doQuery(xyzConnectionImpl.java:201)
	  at com.abclfm.pelm.dm.query.historical.xyz.xyzEventQueryDAO$1.run(xyzEventQueryDAO.java:105)
	  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	  at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	  at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	  at java.lang.Thread.run(Thread.java:662)
"historicalEventQueryService-6@18093" prio=5 tid=0xa2 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	 blocks historicalEventQueryService-5@17972
	  at Ice.ConnectionI.sendRequest(ConnectionI.java:534)
	  - locked <0x45d1> (a Ice.ConnectionI)
	  at IceInternal.Outgoing.invoke(Outgoing.java:72)
	  at abclfm.FX.xyz.Common.Remote.Interfaces._IFXxyzRemoteServiceDelM.SubmitRequest(_IFXxyzRemoteServiceDelM.java:71)
	  at abclfm.FX.xyz.Common.Remote.Interfaces.IFXxyzRemoteServicePrxHelper.SubmitRequest(IFXxyzRemoteServicePrxHelper.java:87)
	  at abclfm.FX.xyz.Common.Remote.Interfaces.IFXxyzRemoteServicePrxHelper.SubmitRequest(IFXxyzRemoteServicePrxHelper.java:61)
	  at com.abclfm.pelm.dm.query.historical.xyz.xyzConnectionImpl.doAsyncQuery(xyzConnectionImpl.java:303)
	  at com.abclfm.pelm.dm.query.historical.xyz.xyzConnectionImpl.doQuery(xyzConnectionImpl.java:201)
	  at com.abclfm.pelm.dm.query.historical.xyz.xyzEventQueryDAO$1.run(xyzEventQueryDAO.java:105)
	  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	  at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	  at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	  at java.lang.Thread.run(Thread.java:662)

**Comment by hansraj2** [comment]
Let me know if above threads details from dump are good enough for the root cause

**Comment by bentoi** [comment]
Sorry, we can't provide free support for such an old Ice version. Could you try upgrading to the latest version and see if you still have the problem? If you can't easily upgrade, please contact us at info@zeroc.com so that we can discuss commercial support options.

**Comment by hansraj2** [comment]
Before taking any decision for upgrading to latest version, can you just let us know if you see any issue with this older ice api code and causing threads in hung state..

**Comment by bentoi** [comment]
Sorry, I can't see anything obvious from the thread dump. 

It shows that many threads are waiting to acquire a lock which is indirectly held by the last thread. This last thread appears to be in the runnable state and it's about to throw an exception because the Ice connection appears to have been closed and can't send a request. 

It's not clear why it would it hang or go into an infinite loop, this last thread should release the lock after throwing the exception.
