### ISSUE TITLE
IceBox failure testing binary compatibility

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#342]
```
*** [1/1] Running csharp/IceBox/configuration tests ***
[ running client/server #1 test - 01/25/19 22:22:17 ]
- Config: x64,Release
timeout exceeded in match
pattern: "[^\n]+ ready\n"
buffer: "!! 1/25/2019 22:22:17:991 IceBox: error: IceBox.FailureException
       reason = \"ServiceManager: unable to load service \'msbuild\\testservice\\net45\\testservice.dll:TestServiceI\': GetType failed for \'TestServiceI\'\"
      at IceBox.ServiceManagerI.startService(String service, String entryPoint, String[] args) in C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice\\builds\\ice-v141\\csharp\\src\\IceBox\\ServiceManagerI.cs:line 532
      at IceBox.ServiceManagerI.run() in C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice\\builds\\ice-v141\\csharp\\src\\IceBox\\ServiceManagerI.cs:line 381
   Caused by: System.IO.FileNotFoundException: Could not load file or assembly \'IceBox, Version=3.7.1.0, Culture=neutral, PublicKeyToken=0c5ebb72d74932c6\' or one of its dependencies. The system cannot find the file specified.
      at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)
      at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
      at IceBox.ServiceManagerI.startService(String service, String entryPoint, String[] args) in C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice\\builds\\ice-v141\\csharp\\src\\IceBox\\ServiceManagerI.cs:line 527
```

Works if we add binding redirects in `iceboxnet.exe.config`

**Comment by pepone** [comment]
We should redirect both 3.7.1.0 and 3.7.0.0 to 3.7.2.0

**Comment by pepone** [comment]
the exe.config is generated from https://github.com/zeroc-ice/ice/blob/3.7/csharp/msbuild/iceboxnet.exe.config.release

**Comment by pepone** [comment]
8701fe8ed61225997a12f9d20d0553dd8d1ccfc0
