### ISSUE TITLE
SSL interoperability issues between Java and C++ on ArchLinux

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#353]
```
testing batch AMI oneway operations... com.zeroc.Ice.SecurityException
reason = "IceSSL: server did not supply a certificate"
at com.zeroc.IceInternal.OutgoingAsyncBaseI.waitForResponse(OutgoingAsyncBaseI.java:89)
at com.zeroc.Ice._ObjectPrxI.ice_getConnection(_ObjectPrxI.java:320)
at test.Ice.operations.BatchOnewaysAMI.batchOneways(BatchOnewaysAMI.java:106)
at test.Ice.operations.AllTests.allTests(AllTests.java:54)
at test.Ice.operations.Client.run(Client.java:21)
at test.TestDriver.main(TestDriver.java:17)
```

**Comment by pepone** [comment]
Added workaround here f566a00dc37f9c6cd87f88eda43ab6186f90edcc

Seems like JDK 11 bug
