### ISSUE TITLE
Ice/exceptions failures on archlinux

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice#362]
The test is failing with several language mappings based on C++.

```
[ running client/server with 1.0 encoding test - 03/06/19 13:51:33 ]
- Config: tcp,cpp11-shared
(/home/vagrant/workspace/ice/3.7/cpp/test/Ice/exceptions/build/x86_64/cpp11-shared/server --Ice.Default.Host=127.0.0.1 --Test.BasePort=14000 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp --Ice.IPv6=0 --Ice.NullHandleAbort=1 --Ice.PrintStackTraces=1 --Ice.Default.EncodingVersion=1.0 --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 env={'LD_LIBRARY_PATH': '/home/vagrant/workspace/ice/3.7/cpp/lib'})
(/home/vagrant/workspace/ice/3.7/cpp/test/Ice/exceptions/build/x86_64/cpp11-shared/client --Ice.Default.Host=127.0.0.1 --Test.BasePort=14000 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp --Ice.IPv6=0 --Ice.NullHandleAbort=1 --Ice.PrintStackTraces=1 --Ice.Default.EncodingVersion=1.0 env={'LD_LIBRARY_PATH': '/home/vagrant/workspace/ice/3.7/cpp/lib'})
testing ice_print()/what()... ok
testing object adapter registration exceptions... ok
testing servant registration exceptions... ok
testing servant locator registrations exceptions... ok
testing value factory registration exception... ok
testing stringToProxy... ok
testing checked cast... ok
catching exact types... ok
catching base types... ok
catching derived types... ok
catching unknown user exception... ok
testing memory limit marshal exception...src/Ice/ConnectionI.cpp:673: ::Ice::ConnectionTimeoutException:
connection has timed out
failed!
test/Ice/exceptions/AllTests.cpp:995: assertion `false' failed
```

```
[ running client/server with sliced format test - 03/06/19 13:48:41 ]
- Config: tcp,shared,es5
("/usr/bin/python"  /home/vagrant/workspace/ice/3.7/python/test/TestHelper.py Server --Ice.Default.Host=127.0.0.1 --Test.BasePort=14100 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp --Ice.IPv6=0 --Ice.Default.SlicedFormat=1 --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 env={'LD_LIBRARY_PATH': '/home/vagrant/workspace/ice/3.7/cpp/lib', 'PYTHONPATH': '/home/vagrant/workspace/ice/3.7/python/python:/home/vagrant/workspace/ice/3.7/python/test/Ice/exceptions'})
("/usr/bin/python"  /home/vagrant/workspace/ice/3.7/python/test/TestHelper.py Client --Ice.Default.Host=127.0.0.1 --Test.BasePort=14100 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp --Ice.IPv6=0 --Ice.Default.SlicedFormat=1 env={'LD_LIBRARY_PATH': '/home/vagrant/workspace/ice/3.7/cpp/lib', 'PYTHONPATH': '/home/vagrant/workspace/ice/3.7/python/python:/home/vagrant/workspace/ice/3.7/python/test/Ice/exceptions'})
testing servant registration exceptions... ok
testing servant locator registrations exceptions... ok
testing object factory registration exception... ok
testing stringToProxy... ok
testing checked cast... ok
catching exact types... ok
catching base types... ok
catching derived types... ok
catching unknown user exception... ok
testing memory limit marshal exception...Traceback (most recent call last):
  File "/home/vagrant/workspace/ice/3.7/python/test/Ice/exceptions/AllTests.py", line 475, in allTests
    thrower.throwMemoryLimitException(bytearray(20 * 1024)) # 20KB
  File "Test.ice", line 381, in throwMemoryLimitException
Ice.ConnectionTimeoutException: exception ::Ice::ConnectionTimeoutException
{
}
```

**Comment by pepone** [comment]
I cannot reproduce this with current archlinux builds
