### ISSUE TITLE
RHEL8 Ruby crash

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice#432]
```
*** [15/22] Running ruby/Ice/operations tests ***
[ running client/server test - 07/09/19 03:05:20 ]
- Config: aarch64,tcp
(/home/ec2-user/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/cpp/test/Ice/operations/build/aarch64/shared/server --Ice.Default.Host=127.0.0.1 --Test.BasePort=14200 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp --Ice.IPv6=0 --Ice.NullHandleAbort=1 --Ice.PrintStackTraces=1 --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 env={'LD_LIBRARY_PATH': '/usr/lib'})
(ruby /home/ec2-user/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/ruby/test/TestHelper.rb Client --Ice.Default.Host=127.0.0.1 --Test.BasePort=14200 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp --Ice.IPv6=0 env={'RUBYLIB': '/home/ec2-user/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/ruby/test/Ice/operations'})
testing twoway operations...
-! 07/09/19 03:05:21.038 /home/ec2-user/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/cpp/test/Ice/operations/build/aarch64/shared/server: warning: connection exception:
src/Ice/StreamSocket.cpp:243: ::Ice::ConnectionLostException:
connection lost: recv() returned zero
0 IceUtil::Exception::Exception(char const*, int) in /lib64/libIce.so.37
1 Ice::LocalException::LocalException(char const*, int) in /lib64/libIce.so.37
2 Ice::SyscallException::SyscallException(char const*, int, int) in /lib64/libIce.so.37
3 Ice::SocketException::SocketException(char const*, int, int) in /lib64/libIce.so.37
4 Ice::ConnectionLostException::ConnectionLostException(char const*, int, int) in /lib64/libIce.so.37
5 IceInternal::StreamSocket::read(char*, unsigned long) in /lib64/libIce.so.37
6 IceInternal::StreamSocket::read(IceInternal::Buffer&) in /lib64/libIce.so.37
7 /lib64/libIce.so.37(+0x29105c) [0xffff96eb105c]
8 /lib64/libIce.so.37(+0x298554) [0xffff96eb8554]
9 /lib64/libIce.so.37(+0x245f94) [0xffff96e65f94]
10 /lib64/libIce.so.37(+0x2469b4) [0xffff96e669b4]
11 /lib64/libIce.so.37(+0x1a7ae0) [0xffff96dc7ae0]
12 /lib64/libpthread.so.0(+0x77f8) [0xffff969277f8]
13 /lib64/libc.so.6(+0xd157c) [0xffff9687157c]
```

**Comment by bentoi** [comment]
The Ruby client crashes actually:
```
#1  0x00007ffff68f6c95 in abort () from /lib64/libc.so.6
#2  0x00007ffff5bfe708 in std::__replacement_assert (
    __file=__file@entry=0x7ffff5ecbc60 "/usr/include/c++/8/bits/stl_vector.h", 
    __line=__line@entry=932, 
    __function=__function@entry=0x7ffff5ecfda0 <std::vector<short, std::allocator<short> >::operator[](unsigned long)::__PRETTY_FUNCTION__> "std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = short int; _Alloc = std::allocator<short int>; std::vector<_Tp, _Alloc>::refer"..., 
    __condition=__condition@entry=0x7ffff5ecbc30 "__builtin_expect(__n < this->size(), true)") at /usr/include/c++/8/x86_64-redhat-linux/bits/c++config.h:2391
#3  0x00007ffff5bf723f in std::vector<short, std::allocator<short> >::operator[] (
    __n=0, this=<synthetic pointer>) at /usr/include/c++/8/bits/stl_vector.h:930
#4  IceRuby::SequenceInfo::marshalPrimitiveSequence (this=<optimized out>, pi=..., 
    p=<optimized out>, os=0x7fffffffd660) at Types.cpp:1451
#5  0x00007ffff5bf7725 in IceRuby::SequenceInfo::marshal (this=0x555555ac3be0, 
    p=93824997538840, os=0x7fffffffd660, objectMap=0x7fffffffd520, 
    optional=<optimized out>) at Types.cpp:1229
#6  0x00007ffff5bf7834 in IceRuby::SequenceInfo::marshal (this=0x555555cc9400, 
    p=<optimized out>, os=0x7fffffffd660, objectMap=0x7fffffffd520, 
    optional=<optimized out>) at /usr/include/ruby/ruby.h:2076
#7  0x00007ffff5bded10 in IceRuby::OperationI::prepareRequest (this=0x555555d78ae0, 
    proxy=..., args=93824997537840, os=0x7fffffffd660, params=...)
--Type <RET> for more, q to quit, c to continue without paging--
    at ice/cpp/include/IceUtil/Handle.h:30
#8  0x00007ffff5be07a0 in IceRuby::OperationI::invoke (this=this@entry=0x555555d78ae0, 
    proxy=..., args=args@entry=93824997537840, hctx=hctx@entry=8) at Operation.cpp:290
#9  0x00007ffff5be0111 in IceRuby_Operation_invoke (self=<optimized out>, 
    proxy=93825001015360, opArgs=93824997537840, ctx=8) at Operation.cpp:125
#10 0x00007ffff7ac1406 in vm_call_cfunc () from /lib64/libruby.so.2.5
#11 0x00007ffff7ad25cb in vm_call_method () from /lib64/libruby.so.2.5
#12 0x00007ffff7acbd36 in vm_exec_core () from /lib64/libruby.so.2.5
#13 0x00007ffff7acfffe in vm_exec () from /lib64/libruby.so.2.5
#14 0x00007ffff799c29e in ruby_exec_internal () from /lib64/libruby.so.2.5
#15 0x00007ffff799e2a1 in ruby_exec_node () from /lib64/libruby.so.2.5
#16 0x00007ffff79a09f2 in ruby_run_node () from /lib64/libruby.so.2.5
#17 0x0000555555554a4f in main ()
```
