### ISSUE TITLE
TypeError from browser testing causes hang of allTests.py

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice#433]
TypeError raised by the tests are causing `allTests.py` to hang.

```
testing forward declarations... unexpected exception while running test: TypeError: Test.F1 is not a constructor
TypeError: Test.F1 is not a constructor
    at Client.allTests (http://127.0.0.1:8080/test/Ice/objects/Client.js:470:55)
    at async Client.run (http://127.0.0.1:8080/test/Ice/objects/Client.js:502:17)
    at async ProcessI.waitSuccess (http://127.0.0.1:8080/test/Common/ControllerI.js:69:13)
unexpected exception while running test: TypeError: Test.F1 is not a constructor
TypeError: Test.F1 is not a constructor
    at Client.allTests (http://127.0.0.1:8080/test/Ice/objects/Client.js:470:55)
    at async Client.run (http://127.0.0.1:8080/test/Ice/objects/Client.js:502:17)
    at async ProcessI.waitSuccess (http://127.0.0.1:8080/test/Common/ControllerI.js:69:13)
Traceback (most recent call last):
  File "../scripts/Util.py", line 1653, in run
    self.runWithDriver(current)
  File "../scripts/Util.py", line 1682, in runWithDriver
    current.driver.runClientServerTestCase(current)
  File "../scripts/LocalDriver.py", line 565, in runClientServerTestCase
    self.runner.runClientSide(client, current, host)
  File "../scripts/LocalDriver.py", line 197, in runClientSide
    testcase._runClientSide(current, host)
  File "../scripts/Util.py", line 1630, in _runClientSide
    self.runClientSide(current)
  File "../scripts/Util.py", line 1522, in runClientSide
    self._runClient(current, client)
  File "../scripts/Util.py", line 1642, in _runClient
    client.run(current)
  File "../scripts/Util.py", line 1158, in run
    self.stop(current, True, exitstatus)
  File "../scripts/Util.py", line 1230, in stop
    process.waitSuccess(exitstatus=exitstatus, timeout=30)
  File "../scripts/Util.py", line 2088, in waitSuccess
    raise RuntimeError("unexpected exit status: expected: %d, got %d\n" % (exitstatus, result))
RuntimeError: unexpected exit status: expected: 0, got 1
```

or 

```
*** [7/28] Running js/Ice/defaultValue tests ***
[ running client test - 07/10/19 11:22:56 ]
- Config: Chrome
(executing `Ice/defaultValue/Client' on `<selenium.webdriver.chrome.webdriver.WebDriver (session="6c599fae1414157a70ff974829ddebe0")>' args = ['--Ice.Default.Host=127.0.0.1', '--Ice.Warn.Connections=1', '--Ice.IPv6=0', '--Ice.Default.Protocol=ws'])
Traceback (most recent call last):
  File "../scripts/Util.py", line 1653, in run
    self.runWithDriver(current)
  File "../scripts/Util.py", line 1671, in runWithDriver
    current.driver.runTestCase(current)
  File "../scripts/LocalDriver.py", line 617, in runTestCase
    current.testcase._runClientSide(current)
  File "../scripts/Util.py", line 1630, in _runClientSide
    self.runClientSide(current)
  File "../scripts/Util.py", line 1522, in runClientSide
    self._runClient(current, client)
  File "../scripts/Util.py", line 1642, in _runClient
    client.run(current)
  File "../scripts/Util.py", line 1132, in run
    self.start(current, args, props, watchDog=watchDog)
  File "../scripts/Util.py", line 1211, in start
    current.processes[self] = processController.start(self, current, allArgs, allProps, allEnvs, watchDog)
  File "../scripts/Util.py", line 2236, in start
    prx = processController.start(str(current.testsuite), exe, args)
  File "/Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-clang-default/scripts/Controller.ice", line 473, in start
UnknownException: exception ::Ice::UnknownException
{
    unknown = TypeError: Test.Struct1 is not a constructor
TypeError: Test.Struct1 is not a constructor
    at Client.run (http://127.0.0.1:8080/test/Ice/defaultValue/Client.js:19:27)
    at ProcessControllerI.start (http://127.0.0.1:8080/test/Common/ControllerI.js:206:28)
    at dispatchImpl (http://127.0.0.1:8080/lib/Ice.js:14897:36)
    at Function.method (http://127.0.0.1:8080/lib/Ice.js:15023:32)
    at ProcessControllerI.classType._iceDispatch (http://127.0.0.1:8080/lib/Ice.js:15139:31)
    at IncomingAsync.invoke (http://127.0.0.1:8080/lib/Ice.js:15716:51)
    at ConnectionI.invokeAll (http://127.0.0.1:8080/lib/Ice.js:18642:29)
    at ConnectionI.dispatch (http://127.0.0.1:8080/lib/Ice.js:17651:30)
    at ConnectionI.message (http://127.0.0.1:8080/lib/Ice.js:17618:22)
    at WSTransceiver._bytesAvailableCallback (http://127.0.0.1:8080/lib/Ice.js:16873:36)
}
```

**Comment by bentoi** [comment]
I haven't been able to reproduce.
