### ISSUE TITLE
Throwing exceptions from dispatch-interceptors causes UnsupportedEncodingException

### ISSUE THREAD

**Issue by InsertCreativityHere** [zeroc-ice/ice#435]
Throwing an exception in a dispatch interceptor causes an UnsupportedEncodingException to be thrown, at least in Java, probably other languages too. This is because the response's encoding is only set when the Incoming's parameters are read, which doesn't happen until after dispatch interception (when the actual servant receives the dispatch). And so, when Ice tries to marshal the exception thrown by the interceptor, the encoding still isn't set (or rather it's set to the default value of 0.0), and hence the UnsupportedEncodingException.

Throwing any user exceptions before requests are dispatched to actual servants will likely cause this to occur, but dispatch interceptors are probably the easiest example of where this will go wrong.

Below is a stack trace for the UnsupportedEncodingException:
```
-! 7/10/19 11:33:54:408 warning: Ice.ThreadPool.Server-0: connection exception:
   local address = 127.0.0.1:10000
   remote address = 127.0.0.1:50514
   com.zeroc.Ice.UnsupportedEncodingException
       reason = ""
       bad.major = 0
       bad.minor = 0
       supported.major = 1
       supported.minor = 1
        at com.zeroc.IceInternal.Protocol.checkSupportedEncoding(Protocol.java:127)
        at com.zeroc.Ice.OutputStream.startEncapsulation(OutputStream.java:371)
        at com.zeroc.IceInternal.Incoming.handleException(Incoming.java:754)
        at com.zeroc.IceInternal.Incoming.completed(Incoming.java:355)
        at com.zeroc.IceInternal.Incoming.invoke(Incoming.java:256)
        at com.zeroc.Ice.ConnectionI.invokeAll(ConnectionI.java:2706)
        at com.zeroc.Ice.ConnectionI.dispatch(ConnectionI.java:1292)
        at com.zeroc.Ice.ConnectionI.message(ConnectionI.java:1203)
        at com.zeroc.IceInternal.ThreadPool.run(ThreadPool.java:412)
        at com.zeroc.IceInternal.ThreadPool.access$500(ThreadPool.java:7)
        at com.zeroc.IceInternal.ThreadPool$EventHandlerThread.run(ThreadPool.java:781)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by bentoi** [comment]
Good catch. I guess this only occurs when throwing user exceptions because other exceptions don't require the encoding to be set. A simply way to fix this would be to add:
```
if(_current.encoding == null)
{
     _current.encoding = _is.skipEncapsulation();
}
```

in the handleException method before the marshalling of the user exception (around line 772).

**Comment by bernardnormier** [comment]
Still need to fix Swift

**Comment by externl** [comment]
This was not an issue with Swift as the blobject api reads the encoding before dispatching.
