### ISSUE TITLE
Android fails to build

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice#437]
The build of the tests fails with the CI distribution job (mojave VM), looks related to the modules:
```
Skipping task ':mergeDebugAssets' as it is up-to-date.
:mergeDebugAssets (Thread[main,5,main]) completed. Took 0.005 secs.
:transformClassesWithDexBuilderForDebug (Thread[main,5,main]) started.
error processing /Users/vagrant/.gradle/caches/modules-2/files-2.1/com.zeroc/icessl/3.7.2/2ba1f1c3554cf6e80996cea1d6ad41d2cdec4dab/icessl-3.7.2.jar
java.lang.RuntimeException
at org.objectweb.asm.ClassVisitor.visitModule(ClassVisitor.java:148)
at org.objectweb.asm.ClassReader.readModule(ClassReader.java:731)
at org.objectweb.asm.ClassReader.accept(ClassReader.java:632)
at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
at com.android.builder.desugaring.DesugaringClassAnalyzer.analyze(DesugaringClassAnalyzer.java:144)
at com.android.builder.desugaring.DesugaringClassAnalyzer.analyzeJar(DesugaringClassAnalyzer.java:92)
at com.android.builder.desugaring.DesugaringClassAnalyzer.analyze(DesugaringClassAnalyzer.java:63)
at com.android.build.gradle.internal.transforms.DesugarIncrementalTransformHelper.lambda$getInitalGraphData$4(DesugarIncrementalTransformHelper.java:150)
at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by pepone** [comment]
Works after updating android tools and the gradle wrapper used with the builds. Fixed in 4192f6be40be8c17edda3bcb38f6774775e89ec9
