### ISSUE TITLE
Ruby IceSSL load failure on macOS mojave 

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#461]
This is failing with macOS mojave 3.6 CI builds

```*** running tests 74/356 in /Users/vagrant/workspace/ice/3.6/cpp/test/Ice/operations
*** configuration: --cross=ruby --protocol=ssl --compress 
*** test started: 07/23/19 17:29:17
*** using Ice source dist (64bit) 
tests with regular server.
starting server... ok
starting ruby Client.rb ... ok
Ice::PluginInitializationException
/Users/vagrant/workspace/ice/3.6/ruby/test/Ice/operations/Client.rb:51:in `initialize'
/Users/vagrant/workspace/ice/3.6/ruby/test/Ice/operations/Client.rb:51:in `<main>'unexpected exit status: expected: 0, got 1
('test in /Users/vagrant/workspace/ice/3.6/cpp/test/Ice/operations failed with exit status', 1)
sh: line 1: 13427 Terminated: 15          sleep 3
script returned exit code 1```

**Comment by pepone** [comment]
This a problem when using macOS ruby, it works fine with brew ruby binaries, we need to call the methods to register the plug-ins to be able to load them.
