### ISSUE TITLE
IceSSL/configuration timeout failures with iphonesimulator

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#466]
We are getting this failure with 3.7 CI Job

```
*** [35/65] Running cpp/IceSSL/configuration tests ***
[ running client/server test - 07/31/19 19:01:08 ]
- Config: xcodesdk,iphonesimulator
(executing `IceSSL/configuration/server' on `iOS Simulator' args = ['--Ice.Default.Host=127.0.0.1', '--Ice.Warn.Connections=1', '--Ice.IPv6=0', '--Ice.PrintStackTraces=1', '--Ice.ThreadPool.Server.SizeMax=3', '--Ice.ThreadPool.Server.SizeWarn=0', '--Ice.NullHandleAbort=1', '--Ice.Default.Protocol=tcp', '--Ice.ThreadPool.Server.Size=1', '"{testdir}"'])
(executing `IceSSL/configuration/client' on `iOS Simulator' args = ['--Ice.Default.Host=127.0.0.1', '--Ice.Warn.Connections=1', '--Ice.IPv6=0', '--Ice.PrintStackTraces=1', '--Ice.NullHandleAbort=1', '--Ice.Default.Protocol=tcp', '"{testdir}"'])
testing with PKCS12 certificates...
testing manual initialization... ok
testing certificate verification... ok
testing certificate chains... ok
testing custom certificate verifier... ok
testing protocols... ok
testing expired certificates... ok
testing multiple CA certificates... ok
testing DER CA certificate... ok
testing password prompt... ok
testing ciphers... ok
testing IceSSL.TrustOnly... ok
testing IceSSL.TrustOnly.Client... ok
testing IceSSL.TrustOnly.Server... ok
testing IceSSL.TrustOnly.Server.<AdapterName>... ok
testing IceSSL.FindCert... ok
testing system CAs... ok
Traceback (most recent call last):
  File "scripts/Util.py", line 1690, in run
    self.runWithDriver(current)
  File "scripts/Util.py", line 1719, in runWithDriver
    current.driver.runClientServerTestCase(current)
  File "scripts/LocalDriver.py", line 565, in runClientServerTestCase
    self.runner.runClientSide(client, current, host)
  File "scripts/LocalDriver.py", line 197, in runClientSide
    testcase._runClientSide(current, host)
  File "scripts/Util.py", line 1667, in _runClientSide
    self.runClientSide(current)
  File "scripts/Util.py", line 1559, in runClientSide
    self._runClient(current, client)
  File "scripts/Util.py", line 1679, in _runClient
    client.run(current)
  File "scripts/Util.py", line 1180, in run
    process.waitSuccess(exitstatus=exitstatus, timeout=30)
  File "scripts/Util.py", line 2119, in waitSuccess
    result = self.proxy.waitSuccess(timeout)
  File "/Users/vagrant/workspace/ice/3.7/scripts/Controller.ice", line 390, in waitSuccess
ProcessFailedException: exception ::Test::Common::ProcessFailedException
{
    reason = timed out waiting for the process to succeed
}
```

**Comment by pepone** [comment]
This was due to a problem with test script introduce with the merge of Swift branch
Fixed in b67d94a178754391ddd1c09ecb8ab0252f159608
