### ISSUE TITLE
Ruby Ice/slicing/objects CI failure

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice#524]
This occurred on Catalina

```
Running on ice-ci-macos-catalina-dev-3.7
[ running client/server with 1.0 encoding test - 09/10/19 11:15:59 ]
- Config: ssl,ipv6,serialize,compress,mx,shared
(/Users/vagrant/workspace/ice/3.7/cpp/test/Ice/slicing/objects/build/macosx/shared/server --Ice.Plugin.IceSSL=IceSSL:createIceSSL --Ice.Override.Compress=1 --Ice.PrintAdapterReady=1 --IceMX.Metrics.All.GroupBy=none --Ice.Admin.InstanceName=Server --Ice.NullHandleAbort=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.Size=1 --Ice.Warn.Connections=1 --Ice.ThreadPool.Server.SizeWarn=0 --IceSSL.CertFile=server.p12 --Test.BasePort=14000 --Ice.Default.EncodingVersion=1.0 --IceSSL.KeychainPassword=password --IceSSL.DefaultDir=/Users/vagrant/workspace/ice/3.7/certs --Ice.Admin.Endpoints="tcp -h \"::1\"" --Ice.PrintStackTraces=1 --IceSSL.Password=password --IceSSL.Keychain=server.keychain --Ice.ThreadPool.Server.Serialize=1 --Ice.Default.Protocol=ssl --Ice.Default.Host=::1 --Ice.IPv6=1 --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.Debug.GroupBy=id --Ice.PreferIPv6Address=1 --IceSSL.CAs=cacert.pem)
(ruby  /Users/vagrant/workspace/ice/3.7/ruby/test/TestHelper.rb Client --Ice.Default.EncodingVersion=1.0 --Ice.Warn.Connections=1 --Ice.Plugin.IceSSL=IceSSL:createIceSSL --Ice.Override.Compress=1 --IceSSL.Password=password --IceSSL.Keychain=client.keychain --Ice.ThreadPool.Server.Serialize=1 --Ice.Admin.InstanceName=Client --Ice.PreferIPv6Address=1 --Ice.Default.Protocol=ssl --Ice.Default.Host=::1 --IceSSL.KeychainPassword=password --Ice.IPv6=1 --IceMX.Metrics.Parent.GroupBy=parent --IceSSL.CertFile=client.p12 --IceMX.Metrics.Debug.GroupBy=id --IceSSL.DefaultDir=/Users/vagrant/workspace/ice/3.7/certs --Test.BasePort=14000 --IceMX.Metrics.All.GroupBy=none --Ice.Admin.Endpoints="tcp -h \"::1\"" --IceSSL.CAs=cacert.pem env={'DYLD_LIBRARY_PATH': '/Users/vagrant/workspace/ice/3.7/cpp/lib', 'RUBYLIB': '/Users/vagrant/workspace/ice/3.7/ruby/ruby:/Users/vagrant/workspace/ice/3.7/ruby/test/Ice/slicing/objects'})
base as Object... ok
base as base... ok
base with known derived as base... ok
base with known derived as known derived... ok
base with unknown derived as base... ok
unknown with Object as Object... ok
one-element cycle... ok
two-element cycle... ok
known derived pointer slicing as base... ok
known derived pointer slicing as derived... ok
unknown derived pointer slicing as base... ok
param ptr slicing with known first... ok
param ptr slicing with unknown first... ok
return value identity with known first... ok
return value identity with unknown first... ok
return value identity for input params known first... ok
return value identity for input params unknown first... ok
remainder unmarshaling (3 instances)... ok
remainder unmarshaling (4 instances)... ok
param ptr slicing, instance marshaled in unknown derived as base... ok
param ptr slicing, instance marshaled in unknown derived as derived... ok
sequence slicing... ok
dictionary slicing... ok
base exception thrown as base exception... ok
derived exception thrown as base exception... ok
derived exception thrown as derived exception... ok
unknown derived exception thrown as base exception... eval:485: [BUG] Segmentation fault at 0x0000000000000000
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]

-- Crash Report log information --------------------------------------------
   See Crash Report log file under the one of following:
     * ~/Library/Logs/DiagnosticReports
     * /Library/Logs/DiagnosticReports
   for more details.
Don't forget to include the above Crash Report log file in bug reports.

-- Control frame information -----------------------------------------------
c:0009 p:---- s:0090 e:000089 CFUNC  :invoke
c:0008 p:0020 s:0083 e:000082 METHOD eval:485
c:0007 p:4230 s:0078 e:000077 METHOD /Users/vagrant/workspace/ice/3.7/ruby/test/Ice/slicing/objects/AllTests.rb:653
c:0006 p:0008 s:0033 e:000032 BLOCK  /Users/vagrant/workspace/ice/3.7/ruby/test/Ice/slicing/objects/Client.rb:11
c:0005 p:0090 s:0028 e:000027 METHOD /Users/vagrant/workspace/ice/3.7/ruby/test/TestHelper.rb:69
c:0004 p:0007 s:0019 e:000018 METHOD /Users/vagrant/workspace/ice/3.7/ruby/test/Ice/slicing/objects/Client.rb:10
c:0003 p:0069 s:0014 e:000013 METHOD /Users/vagrant/workspace/ice/3.7/ruby/test/TestHelper.rb:91
c:0002 p:0035 s:0006 e:000005 EVAL   /Users/vagrant/workspace/ice/3.7/ruby/test/TestHelper.rb:107 [FINISH]
c:0001 p:0000 s:0003 E:001b20 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/Users/vagrant/workspace/ice/3.7/ruby/test/TestHelper.rb:107:in `<main>'
/Users/vagrant/workspace/ice/3.7/ruby/test/TestHelper.rb:91:in `run'
/Users/vagrant/workspace/ice/3.7/ruby/test/Ice/slicing/objects/Client.rb:10:in `run'
/Users/vagrant/workspace/ice/3.7/ruby/test/TestHelper.rb:69:in `init'
/Users/vagrant/workspace/ice/3.7/ruby/test/Ice/slicing/objects/Client.rb:11:in `block in run'
/Users/vagrant/workspace/ice/3.7/ruby/test/Ice/slicing/objects/AllTests.rb:653:in `allTests'
eval:485:in `throwUnknownDerivedAsBase'
eval:485:in `invoke'
```

**Comment by pepone** [comment]
thread dump from the crash report

```

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff6c0b744e __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff6c174707 pthread_kill + 384
2   libsystem_c.dylib             	0x00007fff6c03f9cc abort + 120
3   libruby.2.6.dylib             	0x00007fff409b7bce 0x7fff40960000 + 359374
4   libruby.2.6.dylib             	0x00007fff409b7ca9 rb_bug_context + 219
5   libruby.2.6.dylib             	0x00007fff40a77329 0x7fff40960000 + 1143593
6   libsystem_platform.dylib      	0x00007fff6c169b1d _sigtramp + 29
7   ???                           	0x000000000016910c 0 + 1478924
8   libruby.2.6.dylib             	0x00007fff40abb863 rb_ivar_set + 244
9   IceRuby.bundle                	0x000000010cbd01e4 IceRuby::RF_3<unsigned long (*)(unsigned long, unsigned long, unsigned long), unsigned long, unsigned long, unsigned long>::operator()() + 36 (Util.h:266)
10  IceRuby.bundle                	0x000000010cbd0175 IceRuby::RF_3<unsigned long (*)(unsigned long, unsigned long, unsigned long), unsigned long, unsigned long, unsigned long>::call(unsigned long) + 21 (Util.h:269)
11  libruby.2.6.dylib             	0x00007fff409be5c5 rb_protect + 345
12  IceRuby.bundle                	0x000000010cc64a68 IceRuby::callProtected(unsigned long (*)(unsigned long), unsigned long) + 40 (Util.cpp:564)
13  IceRuby.bundle                	0x000000010cbc5591 unsigned long IceRuby::callRuby<unsigned long (*)(unsigned long, unsigned long, unsigned long), unsigned long, unsigned long, unsigned long>(unsigned long (*)(unsigned long, unsigned long, unsigned long), unsigned long, unsigned long, unsigned long) + 65 (Util.h:285)
14  IceRuby.bundle                	0x000000010cc248a7 IceRuby::DataMember::unmarshaled(unsigned long, unsigned long, void*) + 55 (Types.cpp:873)
15  IceRuby.bundle                	0x000000010cc32099 IceRuby::ReadObjectCallback::invoke(IceInternal::Handle<Ice::Object> const&) + 1033 (Types.cpp:2748)
16  IceRuby.bundle                	0x000000010cc2ced0 (anonymous namespace)::patchObject(void*, IceInternal::Handle<Ice::Object> const&) + 96 (Types.cpp:2115)
17  libIce.37.dylib               	0x000000010d28534b Ice::InputStream::EncapsDecoder::unmarshal(int, IceInternal::Handle<Ice::Object> const&) + 619 (InputStream.cpp:1883)
18  libIce.37.dylib               	0x000000010d286d57 Ice::InputStream::EncapsDecoder10::readInstance() + 1831 (InputStream.cpp:2230)
19  libIce.37.dylib               	0x000000010d28651d Ice::InputStream::EncapsDecoder10::readPendingValues() + 61 (InputStream.cpp:2129)
20  libIce.37.dylib               	0x000000010d285dcc Ice::InputStream::EncapsDecoder10::throwException(IceUtil::Handle<Ice::UserExceptionFactory> const&) + 588 (InputStream.cpp:2008)
21  libIce.37.dylib               	0x000000010d282506 Ice::InputStream::throwException(IceUtil::Handle<Ice::UserExceptionFactory> const&) + 54 (InputStream.cpp:1395)
22  IceRuby.bundle                	0x000000010cbea4ae IceRuby::OperationI::unmarshalException(std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&, IceInternal::Handle<Ice::Communicator> const&) + 398 (Operation.cpp:575)
23  IceRuby.bundle                	0x000000010cbe9297 IceRuby::OperationI::invoke(IceInternal::ProxyHandle<IceProxy::Ice::Object> const&, unsigned long, unsigned long) + 967 (Operation.cpp:331)
24  IceRuby.bundle                	0x000000010cbe65b5 IceRuby_Operation_invoke + 373 (Operation.cpp:125)
25  libruby.2.6.dylib             	0x00007fff40ad378b 0x7fff40960000 + 1521547
26  libruby.2.6.dylib             	0x00007fff40ac26f7 0x7fff40960000 + 1451767
27  libruby.2.6.dylib             	0x00007fff40ad00bd rb_vm_exec + 1853
28  libruby.2.6.dylib             	0x00007fff409bdd58 0x7fff40960000 + 384344
29  libruby.2.6.dylib             	0x00007fff409bdc59 ruby_run_node + 57
30  ruby                          	0x000000010a452447 main + 98
31  libdyld.dylib                 	0x00007fff6bf682f5 start + 1

Thread 1:
0   libsystem_kernel.dylib        	0x00007fff6c0b9572 poll + 10
1   libruby.2.6.dylib             	0x00007fff40aa68bc 0x7fff40960000 + 1337532
2   libsystem_pthread.dylib       	0x00007fff6c174d76 _pthread_start + 125
3   libsystem_pthread.dylib       	0x00007fff6c1715ef thread_start + 15

Thread 2:
0   libsystem_kernel.dylib        	0x00007fff6c0b48c6 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff6c175082 _pthread_cond_wait + 701
2   libIceLocatorDiscovery.37.dylib	0x000000010c7bfe1c bool IceUtil::Cond::timedWaitImpl<IceUtil::Mutex>(IceUtil::Mutex const&, IceUtil::Time const&) const + 284 (Cond.h:295)
3   libIce.37.dylib               	0x000000010d4f7b95 IceUtil::Monitor<IceUtil::Mutex>::timedWait(IceUtil::Time const&) const + 69 (Monitor.h:175)
4   libIce.37.dylib               	0x000000010d501be0 IceUtil::Timer::run() + 1568 (Timer.cpp:197)
5   libIce.37.dylib               	0x000000010d4efc43 startHook(void*) + 131 (Thread.cpp:653)
6   libsystem_pthread.dylib       	0x00007fff6c174d76 _pthread_start + 125
7   libsystem_pthread.dylib       	0x00007fff6c1715ef thread_start + 15

Thread 3:
0   libsystem_kernel.dylib        	0x00007fff6c0b48c6 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff6c175082 _pthread_cond_wait + 701
2   libIce.37.dylib               	0x000000010d19cc05 void IceUtil::Cond::waitImpl<IceUtil::Mutex>(IceUtil::Mutex const&) const + 53 (Cond.h:260)
3   libIce.37.dylib               	0x000000010d1980d8 IceUtil::Monitor<IceUtil::Mutex>::wait() const + 56 (Monitor.h:147)
4   libIce.37.dylib               	0x000000010d2502f5 IceInternal::EndpointHostResolver::run() + 181 (IPEndpointI.cpp:610)
5   libIce.37.dylib               	0x000000010d4efc43 startHook(void*) + 131 (Thread.cpp:653)
6   libsystem_pthread.dylib       	0x00007fff6c174d76 _pthread_start + 125
7   libsystem_pthread.dylib       	0x00007fff6c1715ef thread_start + 15

Thread 4:
0   libsystem_kernel.dylib        	0x00007fff6c0b793e kevent + 10
1   libIce.37.dylib               	0x000000010d4ba382 IceInternal::Selector::select(int) + 402 (Selector.cpp:736)
2   libIce.37.dylib               	0x000000010d4f5880 IceInternal::ThreadPool::run(IceUtil::Handle<IceInternal::ThreadPool::EventHandlerThread> const&) + 1616 (ThreadPool.cpp:702)
3   libIce.37.dylib               	0x000000010d4f8431 IceInternal::ThreadPool::EventHandlerThread::run() + 1073 (ThreadPool.cpp:1267)
4   libIce.37.dylib               	0x000000010d4efc43 startHook(void*) + 131 (Thread.cpp:653)
5   libsystem_pthread.dylib       	0x00007fff6c174d76 _pthread_start + 125
6   libsystem_pthread.dylib       	0x00007fff6c1715ef thread_start + 15

Thread 5:
0   libsystem_pthread.dylib       	0x00007fff6c1715cc start_wqthread + 0

Thread 6:
0   libsystem_pthread.dylib       	0x00007fff6c1715cc start_wqthread + 0

Thread 7:
0   libsystem_kernel.dylib        	0x00007fff6c0b793e kevent + 10
1   libIce.37.dylib               	0x000000010d4ba382 IceInternal::Selector::select(int) + 402 (Selector.cpp:736)
2   libIce.37.dylib               	0x000000010d4f5880 IceInternal::ThreadPool::run(IceUtil::Handle<IceInternal::ThreadPool::EventHandlerThread> const&) + 1616 (ThreadPool.cpp:702)
3   libIce.37.dylib               	0x000000010d4f8431 IceInternal::ThreadPool::EventHandlerThread::run() + 1073 (ThreadPool.cpp:1267)
4   libIce.37.dylib               	0x000000010d4efc43 startHook(void*) + 131 (Thread.cpp:653)
5   libsystem_pthread.dylib       	0x00007fff6c174d76 _pthread_start + 125
6   libsystem_pthread.dylib       	0x00007fff6c1715ef thread_start + 15

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x000000010f4e8d40  rcx: 0x00007fb53e0c7cf8  rdx: 0x0000000000000000
  rdi: 0x0000000000000603  rsi: 0x0000000000000006  rbp: 0x00007fb53e0c7d20  rsp: 0x00007fb53e0c7cf8
   r8: 0x00000000000130a8   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000246
  r12: 0x0000000000000603  r13: 0x00007ffee57ace70  r14: 0x0000000000000006  r15: 0x0000000000000016
  rip: 0x00007fff6c0b744e  rfl: 0x0000000000000246  cr2: 0x00007fff40ae4b98
```

**Comment by bentoi** [comment]
I can't reproduce this anymore with the latest version of Catalina.
