### ISSUE TITLE
js Ice/adapterDeactivation 

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#534]
I get this failure with Chrome on Android

```
*** [4/54] Running js/Ice/adapterDeactivation tests ***
[ running client/server test - 09/18/19 19:52:30 ]
- Config: Manual,x64
(D:\3.7\ice3.7\cpp\test\Ice\adapterDeactivation\msbuild\server\x64\Release\server.exe --Ice.Default.Host=192.168.1.5 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ws --Ice.IPv6=0 --Ice.NullHandleAbort=1 --Ice.PrintStackTraces=1 --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 env={'PATH': 'D:\\3.7\\ice3.7\\cpp\\test\\Common\\msbuild\\x64\\Release;D:\\3.7\\ice3.7\\cpp\\msbuild\\packages\\zeroc.ice.v142.3.7.3\\build\\native\\bin\\x64\\Release'})
(executing `Ice/adapterDeactivation/Client' on `Manual' args = ['--Ice.Default.Host=192.168.1.5', '--Ice.Warn.Connections=1', '--Ice.Default.Protocol=ws', '--Ice.IPv6=0'])
testing stringToProxy... ok
testing checked cast... ok
creating/destroying/recreating object adapter... ok
creating/activating/deactivating object adapter in one operation... ok
testing connection closure... ok
testing object adapter published endpoints... ok
testing object adapter with bi-dir connection... ok
testing object adapter with router... unexpected exception while running test: Error: test failed
Error: test failed
    at test (http://192.168.1.5:8080/test/Common/TestHelper.js:175:23)
    at Client.allTests (http://192.168.1.5:8080/test/Ice/adapterDeactivation/Client.js:159:21)
unexpected exception while running test: Error: test failed
Error: test failed
    at test (http://192.168.1.5:8080/test/Common/TestHelper.js:175:23)
    at Client.allTests (http://192.168.1.5:8080/test/Ice/adapterDeactivation/Client.js:159:21)
!! 09/18/19 19:54:38.530 error: communicator not destroyed during global destruction.Traceback (most recent call last):
  File "..\scripts\Util.py", line 1193, in run
    process.waitSuccess(exitstatus=exitstatus, timeout=30)
  File "..\scripts\Util.py", line 2139, in waitSuccess
    raise RuntimeError("unexpected exit status: expected: %d, got %d\n" % (exitstatus, result))
RuntimeError: unexpected exit status: expected: 0, got 1
```

**Comment by pepone** [comment]
The test is failing with `Ice.ConnectTimeoutException` instead of the expected `Ice.ConnectFailedException`

```
Error
    at Function.captureStackTrace (http://192.168.1.5:8080/lib/Ice.js:1029:31)
    at new LocalException (http://192.168.1.5:8080/lib/Ice.js:1056:27)
    at new Ice.TimeoutException (http://192.168.1.5:8080/lib/Ice.js:5039:21)
    at new Ice.ConnectTimeoutException (http://192.168.1.5:8080/lib/Ice.js:5061:21)
    at ConnectionI.timedOut (http://192.168.1.5:8080/lib/Ice.js:17852:48)
    at Object.callback (http://192.168.1.5:8080/lib/Ice.js:18737:76)
    at Timer.handleTimeout (http://192.168.1.5:8080/lib/Ice.js:5857:31)
    at http://192.168.1.5:8080/lib/Ice.js:5801:56
    at Worker.onmessage (http://192.168.1.5:8080/lib/Ice.js:4033:24)
```
