### ISSUE TITLE
IceGrid/admin failure

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#546]
```
*** [71/91] Running cpp/IceGrid/admin tests ***
[ running IceGrid test - 09/23/19 01:42:38 ]
- Config: arm64,tcp
starting IceGrid registry Master... (/usr/bin/icegridregistry --Ice.PrintAdapterReady=1 --IceGrid.Registry.Client.Endpoints="default -p 14320" --IceGrid.InstanceName=TestIceGrid --IceGrid.Registry.LMDB.Path=/home/ubuntu/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/cpp/test/IceGrid/admin/registry-Master --IceGrid.Registry.AdminSSLPermissionsVerifier=TestIceGrid/NullSSLPermissionsVerifier --Ice.NullHandleAbort=1 --Ice.Warn.Connections=0 --IceGrid.Registry.SessionTimeout=60 --IceGrid.Registry.Server.Endpoints=default --IceGrid.Registry.Discovery.Port=14399 --Ice.PrintStackTraces=1 --IceGrid.Registry.SessionManager.Endpoints=default --IceGrid.Registry.SSLPermissionsVerifier=TestIceGrid/NullSSLPermissionsVerifier --IceGrid.Registry.AdminPermissionsVerifier=TestIceGrid/NullPermissionsVerifier --IceGrid.Registry.LMDB.MapSize=1 --IceGrid.Registry.PermissionsVerifier=TestIceGrid/NullPermissionsVerifier --IceGrid.Registry.Client.ThreadPool.SizeWarn=0 --Ice.Default.Protocol=tcp --Ice.Default.Host=127.0.0.1 --Ice.IPv6=0 --Ice.ProgramName=Master --IceGrid.Registry.Internal.Endpoints=default --IceGrid.Registry.AdminSessionManager.Endpoints=default --Ice.ThreadPool.Client.SizeWarn=0 --IceGrid.Registry.ReplicaName=Master --IceGrid.Registry.DefaultTemplates="/home/ubuntu/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/cpp/config/templates.xml" env={'LD_LIBRARY_PATH': '/usr/lib/aarch64-linux-gnu'})
ok
starting IceGrid registry Slave1... (/usr/bin/icegridregistry --Ice.PrintAdapterReady=1 --IceGrid.Registry.Client.Endpoints="default -p 14321" --IceGrid.InstanceName=TestIceGrid --IceGrid.Registry.LMDB.Path=/home/ubuntu/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/cpp/test/IceGrid/admin/registry-Slave1 --IceGrid.Registry.AdminSSLPermissionsVerifier=TestIceGrid/NullSSLPermissionsVerifier --Ice.NullHandleAbort=1 --Ice.Default.Locator="TestIceGrid/Locator:default -p 14320" --Ice.Warn.Connections=0 --IceGrid.Registry.SessionTimeout=60 --IceGrid.Registry.Server.Endpoints=default --IceGrid.Registry.Discovery.Port=14399 --Ice.PrintStackTraces=1 --IceGrid.Registry.SessionManager.Endpoints=default --IceGrid.Registry.SSLPermissionsVerifier=TestIceGrid/NullSSLPermissionsVerifier --IceGrid.Registry.AdminPermissionsVerifier=TestIceGrid/NullPermissionsVerifier --IceGrid.Registry.LMDB.MapSize=1 --IceGrid.Registry.PermissionsVerifier=TestIceGrid/NullPermissionsVerifier --IceGrid.Registry.Client.ThreadPool.SizeWarn=0 --Ice.Default.Protocol=tcp --Ice.Default.Host=127.0.0.1 --Ice.IPv6=0 --Ice.ProgramName=Slave1 --IceGrid.Registry.Internal.Endpoints=default --IceGrid.Registry.AdminSessionManager.Endpoints=default --Ice.ThreadPool.Client.SizeWarn=0 --IceGrid.Registry.DefaultTemplates="/home/ubuntu/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/cpp/config/templates.xml" --IceGrid.Registry.ReplicaName=Slave1 env={'LD_LIBRARY_PATH': '/usr/lib/aarch64-linux-gnu'})
ok
starting IceGrid node localnode... (/usr/bin/icegridnode --IceGrid.Node.ThreadPool.SizeWarn=0 --IceGrid.InstanceName=TestIceGrid --IceGrid.Node.Trace.Replica=0 --Ice.NullHandleAbort=1 --IceGrid.Node.Trace.Server=0 --Ice.Default.Locator="TestIceGrid/Locator:default -p 14320:default -p 14321" --Ice.Warn.Connections=1 --IceGrid.Node.Trace.Adapter=0 --IceGrid.Node.Endpoints=default --IceGrid.Node.PropertiesOverride="Ice.Warn.Connections=1 Ice.PrintAdapterReady=1 Ice.NullHandleAbort=1 Ice.Default.Protocol=tcp Ice.ThreadPool.Server.Size=1 Ice.Default.Host=127.0.0.1 Ice.IPv6=0 Ice.ThreadPool.Server.SizeMax=3 Test.BasePort=14300 Ice.PrintStackTraces=1 Ice.ThreadPool.Server.SizeWarn=0" --IceGrid.Node.Trace.Activator=0 --Ice.PrintStackTraces=1 --IceGrid.Node.Data=/home/ubuntu/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/cpp/test/IceGrid/admin/node-localnode --IceGrid.Node.Name=localnode --IceGrid.Node.WaitTime=240 --Ice.Default.Protocol=tcp --Ice.Default.Host=127.0.0.1 --Ice.IPv6=0 --Ice.ProgramName=icegridnode --IceGrid.Node.PrintServersReady=node env={'LD_LIBRARY_PATH': '/usr/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu'})
ok
starting Glacier2 router... (/usr/bin/glacier2router --Glacier2.PermissionsVerifier=Glacier2/NullPermissionsVerifier --Ice.PrintAdapterReady=1 --Ice.Admin.InstanceName=Glacier2 --Glacier2.Server.Endpoints=tcp --Ice.NullHandleAbort=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.Size=1 --Ice.Warn.Connections=1 --Ice.ThreadPool.Server.SizeWarn=0 --Glacier2.SessionManager=TestIceGrid/AdminSessionManager --Ice.Default.Locator="TestIceGrid/Locator:default -p 14320:default -p 14321" --Ice.Admin.Endpoints="default -p 14351" --Ice.PrintStackTraces=1 --Glacier2.SSLPermissionsVerifier=Glacier2/NullSSLPermissionsVerifier --Glacier2.SessionTimeout=5 --Glacier2.SSLSessionManager=TestIceGrid/AdminSSLSessionManager --Ice.Default.Protocol=tcp --Glacier2.Client.Endpoints="default -p 14350" --Ice.Default.Host=127.0.0.1 --Ice.IPv6=0 --Glacier2.CryptPasswords=/home/ubuntu/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/cpp/test/IceGrid/admin/passwords --IceSSL.VerifyPeer=1 env={'LD_LIBRARY_PATH': '/usr/lib/aarch64-linux-gnu'})
ok
testing login with username/password... (/usr/bin/icegridadmin --Ice.Default.Host=127.0.0.1 --Ice.Warn.Connections=1 --Ice.IPv6=0 --Ice.PrintStackTraces=1 --IceGridAdmin.Username=admin1 --IceGridAdmin.Password=test1 --Ice.NullHandleAbort=1 --Ice.Default.Protocol=tcp --Ice.Default.Locator="TestIceGrid/Locator:default -p 14320" env={'LD_LIBRARY_PATH': '/usr/lib/aarch64-linux-gnu'})
(/usr/bin/icegridadmin --Ice.Default.Host=127.0.0.1 --Ice.Warn.Connections=1 --Ice.IPv6=0 --Ice.PrintStackTraces=1 --IceGridAdmin.Username=admin1 --IceGridAdmin.Password=test1 --Ice.Default.Router="Glacier2/router:default -p 14350" --Ice.NullHandleAbort=1 --Ice.Default.Protocol=tcp --Ice.Default.Locator="TestIceGrid/Locator:default -p 14320" env={'LD_LIBRARY_PATH': '/usr/lib/aarch64-linux-gnu'})
ok
testing commands... (/usr/bin/icegridadmin --Ice.Default.Host=127.0.0.1 --Ice.Warn.Connections=1 --Ice.IPv6=0 --Ice.PrintStackTraces=1 --IceGridAdmin.Username=admin1 --IceGridAdmin.Password=test1 --Ice.NullHandleAbort=1 --Ice.Default.Protocol=tcp --Ice.Default.Locator="TestIceGrid/Locator:default -p 14320" env={'LD_LIBRARY_PATH': '/usr/lib/aarch64-linux-gnu'})
ok
(/usr/bin/icegridadmin --Ice.Default.Host=127.0.0.1 --Ice.Warn.Connections=1 --Ice.IPv6=0 --Ice.PrintStackTraces=1 --IceGridAdmin.Username=admin1 --IceGridAdmin.Password=test1 --Ice.NullHandleAbort=1 --Ice.Default.Protocol=tcp --Ice.Default.Locator="TestIceGrid/Locator:default -p 14320" -r Master -e "node shutdown localnode" env={'LD_LIBRARY_PATH': '/usr/lib/aarch64-linux-gnu'})
(/usr/bin/icegridadmin --Ice.Default.Host=127.0.0.1 --Ice.Warn.Connections=1 --Ice.IPv6=0 --Ice.PrintStackTraces=1 --IceGridAdmin.Username=admin1 --IceGridAdmin.Password=test1 --Ice.NullHandleAbort=1 --Ice.Default.Protocol=tcp --Ice.Default.Locator="TestIceGrid/Locator:default -p 14320" -r Master -e "registry shutdown Master" env={'LD_LIBRARY_PATH': '/usr/lib/aarch64-linux-gnu'})
(/usr/bin/icegridadmin --Ice.Default.Host=127.0.0.1 --Ice.Warn.Connections=1 --Ice.IPv6=0 --Ice.PrintStackTraces=1 --IceGridAdmin.Username=admin1 --IceGridAdmin.Password=test1 --Ice.NullHandleAbort=1 --Ice.Default.Protocol=tcp --Ice.Default.Locator="TestIceGrid/Locator:default -p 14321" -r Slave1 -e "registry shutdown Slave1" env={'LD_LIBRARY_PATH': '/usr/lib/aarch64-linux-gnu'})
[ running IceGrid test - 09/23/19 01:42:41 ]
- Config: arm64,wss,serialize,compress,mx,ipv6
starting IceGrid registry Master... (/usr/bin/icegridregistry --Ice.Plugin.IceSSL=IceSSL:createIceSSL --Ice.Override.Compress=1 --IceGrid.Registry.Client.Endpoints="default -p 14320" --IceMX.Metrics.All.GroupBy=none --IceGrid.Registry.AdminSSLPermissionsVerifier=TestIceGrid/NullSSLPermissionsVerifier --Ice.Warn.Connections=0 --IceGrid.Registry.Discovery.Port=14399 --IceGrid.Registry.SSLPermissionsVerifier=TestIceGrid/NullSSLPermissionsVerifier --IceGrid.Registry.LMDB.MapSize=1 --Ice.ThreadPool.Server.Serialize=1 --IceGrid.Registry.Client.ThreadPool.SizeWarn=0 --Ice.Default.Host=::1 --Ice.IPv6=1 --IceMX.Metrics.Parent.GroupBy=parent --Ice.ProgramName=Master --IceGrid.Registry.Internal.Endpoints=default --IceMX.Metrics.Debug.GroupBy=id --IceGrid.Registry.AdminSessionManager.Endpoints=default --Ice.PreferIPv6Address=1 --IceGrid.Registry.PermissionsVerifier=TestIceGrid/NullPermissionsVerifier --IceGrid.Registry.LMDB.Path=/home/ubuntu/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/cpp/test/IceGrid/admin/registry-Master --IceGrid.Registry.ReplicaName=Master --Ice.PrintAdapterReady=1 --IceGrid.InstanceName=TestIceGrid --Ice.Admin.InstanceName=Server --Ice.NullHandleAbort=1 --IceGrid.Registry.SessionTimeout=60 --IceSSL.CertFile=server.p12 --IceGrid.Registry.Server.Endpoints=default --IceSSL.DefaultDir=/home/ubuntu/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/certs --Ice.Admin.Endpoints="tcp -h \"::1\"" --Ice.PrintStackTraces=1 --IceGrid.Registry.SessionManager.Endpoints=default --IceSSL.Password=password --IceGrid.Registry.AdminPermissionsVerifier=TestIceGrid/NullPermissionsVerifier --Ice.Default.Protocol=wss --Ice.ThreadPool.Client.SizeWarn=0 --IceSSL.CAs=cacert.pem --IceGrid.Registry.DefaultTemplates="/home/ubuntu/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/cpp/config/templates.xml" env={'LD_LIBRARY_PATH': '/usr/lib/aarch64-linux-gnu'})
ok
starting IceGrid registry Slave1... (/usr/bin/icegridregistry --Ice.Plugin.IceSSL=IceSSL:createIceSSL --Ice.Override.Compress=1 --IceGrid.Registry.Client.Endpoints="default -p 14321" --IceMX.Metrics.All.GroupBy=none --IceGrid.Registry.AdminSSLPermissionsVerifier=TestIceGrid/NullSSLPermissionsVerifier --Ice.Default.Locator="TestIceGrid/Locator:default -p 14320" --Ice.Warn.Connections=0 --IceGrid.Registry.Discovery.Port=14399 --IceGrid.Registry.SSLPermissionsVerifier=TestIceGrid/NullSSLPermissionsVerifier --IceGrid.Registry.LMDB.MapSize=1 --Ice.ThreadPool.Server.Serialize=1 --IceGrid.Registry.Client.ThreadPool.SizeWarn=0 --Ice.Default.Host=::1 --Ice.IPv6=1 --IceMX.Metrics.Parent.GroupBy=parent --Ice.ProgramName=Slave1 --IceGrid.Registry.Internal.Endpoints=default --IceMX.Metrics.Debug.GroupBy=id --IceGrid.Registry.AdminSessionManager.Endpoints=default --Ice.PreferIPv6Address=1 --IceGrid.Registry.PermissionsVerifier=TestIceGrid/NullPermissionsVerifier --IceGrid.Registry.LMDB.Path=/home/ubuntu/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/cpp/test/IceGrid/admin/registry-Slave1 --IceGrid.Registry.ReplicaName=Slave1 --Ice.PrintAdapterReady=1 --IceGrid.InstanceName=TestIceGrid --Ice.Admin.InstanceName=Server --Ice.NullHandleAbort=1 --IceGrid.Registry.SessionTimeout=60 --IceSSL.CertFile=server.p12 --IceGrid.Registry.Server.Endpoints=default --IceSSL.DefaultDir=/home/ubuntu/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/certs --Ice.Admin.Endpoints="tcp -h \"::1\"" --Ice.PrintStackTraces=1 --IceGrid.Registry.SessionManager.Endpoints=default --IceSSL.Password=password --IceGrid.Registry.AdminPermissionsVerifier=TestIceGrid/NullPermissionsVerifier --Ice.Default.Protocol=wss --Ice.ThreadPool.Client.SizeWarn=0 --IceSSL.CAs=cacert.pem --IceGrid.Registry.DefaultTemplates="/home/ubuntu/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/cpp/config/templates.xml" env={'LD_LIBRARY_PATH': '/usr/lib/aarch64-linux-gnu'})
ok
starting IceGrid node localnode... (/usr/bin/icegridnode --Ice.Plugin.IceSSL=IceSSL:createIceSSL --Ice.Override.Compress=1 --IceGrid.Node.ThreadPool.SizeWarn=0 --IceMX.Metrics.All.GroupBy=none --Ice.Default.Locator="TestIceGrid/Locator:default -p 14320:default -p 14321" --Ice.Warn.Connections=1 --IceGrid.Node.Trace.Activator=0 --Ice.ThreadPool.Server.Serialize=1 --Ice.Default.Host=::1 --Ice.IPv6=1 --IceMX.Metrics.Parent.GroupBy=parent --Ice.ProgramName=icegridnode --IceMX.Metrics.Debug.GroupBy=id --Ice.PreferIPv6Address=1 --IceGrid.Node.PrintServersReady=node --IceGrid.InstanceName=TestIceGrid --Ice.Admin.InstanceName=Server --IceGrid.Node.Trace.Replica=0 --Ice.NullHandleAbort=1 --IceGrid.Node.Trace.Server=0 --IceGrid.Node.Trace.Adapter=0 --IceGrid.Node.Endpoints=default --IceSSL.CertFile=server.p12 --IceGrid.Node.PropertiesOverride="Ice.Plugin.IceSSL=IceSSL:createIceSSL Ice.Override.Compress=1 Ice.PrintAdapterReady=1 IceMX.Metrics.All.GroupBy=none Ice.Admin.InstanceName=Server Ice.NullHandleAbort=1 Ice.ThreadPool.Server.SizeMax=3 Ice.ThreadPool.Server.Size=1 Ice.Warn.Connections=1 Ice.ThreadPool.Server.SizeWarn=0 IceSSL.CertFile=server.p12 Test.BasePort=14300 IceSSL.DefaultDir=/home/ubuntu/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/certs Ice.Admin.Endpoints=\"tcp -h \\\"::1\\\"\" Ice.PrintStackTraces=1 IceSSL.Password=password Ice.ThreadPool.Server.Serialize=1 Ice.Default.Protocol=wss Ice.Default.Host=::1 Ice.IPv6=1 IceMX.Metrics.Parent.GroupBy=parent IceMX.Metrics.Debug.GroupBy=id Ice.PreferIPv6Address=1 IceSSL.CAs=cacert.pem" --IceSSL.DefaultDir=/home/ubuntu/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/certs --Ice.Admin.Endpoints="tcp -h \"::1\"" --Ice.PrintStackTraces=1 --IceSSL.Password=password --IceGrid.Node.Data=/home/ubuntu/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/cpp/test/IceGrid/admin/node-localnode --IceGrid.Node.Name=localnode --IceGrid.Node.WaitTime=240 --Ice.Default.Protocol=wss --IceSSL.CAs=cacert.pem env={'LD_LIBRARY_PATH': '/usr/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu'})
ok
starting Glacier2 router... (/usr/bin/glacier2router --Ice.Plugin.IceSSL=IceSSL:createIceSSL --Glacier2.PermissionsVerifier=Glacier2/NullPermissionsVerifier --Ice.Override.Compress=1 --Ice.PrintAdapterReady=1 --IceMX.Metrics.All.GroupBy=none --Ice.Admin.InstanceName=Glacier2 --Glacier2.Server.Endpoints=tcp --Ice.NullHandleAbort=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.Size=1 --Ice.Warn.Connections=1 --Ice.ThreadPool.Server.SizeWarn=0 --IceSSL.CertFile=server.p12 --Glacier2.SessionManager=TestIceGrid/AdminSessionManager --Ice.Default.Locator="TestIceGrid/Locator:default -p 14320:default -p 14321" --IceSSL.DefaultDir=/home/ubuntu/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/certs --Ice.Admin.Endpoints="default -p 14351" --Glacier2.SessionTimeout=5 --Ice.PrintStackTraces=1 --Glacier2.SSLPermissionsVerifier=Glacier2/NullSSLPermissionsVerifier --IceSSL.Password=password --Ice.ThreadPool.Server.Serialize=1 --Glacier2.SSLSessionManager=TestIceGrid/AdminSSLSessionManager --Ice.Default.Protocol=wss --Glacier2.Client.Endpoints="default -p 14350" --Ice.Default.Host=::1 --Ice.IPv6=1 --IceMX.Metrics.Parent.GroupBy=parent --Glacier2.CryptPasswords=/home/ubuntu/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/cpp/test/IceGrid/admin/passwords --IceMX.Metrics.Debug.GroupBy=id --Ice.PreferIPv6Address=1 --IceSSL.CAs=cacert.pem --IceSSL.VerifyPeer=1 env={'LD_LIBRARY_PATH': '/usr/lib/aarch64-linux-gnu'})
ok
testing login with username/password... (/usr/bin/icegridadmin --IceGridAdmin.Username=admin1 --Ice.Plugin.IceSSL=IceSSL:createIceSSL --Ice.Override.Compress=1 --IceMX.Metrics.All.GroupBy=none --Ice.Admin.InstanceName=Client --Ice.NullHandleAbort=1 --Ice.Default.Locator="TestIceGrid/Locator:default -p 14320" --Ice.Warn.Connections=1 --IceSSL.CertFile=client.p12 --IceSSL.DefaultDir=/home/ubuntu/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/certs --Ice.Admin.Endpoints="tcp -h \"::1\"" --Ice.PrintStackTraces=1 --IceSSL.Password=password --Ice.ThreadPool.Server.Serialize=1 --Ice.Default.Protocol=wss --Ice.Default.Host=::1 --Ice.IPv6=1 --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.Debug.GroupBy=id --Ice.PreferIPv6Address=1 --IceGridAdmin.Password=test1 --IceSSL.CAs=cacert.pem env={'LD_LIBRARY_PATH': '/usr/lib/aarch64-linux-gnu'})
(/usr/bin/icegridadmin --IceGridAdmin.Username=admin1 --Ice.Plugin.IceSSL=IceSSL:createIceSSL --Ice.Override.Compress=1 --IceMX.Metrics.All.GroupBy=none --Ice.Admin.InstanceName=Client --Ice.NullHandleAbort=1 --Ice.Default.Locator="TestIceGrid/Locator:default -p 14320" --Ice.Warn.Connections=1 --IceSSL.CertFile=client.p12 --IceSSL.DefaultDir=/home/ubuntu/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/certs --Ice.Admin.Endpoints="tcp -h \"::1\"" --Ice.PrintStackTraces=1 --IceSSL.Password=password --Ice.ThreadPool.Server.Serialize=1 --Ice.Default.Protocol=wss --Ice.Default.Host=::1 --Ice.IPv6=1 --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.Debug.GroupBy=id --Ice.PreferIPv6Address=1 --IceGridAdmin.Password=test1 --IceSSL.CAs=cacert.pem --Ice.Default.Router="Glacier2/router:default -p 14350" env={'LD_LIBRARY_PATH': '/usr/lib/aarch64-linux-gnu'})
(/usr/bin/icegridadmin --IceGridAdmin.Username=admin1 --Ice.Plugin.IceSSL=IceSSL:createIceSSL --Ice.Override.Compress=1 --IceMX.Metrics.All.GroupBy=none --Ice.Admin.InstanceName=Client --Ice.NullHandleAbort=1 --Ice.Default.Locator="TestIceGrid/Locator:default -p 14320" --Ice.Warn.Connections=1 --IceSSL.CertFile=client.p12 --IceSSL.DefaultDir=/home/ubuntu/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/certs --Ice.Admin.Endpoints="tcp -h \"::1\"" --Ice.PrintStackTraces=1 --IceSSL.Password=password --Ice.ThreadPool.Server.Serialize=1 --Ice.Default.Protocol=wss --Ice.Default.Host=::1 --Ice.IPv6=1 --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.Debug.GroupBy=id --Ice.PreferIPv6Address=1 --IceGridAdmin.Password=test1 --IceSSL.CAs=cacert.pem -r Master -e "node shutdown localnode" env={'LD_LIBRARY_PATH': '/usr/lib/aarch64-linux-gnu'})
(/usr/bin/icegridadmin --IceGridAdmin.Username=admin1 --Ice.Plugin.IceSSL=IceSSL:createIceSSL --Ice.Override.Compress=1 --IceMX.Metrics.All.GroupBy=none --Ice.Admin.InstanceName=Client --Ice.NullHandleAbort=1 --Ice.Default.Locator="TestIceGrid/Locator:default -p 14320" --Ice.Warn.Connections=1 --IceSSL.CertFile=client.p12 --IceSSL.DefaultDir=/home/ubuntu/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/certs --Ice.Admin.Endpoints="tcp -h \"::1\"" --Ice.PrintStackTraces=1 --IceSSL.Password=password --Ice.ThreadPool.Server.Serialize=1 --Ice.Default.Protocol=wss --Ice.Default.Host=::1 --Ice.IPv6=1 --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.Debug.GroupBy=id --Ice.PreferIPv6Address=1 --IceGridAdmin.Password=test1 --IceSSL.CAs=cacert.pem -r Master -e "registry shutdown Master" env={'LD_LIBRARY_PATH': '/usr/lib/aarch64-linux-gnu'})
(/usr/bin/icegridadmin --IceGridAdmin.Username=admin1 --Ice.Plugin.IceSSL=IceSSL:createIceSSL --Ice.Override.Compress=1 --IceMX.Metrics.All.GroupBy=none --Ice.Admin.InstanceName=Client --Ice.NullHandleAbort=1 --Ice.Default.Locator="TestIceGrid/Locator:default -p 14321" --Ice.Warn.Connections=1 --IceSSL.CertFile=client.p12 --IceSSL.DefaultDir=/home/ubuntu/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/certs --Ice.Admin.Endpoints="tcp -h \"::1\"" --Ice.PrintStackTraces=1 --IceSSL.Password=password --Ice.ThreadPool.Server.Serialize=1 --Ice.Default.Protocol=wss --Ice.Default.Host=::1 --Ice.IPv6=1 --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.Debug.GroupBy=id --Ice.PreferIPv6Address=1 --IceGridAdmin.Password=test1 --IceSSL.CAs=cacert.pem -r Slave1 -e "registry shutdown Slave1" env={'LD_LIBRARY_PATH': '/usr/lib/aarch64-linux-gnu'})

test in IceGrid/admin failed:
Traceback (most recent call last):
  File "../scripts/Util.py", line 1699, in run
    self.runWithDriver(current)
  File "../scripts/IceGridUtil.py", line 286, in runWithDriver
    current.driver.runClientServerTestCase(current)
  File "../scripts/LocalDriver.py", line 565, in runClientServerTestCase
    self.runner.runClientSide(client, current, host)
  File "../scripts/LocalDriver.py", line 197, in runClientSide
    testcase._runClientSide(current, host)
  File "../scripts/Util.py", line 1676, in _runClientSide
    self.runClientSide(current)
  File "/home/ubuntu/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/cpp/test/IceGrid/admin/test.py", line 32, in runClientSide
    admin.stop(current, True)
  File "../scripts/Util.py", line 1277, in stop
    process.waitSuccess(exitstatus=exitstatus, timeout=30)
  File "../scripts/Expect.py", line 632, in waitSuccess
    self.testExitStatus(exitstatus)
  File "../scripts/Expect.py", line 667, in testExitStatus
    test(self.exitstatus, exitstatus)
  File "../scripts/Expect.py", line 653, in test
    raise RuntimeError("unexpected exit status: expected: {0}, got {1}\n".format(expected, result))
RuntimeError: unexpected exit status: expected: 0, got 1


Traceback (most recent call last):
  File "../scripts/LocalDriver.py", line 501, in runTestSuite
    testcase.run(current)
  File "../scripts/Util.py", line 1699, in run
    self.runWithDriver(current)
  File "../scripts/IceGridUtil.py", line 286, in runWithDriver
    current.driver.runClientServerTestCase(current)
  File "../scripts/LocalDriver.py", line 565, in runClientServerTestCase
    self.runner.runClientSide(client, current, host)
  File "../scripts/LocalDriver.py", line 197, in runClientSide
    testcase._runClientSide(current, host)
  File "../scripts/Util.py", line 1676, in _runClientSide
    self.runClientSide(current)
  File "/home/ubuntu/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/cpp/test/IceGrid/admin/test.py", line 32, in runClientSide
    admin.stop(current, True)
  File "../scripts/Util.py", line 1277, in stop
    process.waitSuccess(exitstatus=exitstatus, timeout=30)
  File "../scripts/Expect.py", line 632, in waitSuccess
    self.testExitStatus(exitstatus)
  File "../scripts/Expect.py", line 667, in testExitStatus
    test(self.exitstatus, exitstatus)
  File "../scripts/Expect.py", line 653, in test
    raise RuntimeError("unexpected exit status: expected: {0}, got {1}\n".format(expected, result))
RuntimeError: unexpected exit status: expected: 0, got 1
```

**Comment by bentoi** [comment]
Let's reopen when this occurs again, we should get more info this time on the error.
