### ISSUE TITLE
macOS Ice/slicing/objects cross test failure

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#549]
```
[ running client/server test - 09/23/19 17:02:25 ]
- Config: shared
- Mappings: csharp,objective-c
(/Users/vagrant/workspace/ice/3.7/objective-c/test/Ice/slicing/objects/build/macosx/shared/server --Ice.Warn.Connections=1 --Ice.PrintAdapterReady=1 --Ice.ThreadPool.Server.Size=1 --Ice.Default.Protocol=tcp --Ice.Default.Host=127.0.0.1 --Ice.IPv6=0 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 env={'DYLD_LIBRARY_PATH': '/Users/vagrant/workspace/ice/3.7/cpp/lib'})
(dotnet /Users/vagrant/workspace/ice/3.7/csharp/test/Ice/slicing/objects/msbuild/client/netstandard2.0/netcoreapp2.1/client.dll --Ice.Default.Host=127.0.0.1 --Ice.Warn.Connections=1 --Ice.IPv6=0 --Ice.Default.Protocol=tcp)
testing stringToProxy... ok
testing checked cast... ok
base as Object... ok
base as Object (AMI)... ok
base as base... ok
base as base (AMI)... ok
base with known derived as base... ok
base with known derived as base (AMI)... ok
base with known derived as known derived... ok
base with known derived as known derived (AMI)... ok
base with unknown derived as base... ok
base with unknown derived as base (AMI)... ok
unknown with Object as Object... ok
unknown with Object as Object (AMI)... -! 9/23/19 17:02:26:299 client: warning: connection exception:
   Ice.ConnectionLostException
       error = 0
      at IceInternal.StreamSocket.finishRead(Buffer buf) in /Users/vagrant/workspace/ice/3.7/csharp/src/Ice/StreamSocket.cs:line 201
      at Ice.ConnectionI.finishAsync(Int32 operation) in /Users/vagrant/workspace/ice/3.7/csharp/src/Ice/ConnectionI.cs:line 1115
   local address = 127.0.0.1:50843
   remote address = 127.0.0.1:12010
Assertion Failed

   at AllTests.<>c.<allTests>b__4_18(Exception ex) in /Users/vagrant/workspace/ice/3.7/csharp/test/Ice/slicing/objects/AllTests.cs:line 463
   at IceInternal.OperationAsyncResultCompletionCallback`2.<getCompletedCallback>b__1_0(AsyncResult r) in /Users/vagrant/workspace/ice/3.7/csharp/src/Ice/OutgoingAsync.cs:line 1694
   at IceInternal.AsyncResultCompletionCallback.handleInvokeException(Exception ex, OutgoingAsyncBase og) in /Users/vagrant/workspace/ice/3.7/csharp/src/Ice/OutgoingAsync.cs:line 1605
   at IceInternal.OutgoingAsyncBase.invokeException() in /Users/vagrant/workspace/ice/3.7/csharp/src/Ice/OutgoingAsync.cs:line 100
   at Ice.ConnectionI.finish() in /Users/vagrant/workspace/ice/3.7/csharp/src/Ice/ConnectionI.cs:line 1651
   at IceInternal.ThreadPool.run(WorkerThread thread) in /Users/vagrant/workspace/ice/3.7/csharp/src/Ice/ThreadPool.cs:line 614
   at IceInternal.ThreadPool.WorkerThread.Run() in /Users/vagrant/workspace/ice/3.7/csharp/src/Ice/ThreadPool.cs:line 861
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Comment by pepone** [comment]
Updated the test to print the unexpected exception in case this happens again
