### ISSUE TITLE
java-compat/Ice/acm  failures

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#558]
```
*** [7/58] Running java-compat/Ice/acm tests ***
[ running client/server test - 09/27/19 12:15:43 ]
- Config: tcp,Release,x64
(C:\Program Files\Java\jdk1.8.0_221\bin\java -ea -Dtest.class=test.Ice.acm.Server test.TestDriver --Ice.Default.Host=127.0.0.1 --Test.BasePort=14200 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp --Ice.IPv6=0 --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 env={'CLASSPATH': 'C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice\\builds\\ice-v140-default\\java-compat\\lib\\test.jar'})
(C:\Program Files\Java\jdk1.8.0_221\bin\java -ea -Dtest.class=test.Ice.acm.Client test.TestDriver --Ice.Default.Host=127.0.0.1 --Test.BasePort=14200 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp --Ice.IPv6=0 env={'CLASSPATH': 'C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice\\builds\\ice-v140-default\\java-compat\\lib\\test.jar'})
testing invocation heartbeat... ok
testing invocation with heartbeat on hold... ok
testing invocation with no heartbeat... ok
testing invocation with no heartbeat and close on idle... ok
testing close on idle... ok
testing close on invocation... ok
testing close on idle and invocation... ok
testing forceful close on idle and invocation... ok
testing heartbeat on idle... ok
testing heartbeat always... ok
testing manual heartbeats... ok
testing setACM/getACM... ok
shutting down... ok
[ running client/server test - 09/27/19 12:15:52 ]
- Config: ssl,compress,ipv6,serialize,mx,Release,x64
(C:\Program Files\Java\jdk1.8.0_221\bin\java -ea -Dtest.class=test.Ice.acm.Server test.TestDriver --Ice.Default.Host=::1 --Test.BasePort=14200 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.Override.Compress=1 --Ice.ThreadPool.Server.Serialize=1 --Ice.IPv6=1 --Ice.PreferIPv6Address=1 --Ice.Admin.Endpoints="tcp -h \"::1\"" --Ice.Admin.InstanceName=Server --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --Ice.Plugin.IceSSL=IceSSL.PluginFactory --IceSSL.Password=password --IceSSL.DefaultDir=C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v140-default\certs --IceSSL.Keystore=server.jks --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 env={'CLASSPATH': 'C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice\\builds\\ice-v140-default\\java-compat\\lib\\test.jar'})
(C:\Program Files\Java\jdk1.8.0_221\bin\java -ea -Dtest.class=test.Ice.acm.Client test.TestDriver --Ice.Default.Host=::1 --Test.BasePort=14200 --Ice.Warn.Connections=1 --Ice.Default.Protocol=ssl --Ice.Override.Compress=1 --Ice.ThreadPool.Server.Serialize=1 --Ice.IPv6=1 --Ice.PreferIPv6Address=1 --Ice.Admin.Endpoints="tcp -h \"::1\"" --Ice.Admin.InstanceName=Client --IceMX.Metrics.Debug.GroupBy=id --IceMX.Metrics.Parent.GroupBy=parent --IceMX.Metrics.All.GroupBy=none --Ice.Plugin.IceSSL=IceSSL.PluginFactory --IceSSL.Password=password --IceSSL.DefaultDir=C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v140-default\certs --IceSSL.Keystore=client.jks env={'CLASSPATH': 'C:\\Users\\vagrant\\workspace\\ice-dist\\3.7\\dist-utils\\build\\ice\\builds\\ice-v140-default\\java-compat\\lib\\test.jar'})
testing invocation heartbeat... ok
testing invocation with heartbeat on hold... ok
testing invocation with no heartbeat... ok
testing invocation with no heartbeat and close on idle... ok
testing close on idle... ok
testing close on invocation... ok
testing close on idle and invocation... failed! unexpected exception:
java.lang.RuntimeException
	at test.Ice.acm.AllTests.test(AllTests.java:24)
	at test.Ice.acm.AllTests.access$000(AllTests.java:16)
	at test.Ice.acm.AllTests$CloseOnIdleAndInvocationTest.runTestCase(AllTests.java:470)
	at test.Ice.acm.AllTests$TestCase.run(AllTests.java:238)
	at test.Ice.acm.AllTests$TestCase$1.run(AllTests.java:167)
	at java.lang.Thread.run(Thread.java:748)

java.lang.RuntimeException
	at test.Ice.acm.AllTests.test(AllTests.java:24)
	at test.Ice.acm.AllTests.access$000(AllTests.java:16)
	at test.Ice.acm.AllTests$TestCase.join(AllTests.java:203)
	at test.Ice.acm.AllTests.allTests(AllTests.java:715)
	at test.Ice.acm.Client.run(Client.java:16)
	at test.TestDriver.main(TestDriver.java:17)

test in Ice/acm failed:
Traceback (most recent call last):
  File "..\scripts\Util.py", line 1700, in run
    self.runWithDriver(current)
  File "..\scripts\Util.py", line 1729, in runWithDriver
    current.driver.runClientServerTestCase(current)
  File "..\scripts\LocalDriver.py", line 565, in runClientServerTestCase
    self.runner.runClientSide(client, current, host)
  File "..\scripts\LocalDriver.py", line 197, in runClientSide
    testcase._runClientSide(current, host)
  File "..\scripts\Util.py", line 1677, in _runClientSide
    self.runClientSide(current)
  File "..\scripts\Util.py", line 1569, in runClientSide
    self._runClient(current, client)
  File "..\scripts\Util.py", line 1689, in _runClient
    client.run(current)
  File "..\scripts\Util.py", line 1194, in run
    process.waitSuccess(exitstatus=exitstatus, timeout=30)
  File "..\scripts\Expect.py", line 632, in waitSuccess
    self.testExitStatus(exitstatus)
  File "..\scripts\Expect.py", line 667, in testExitStatus
    test(self.exitstatus, exitstatus)
  File "..\scripts\Expect.py", line 653, in test
    raise RuntimeError("unexpected exit status: expected: {0}, got {1}\n".format(expected, result))
RuntimeError: unexpected exit status: expected: 0, got 1
```

**Comment by bernardnormier** [comment]
Here is the failed test:
https://github.com/zeroc-ice/ice/blob/3.7/java-compat/test/src/main/java/test/Ice/acm/AllTests.java#L470

On a very slow VM, the hold could be called after the 1s timeout. We could increase this timeout to 2s, if that's the issue.

**Comment by pepone** [comment]
Seems the most likely, connection should have not been closed if hold was call on time

**Comment by pepone** [comment]
Happen again on `ice-dist-windows-windows_7_vs2015_x64-test-3.7`

**Comment by pepone** [comment]
New failure was with Java language mapping, missed from my previous fix
