### ISSUE TITLE
IceSSL/configuration failures on iOS

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#570]
```
*** [35/35] Running cpp/IceSSL/configuration tests ***
[ running client/server test - 10/03/19 08:20:43 ]
- Config: xcodesdk,iphonesimulator
(executing `IceSSL/configuration/server' on `iOS Simulator (iOS-13-0)' args = ['--Ice.Default.Host=127.0.0.1', '--Ice.Warn.Connections=1', '--Ice.IPv6=0', '--Ice.PrintStackTraces=1', '--Ice.ThreadPool.Server.SizeMax=3', '--Ice.ThreadPool.Server.SizeWarn=0', '--Ice.NullHandleAbort=1', '--Ice.Default.Protocol=tcp', '--Ice.ThreadPool.Server.Size=1', '"{testdir}"'])
(executing `IceSSL/configuration/client' on `iOS Simulator (iOS-13-0)' args = ['--Ice.Default.Host=127.0.0.1', '--Ice.Warn.Connections=1', '--Ice.IPv6=0', '--Ice.PrintStackTraces=1', '--Ice.NullHandleAbort=1', '--Ice.Default.Protocol=tcp', '"{testdir}"'])
testing with PKCS12 certificates...
testing manual initialization... ok
testing certificate verification... failed!
test/IceSSL/configuration/AllTests.cpp:1304: assertion `isCatalinaOrGreater' failed
unexpected unknown exception while running `IceSSL/configuration client'
Traceback (most recent call last):
  File "../scripts/Util.py", line 1700, in run
    self.runWithDriver(current)
  File "../scripts/Util.py", line 1729, in runWithDriver
    current.driver.runClientServerTestCase(current)
  File "../scripts/LocalDriver.py", line 594, in runClientServerTestCase
    raise failure[0]
ConnectionLostException: Ice.ConnectionLostException:
recv() returned zero
```

```
*** [35/35] Running cpp/IceSSL/configuration tests ***
[ running client/server test - 10/03/19 08:32:38 ]
- Config: cpp11-xcodesdk,iphonesimulator
(executing `IceSSL/configuration/server' on `iOS Simulator (iOS-13-0)' args = ['--Ice.Default.Host=127.0.0.1', '--Ice.Warn.Connections=1', '--Ice.IPv6=0', '--Ice.PrintStackTraces=1', '--Ice.ThreadPool.Server.SizeMax=3', '--Ice.ThreadPool.Server.SizeWarn=0', '--Ice.NullHandleAbort=1', '--Ice.Default.Protocol=tcp', '--Ice.ThreadPool.Server.Size=1', '"{testdir}"'])
(executing `IceSSL/configuration/client' on `iOS Simulator (iOS-13-0)' args = ['--Ice.Default.Host=127.0.0.1', '--Ice.Warn.Connections=1', '--Ice.IPv6=0', '--Ice.PrintStackTraces=1', '--Ice.NullHandleAbort=1', '--Ice.Default.Protocol=tcp', '"{testdir}"'])
testing with PKCS12 certificates...
testing manual initialization... ok
testing certificate verification... failed!
test/IceSSL/configuration/AllTests.cpp:1304: assertion `isCatalinaOrGreater' failed
unexpected unknown exception while running `IceSSL/configuration client'
Traceback (most recent call last):
  File "../scripts/Util.py", line 1700, in run
    self.runWithDriver(current)
  File "../scripts/Util.py", line 1729, in runWithDriver
    current.driver.runClientServerTestCase(current)
  File "../scripts/LocalDriver.py", line 594, in runClientServerTestCase
    raise failure[0]
ConnectionLostException: Ice.ConnectionLostException:
recv() returned zero
```

**Comment by pepone** [comment]
We already expect this test to fail on Catalina because of macOS SecureTransport changes, probably iOS 13 is aligned with catalina
