### ISSUE TITLE
java-compat/IceSSL/configuration failure on rhel8

### ISSUE THREAD

**Issue by bernardnormier** [zeroc-ice/ice#573]
From ice-dist/3.7 1061:

```
*** [53/58] Running java-compat/IceSSL/configuration tests ***
[ running client/server test - 10/04/19 04:22:52 ]
- Config: x64
(/usr/lib/jvm/java-11/bin/java -ea -Dtest.class=test.IceSSL.configuration.Server test.TestDriver --Ice.Default.Host=127.0.0.1 --Test.BasePort=14100 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp --Ice.IPv6=0 --Ice.ThreadPool.Server.Size=1 --Ice.ThreadPool.Server.SizeMax=3 --Ice.ThreadPool.Server.SizeWarn=0 --Ice.PrintAdapterReady=1 "/home/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/java-compat/test/src/main/java/test/IceSSL/configuration" env={'CLASSPATH': '/home/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/java-compat/lib/test.jar'})
(/usr/lib/jvm/java-11/bin/java -ea -Dtest.class=test.IceSSL.configuration.Client test.TestDriver --Ice.Default.Host=127.0.0.1 --Test.BasePort=14100 --Ice.Warn.Connections=1 --Ice.Default.Protocol=tcp --Ice.IPv6=0 "/home/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/java-compat/test/src/main/java/test/IceSSL/configuration" env={'CLASSPATH': '/home/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-g++-default/java-compat/lib/test.jar'})
testing manual initialization... ok
testing certificate verification... ok
testing certificate chains... ok
testing custom certificate verifier... ok
testing protocols... ok
testing expired certificates... ok
testing multiple CA certificates... ok
testing passwords... ok
testing ciphers... Ice.SecurityException
    reason = "IceSSL: handshake error"
	at IceInternal.AsyncResultI.waitForResponseOrUserEx(AsyncResultI.java:265)
	at Ice.ObjectPrxHelperBase._end(ObjectPrxHelperBase.java:2711)
	at Ice.ObjectPrxHelperBase.end_ice_ping(ObjectPrxHelperBase.java:555)
	at Ice.ObjectPrxHelperBase._iceI_ice_ping(ObjectPrxHelperBase.java:375)
	at Ice.ObjectPrxHelperBase.ice_ping(ObjectPrxHelperBase.java:355)
	at test.IceSSL.configuration.AllTests.allTests(AllTests.java:1510)
	at test.IceSSL.configuration.Client.run(Client.java:26)
	at test.TestDriver.main(TestDriver.java:17)
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:307)
	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:285)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:180)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
	at java.base/sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:668)
	at java.base/sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:623)
	at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:441)
	at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:420)
	at java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:634)
	at IceSSL.TransceiverI.handshakeNonBlocking(TransceiverI.java:361)
	at IceSSL.TransceiverI.initialize(TransceiverI.java:60)
	at Ice.ConnectionI.initialize(ConnectionI.java:2204)
	at Ice.ConnectionI.message(ConnectionI.java:1191)
	at IceInternal.ThreadPool.run(ThreadPool.java:394)
	at IceInternal.ThreadPool.access$500(ThreadPool.java:7)
	at IceInternal.ThreadPool$EventHandlerThread.run(ThreadPool.java:768)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.lang.RuntimeException
	at test.IceSSL.configuration.AllTests.test(AllTests.java:23)
	at test.IceSSL.configuration.AllTests.allTests(AllTests.java:1525)
	at test.IceSSL.configuration.Client.run(Client.java:26)
	at test.TestDriver.main(TestDriver.java:17)
-! 10/4/19 04:23:00:678 warning: Ice.ThreadPool.Server-0: connection exception:
   local address = 127.0.0.1:14100
   remote address = 127.0.0.1:52024
   Ice.ConnectionLostException
       error = 0
   	at IceInternal.StreamSocket.read(StreamSocket.java:188)
   	at IceInternal.StreamSocket.read(StreamSocket.java:149)
   	at IceInternal.TcpTransceiver.read(TcpTransceiver.java:58)
   	at Ice.ConnectionI.read(ConnectionI.java:3094)
   	at Ice.ConnectionI.message(ConnectionI.java:1085)
   	at IceInternal.ThreadPool.run(ThreadPool.java:394)
   	at IceInternal.ThreadPool.access$500(ThreadPool.java:7)
   	at IceInternal.ThreadPool$EventHandlerThread.run(ThreadPool.java:768)
   	at java.base/java.lang.Thread.run(Thread.java:834)

-! 10/4/19 04:23:00:688 warning: Ice.ThreadPool.Server-1: connection exception:
   local address = 127.0.0.1:14100
   remote address = 127.0.0.1:52188
   Ice.ConnectionLostException
       error = 0
   	at IceInternal.StreamSocket.read(StreamSocket.java:188)
   	at IceInternal.StreamSocket.read(StreamSocket.java:149)
   	at IceInternal.TcpTransceiver.read(TcpTransceiver.java:58)
   	at Ice.ConnectionI.read(ConnectionI.java:3094)
   	at Ice.ConnectionI.message(ConnectionI.java:1085)
   	at IceInternal.ThreadPool.run(ThreadPool.java:394)
   	at IceInternal.ThreadPool.access$500(ThreadPool.java:7)
   	at IceInternal.ThreadPool$EventHandlerThread.run(ThreadPool.java:768)
   	at java.base/java.lang.Thread.run(Thread.java:834)

test in IceSSL/configuration failed:
Traceback (most recent call last):
  File "../scripts/Util.py", line 1706, in run
    self.runWithDriver(current)
  File "../scripts/Util.py", line 1735, in runWithDriver
    current.driver.runClientServerTestCase(current)
  File "../scripts/LocalDriver.py", line 565, in runClientServerTestCase
    self.runner.runClientSide(client, current, host)
  File "../scripts/LocalDriver.py", line 197, in runClientSide
    testcase._runClientSide(current, host)
  File "../scripts/Util.py", line 1683, in _runClientSide
    self.runClientSide(current)
  File "../scripts/Util.py", line 1575, in runClientSide
    self._runClient(current, client)
  File "../scripts/Util.py", line 1695, in _runClient
    client.run(current)
  File "../scripts/Util.py", line 1194, in run
    process.waitSuccess(exitstatus=exitstatus, timeout=30)
  File "../scripts/Expect.py", line 632, in waitSuccess
    self.testExitStatus(exitstatus)
  File "../scripts/Expect.py", line 667, in testExitStatus
    test(self.exitstatus, exitstatus)
  File "../scripts/Expect.py", line 653, in test
    raise RuntimeError("unexpected exit status: expected: {0}, got {1}\n".format(expected, result))
RuntimeError: unexpected exit status: expected: 0, got 1


Traceback (most recent call last):
  File "../scripts/LocalDriver.py", line 501, in runTestSuite
    testcase.run(current)
  File "../scripts/Util.py", line 1706, in run
    self.runWithDriver(current)
  File "../scripts/Util.py", line 1735, in runWithDriver
    current.driver.runClientServerTestCase(current)
  File "../scripts/LocalDriver.py", line 565, in runClientServerTestCase
    self.runner.runClientSide(client, current, host)
  File "../scripts/LocalDriver.py", line 197, in runClientSide
    testcase._runClientSide(current, host)
  File "../scripts/Util.py", line 1683, in _runClientSide
    self.runClientSide(current)
  File "../scripts/Util.py", line 1575, in runClientSide
    self._runClient(current, client)
  File "../scripts/Util.py", line 1695, in _runClient
    client.run(current)
  File "../scripts/Util.py", line 1194, in run
    process.waitSuccess(exitstatus=exitstatus, timeout=30)
  File "../scripts/Expect.py", line 632, in waitSuccess
    self.testExitStatus(exitstatus)
  File "../scripts/Expect.py", line 667, in testExitStatus
    test(self.exitstatus, exitstatus)
  File "../scripts/Expect.py", line 653, in test
    raise RuntimeError("unexpected exit status: expected: {0}, got {1}\n".format(expected, result))
RuntimeError: unexpected exit status: expected: 0, got 1

```

**Comment by pepone** [comment]
https://github.com/zeroc-ice/ice/blob/3.7/java/test/src/main/java/test/IceSSL/configuration/AllTests.java#L1521

So we expect this to fail in el8 but with different exception
