### ISSUE TITLE
Unable to start C++11 Test Controller on Catalina iOS Simulator

### ISSUE THREAD

**Issue by externl** [zeroc-ice/ice#631]
```
+ python allTests.py --debug --workers=4 --export-xml=results-ice-ci-macos-catalina_ios-dev-master.xml --all --config=Debug --controller-app --languages=swift,csharp --platform=iphonesimulator
*** [1/61] Running csharp/Ice/acm tests ***
[ running client/server test - 11/13/19 18:54:59 ]
- Config: ssl,Debug,iphonesimulator
launching simulator... ok
launching controller.iOS.app... ok
controller application unreachable, restarting... Traceback (most recent call last):
  File "scripts/Util.py", line 1692, in run
    self.runWithDriver(current)
  File "scripts/Util.py", line 1721, in runWithDriver
    current.driver.runClientServerTestCase(current)
  File "scripts/LocalDriver.py", line 563, in runClientServerTestCase
    host = self.runner.startServerSide(server, current)
  File "scripts/LocalDriver.py", line 191, in startServerSide
    return testcase._startServerSide(current)
  File "scripts/Util.py", line 1625, in _startServerSide
    current.host = current.driver.getProcessController(current).getHost(current)
  File "scripts/Util.py", line 2178, in getHost
    return self.getController(current).getHost(current.config.protocol, current.config.ipv6)
  File "scripts/Util.py", line 2244, in getController
    self.restartControllerApp(current, ident)
  File "scripts/Util.py", line 2517, in restartControllerApp
    run("xcrun simctl launch \"{0}\" {1}".format(self.device, ident.name))
  File "scripts/Util.py", line 38, in run
    raise RuntimeError(cmd + " failed:\n" + out)
RuntimeError: xcrun simctl launch "iOSSimulatorProcessController" com.zeroc.Xamarin-Test-Controller failed:
An error was encountered processing the command (domain=NSMachErrorDomain, code=-308):
The operation couldn\u2019t be completed. (Mach error -308 - (ipc/mig) server died)


test in Ice/acm failed:
Traceback (most recent call last):
  File "scripts/Util.py", line 1692, in run
    self.runWithDriver(current)
  File "scripts/Util.py", line 1721, in runWithDriver
    current.driver.runClientServerTestCase(current)
  File "scripts/LocalDriver.py", line 563, in runClientServerTestCase
    host = self.runner.startServerSide(server, current)
  File "scripts/LocalDriver.py", line 191, in startServerSide
    return testcase._startServerSide(current)
  File "scripts/Util.py", line 1625, in _startServerSide
    current.host = current.driver.getProcessController(current).getHost(current)
  File "scripts/Util.py", line 2178, in getHost
    return self.getController(current).getHost(current.config.protocol, current.config.ipv6)
  File "scripts/Util.py", line 2244, in getController
    self.restartControllerApp(current, ident)
  File "scripts/Util.py", line 2517, in restartControllerApp
    run("xcrun simctl launch \"{0}\" {1}".format(self.device, ident.name))
  File "scripts/Util.py", line 38, in run
    raise RuntimeError(cmd + " failed:\n" + out)
RuntimeError: xcrun simctl launch "iOSSimulatorProcessController" com.zeroc.Xamarin-Test-Controller failed:
An error was encountered processing the command (domain=NSMachErrorDomain, code=-308):
The operation couldn\u2019t be completed. (Mach error -308 - (ipc/mig) server died)

Traceback (most recent call last):
  File "scripts/LocalDriver.py", line 501, in runTestSuite
    testcase.run(current)
  File "scripts/Util.py", line 1692, in run
    self.runWithDriver(current)
  File "scripts/Util.py", line 1721, in runWithDriver
    current.driver.runClientServerTestCase(current)
  File "scripts/LocalDriver.py", line 563, in runClientServerTestCase
    host = self.runner.startServerSide(server, current)
  File "scripts/LocalDriver.py", line 191, in startServerSide
    return testcase._startServerSide(current)
  File "scripts/Util.py", line 1625, in _startServerSide
    current.host = current.driver.getProcessController(current).getHost(current)
  File "scripts/Util.py", line 2178, in getHost
    return self.getController(current).getHost(current.config.protocol, current.config.ipv6)
  File "scripts/Util.py", line 2244, in getController
    self.restartControllerApp(current, ident)
  File "scripts/Util.py", line 2517, in restartControllerApp
    run("xcrun simctl launch \"{0}\" {1}".format(self.device, ident.name))
  File "scripts/Util.py", line 38, in run
    raise RuntimeError(cmd + " failed:\n" + out)
RuntimeError: xcrun simctl launch "iOSSimulatorProcessController" com.zeroc.Xamarin-Test-Controller failed:
An error was encountered processing the command (domain=NSMachErrorDomain, code=-308):
The operation couldn\u2019t be completed. (Mach error -308 - (ipc/mig) server died)
```

I also tried manually in the VM and it just seem to hang when loading into the simulator.

**Comment by externl** [comment]
Starts fine in my local simulator. Our VM is running a Xcode 11.1 (11.2.1 is out) so maybe we just. need to update that. I'll try in a VM.

**Comment by externl** [comment]
I tried this in a local VM and it also worked fine. Going to try with a fresh CI VM.

**Comment by externl** [comment]
@benoit fixed this in https://github.com/zeroc-ice/ice/commit/c05224216e04150747851f0db3f71510ff85e162
