### ISSUE TITLE
C# Ice/background failures

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#650]
```
testing read/write... System.Exception: Exception of type 'System.Exception' was thrown.
   at AllTests.test(Boolean b) in /home/vagrant/workspace/ice/master/csharp/test/Ice/background/AllTests.cs:line 21
   at AllTests.readWriteTests(Configuration configuration, BackgroundPrx background, BackgroundControllerPrx ctl) in /home/vagrant/workspace/ice/master/csharp/test/Ice/background/AllTests.cs:line 1121
   at AllTests.allTests(TestHelper helper) in /home/vagrant/workspace/ice/master/csharp/test/Ice/background/AllTests.cs:line 226
   at Client.run(String[] args) in /home/vagrant/workspace/ice/master/csharp/test/Ice/background/Client.cs:line 43
   at Test.TestDriver.runTest[T](String[] args) in /home/vagrant/workspace/ice/master/csharp/test/TestCommon/TestHelper.cs:line 181

test in Ice/background failed:
Traceback (most recent call last):
  File "scripts/Util.py", line 1692, in run
    self.runWithDriver(current)
  File "scripts/Util.py", line 1721, in runWithDriver
    current.driver.runClientServerTestCase(current)
  File "scripts/LocalDriver.py", line 565, in runClientServerTestCase
    self.runner.runClientSide(client, current, host)
  File "scripts/LocalDriver.py", line 197, in runClientSide
    testcase._runClientSide(current, host)
  File "scripts/Util.py", line 1669, in _runClientSide
    self.runClientSide(current)
  File "scripts/Util.py", line 1561, in runClientSide
    self._runClient(current, client)
  File "scripts/Util.py", line 1681, in _runClient
    client.run(current)
  File "scripts/Util.py", line 1180, in run
    process.waitSuccess(exitstatus=exitstatus, timeout=30)
  File "scripts/Expect.py", line 632, in waitSuccess
    self.testExitStatus(exitstatus)
  File "scripts/Expect.py", line 667, in testExitStatus
    test(self.exitstatus, exitstatus)
  File "scripts/Expect.py", line 653, in test
    raise RuntimeError("unexpected exit status: expected: {0}, got {1}\n".format(expected, result))
RuntimeError: unexpected exit status: expected: 0, got 1


Traceback (most recent call last):
  File "scripts/LocalDriver.py", line 501, in runTestSuite
    testcase.run(current)
  File "scripts/Util.py", line 1692, in run
    self.runWithDriver(current)
  File "scripts/Util.py", line 1721, in runWithDriver
    current.driver.runClientServerTestCase(current)
  File "scripts/LocalDriver.py", line 565, in runClientServerTestCase
    self.runner.runClientSide(client, current, host)
  File "scripts/LocalDriver.py", line 197, in runClientSide
    testcase._runClientSide(current, host)
  File "scripts/Util.py", line 1669, in _runClientSide
    self.runClientSide(current)
  File "scripts/Util.py", line 1561, in runClientSide
    self._runClient(current, client)
  File "scripts/Util.py", line 1681, in _runClient
    client.run(current)
  File "scripts/Util.py", line 1180, in run
    process.waitSuccess(exitstatus=exitstatus, timeout=30)
  File "scripts/Expect.py", line 632, in waitSuccess
    self.testExitStatus(exitstatus)
  File "scripts/Expect.py", line 667, in testExitStatus
    test(self.exitstatus, exitstatus)
  File "scripts/Expect.py", line 653, in test
    raise RuntimeError("unexpected exit status: expected: {0}, got {1}\n".format(expected, result))
RuntimeError: unexpected exit status: expected: 0, got 1
```

**Comment by pepone** [comment]
we are no longer running this test
