### ISSUE TITLE
CSharp unable to load service in netcore 3.1.100

### ISSUE THREAD

**Issue by rainwolfchen** [zeroc-ice/ice#656]
Dec 06 09:39:49 localhost.localdomain dotnet[1712]: iceboxnet Error: 0 :
Dec 06 09:39:49 localhost.localdomain dotnet[1712]: IceBox: error: IceBox.FailureException
                                                           reason = "ServiceManager: unable to load service '/var...pl'"
                                                          at IceBox.ServiceManagerI.startService(String service, S...

---------------------------------------------------------
In centos7, it works in net core 3.0, but throw the upper exception in net core 3.1.100.
In windows, it works in net core 3.0 and 3.1.100.

**Comment by pepone** [comment]
Can you provide the complete exception message

**Comment by rainwolfchen** [comment]
Dec 06 20:34:55 localhost.localdomain systemd[1]: Starting FeicyCMS Server...
Dec 06 20:34:55 localhost.localdomain icegridnode[1968]: -- 12/06/19 20:34:55.252 /usr/bin/icegridnode: ThreadPool: creating Ice.ThreadPool.Client: Size = 1, SizeMax = 100, SizeWarn = 0
Dec 06 20:34:55 localhost.localdomain systemd[1]: Started FeicyCMS Server.
Dec 06 20:34:55 localhost.localdomain dotnet[1992]: iceboxnet Error: 0 :
Dec 06 20:34:55 localhost.localdomain dotnet[1992]: IceBox: error: IceBox.FailureException
                                                           reason = "ServiceManager: unable to load service '/var/ftp/virtual/ftpuser123/icedata/3.7.3/dll/feicycms/FeicyCMSService.dll:IceBoxServiceImpl': GetType failed for 'IceBoxServiceImpl'"
                                                          at IceBox.ServiceManagerI.startService(String service, String entryPoint, String[] args) in C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142\csharp\src\IceBox\ServiceManagerI.cs:line 518
                                                          at IceBox.ServiceManagerI.run() in C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142\csharp\src\IceBox\ServiceManagerI.cs:line 383
                                                       Caused by: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

                                                          at System.Reflection.RuntimeAssembly.GetType(QCallAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type, ObjectHandleOnStack keepAlive, ObjectHandleOnStack assemblyLoadContext)
                                                          at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
                                                          at System.Reflection.Assembly.GetType(String name, Boolean throwOnError)
                                                          at IceBox.ServiceManagerI.startService(String service, String entryPoint, String[] args) in C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142\csharp\src\IceBox\ServiceManagerI.cs:line 512

**Comment by rainwolfchen** [comment]
After chmod -R 777 /var/ftp/virtual/ftpuser123/icedata/3.7.3/dll/feicycms
also got this exception
----------------------------------------
Dec 06 20:41:55 localhost.localdomain systemd[1]: Starting FeicyCMS Server...
Dec 06 20:41:55 localhost.localdomain icegridnode[2044]: -- 12/06/19 20:41:55.898 /usr/bin/icegridnode: ThreadPool: creating Ice.ThreadPool.Client: Size = 1, SizeMax = 100, SizeWarn = 0
Dec 06 20:41:55 localhost.localdomain systemd[1]: Started FeicyCMS Server.
Dec 06 20:41:56 localhost.localdomain dotnet[2067]: iceboxnet Error: 0 :
Dec 06 20:41:56 localhost.localdomain dotnet[2067]: IceBox: error: IceBox.FailureException
                                                           reason = "ServiceManager: unable to load service '/var/ftp/virtual/ftpuser123/icedata/3.7.3/dll/feicycms/FeicyCMSService.dll:IceBoxServiceImpl': GetType failed for 'IceBoxServiceImpl'"
                                                          at IceBox.ServiceManagerI.startService(String service, String entryPoint, String[] args) in C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142\csharp\src\IceBox\ServiceManagerI.cs:line 518
                                                          at IceBox.ServiceManagerI.run() in C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142\csharp\src\IceBox\ServiceManagerI.cs:line 383
                                                       Caused by: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

                                                          at System.Reflection.RuntimeAssembly.GetType(QCallAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type, ObjectHandleOnStack keepAlive, ObjectHandleOnStack assemblyLoadContext)
                                                          at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
                                                          at System.Reflection.Assembly.GetType(String name, Boolean throwOnError)
                                                          at IceBox.ServiceManagerI.startService(String service, String entryPoint, String[] args) in C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142\csharp\src\IceBox\ServiceManagerI.cs:line 512

**Comment by pepone** [comment]
How are you starting iceboxnet? If you build for .NET Core you should use `dotnet iceboxnet.dll` the `iceboxnet.exe` in the 3.7 NuGet packages requires .NET Framework.

see https://github.com/zeroc-ice/ice-demos/blob/f557b8fa5a9c854da14c882ae4645117526e226f/csharp/IceGrid/icebox/application-netcore.xml#L57

**Comment by rainwolfchen** [comment]
[root@localhost ~]# dotnet --list-sdks
3.0.101 [/usr/share/dotnet/sdk]
3.1.100 [/usr/share/dotnet/sdk]
[root@localhost ~]# dotnet --list-runtimes
Microsoft.AspNetCore.App 3.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
Microsoft.NETCore.App 3.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
Microsoft.NETCore.App 3.1.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
[root@localhost ~]#

**Comment by rainwolfchen** [comment]
<node name="node1">
	  	 <server-instance template="Glacier2"
                          instance-name="FeicyCMSGlacier2"
                          client-endpoints="tcp -h localhost -p 8063"
                          server-endpoints="tcp -h localhost">
            <properties>
               <property name="Glacier2.SessionManager" value="FeicyCMSIceGrid/AdminSessionManager"/>
               <property name="Glacier2.PermissionsVerifier" value="FeicyCMSGlacier2/NullPermissionsVerifier"/>
            </properties>
         </server-instance>

         <icebox id="IceBox" activation="always" exe="dotnet">
		 	<option>/var/ftp/virtual/ftpuser123/icedata/3.7.3/dll/iceboxnet.dll</option>
            <description>A NetCore IceBox Server</description>
            <properties>
               <properties refid="mx"/>			   
               <property name="IceBox.Trace.ServiceObserver" value="1"/>
			   <property name="IceBox.LoadOrder" value="FeicyCMSService"/>
            </properties>
            <service-instance template="FeicyCMSServiceTemplate" name="FeicyCMSService"/>
            <env>LANG=en</env>
         </icebox>
      </node>

**Comment by rainwolfchen** [comment]
i copy the iceboxnet.dll from .nuget\packages\zeroc.ice.net\3.7.3\tools\netcoreapp3.0

**Comment by rainwolfchen** [comment]
In centos7, it works in net core 3.0.
In windows, it works in net core 3.0 and 3.1.100.
I installed net.core 2.2.x and net.core 2.1.x sdk in windows.

**Comment by rainwolfchen** [comment]
Sorry for my broken english :->

**Comment by pepone** [comment]
I'm lost now, You wrote that it works with .NET Core 3.0 and 3.1.10, do you mean that it doesn't work?

If you copy iceboxnet, you should copy the whole directory, zeroc.ice.net.3.7.3\tools\netcoreapp3.0

Enable IceGrid activation tracing with `IceGrid.Node.Trace.Activator=3` in the IceGrid Node configuration, this will log the commands used to run iceboxnet.

What target framework do you use for `FeicyCMSService.dll` builds?

**Comment by rainwolfchen** [comment]
In centos7, it works with net core 3.0, doesn't work with 3.1.100
In windows, net core 3.0 and net core 3.1 both work.

**Comment by rainwolfchen** [comment]
I copy all files in zeroc.ice.net\3.7.3\tools\netcoreapp3.0 to centos

**Comment by rainwolfchen** [comment]
IceBox.out with IceGrid.Node.Trace.Activator=3
---------------------------------------------------------------
!! 12/6/2019 21:15:44:441 IceBox: error: IceBox.FailureException
       reason = "ServiceManager: unable to load service '/var/ftp/virtual/ftpuser123/icedata/3.7.3/dll/feicycms/FeicyCMSService.dll:IceBoxServiceImpl': GetType failed for 'IceBoxServiceImpl'"
      at IceBox.ServiceManagerI.startService(String service, String entryPoint, String[] args) in C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142\csharp\src\IceBox\ServiceManagerI.cs:line 518
      at IceBox.ServiceManagerI.run() in C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142\csharp\src\IceBox\ServiceManagerI.cs:line 383
   Caused by: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

      at System.Reflection.RuntimeAssembly.GetType(QCallAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type, ObjectHandleOnStack keepAlive, ObjectHandleOnStack assemblyLoadContext)
      at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
      at System.Reflection.Assembly.GetType(String name, Boolean throwOnError)
      at IceBox.ServiceManagerI.startService(String service, String entryPoint, String[] args) in C:\Users\vagrant\workspace\ice-dist\3.7\dist-utils\build\ice\builds\ice-v142\csharp\src\IceBox\ServiceManagerI.cs:line 512

**Comment by rainwolfchen** [comment]
I use net.core 3.1.100 to build FeicyCMSService.dll

**Comment by rainwolfchen** [comment]
In centos7, it works with net core 3.0 (use net.core 3.0 to build FeicyCMSService.dll), doesn't work with 3.1.100 (use net.core 3.1.100 to build FeicyCMSService.dll)
In windows, net core 3.0 (use net.core 3.0 to build FeicyCMSService.dll) and net core 3.1 (use net.core 3.1.100 to build FeicyCMSService.dll) both work.

**Comment by pepone** [comment]
I see, you can try uninstalling 3.0 run-time and see if iceboxnet automatically gets redirect to 3.1.

For higher compatibility services should target nestandard instead of .NET Core

If your service needs to target a high version of .Net Core than the one used by iceboxnet it might or might not work, you can either stick with 3.0 for your service or rebuild iceboxnet with 3.1.

```
dotnet msbuild msbuild/ice.proj /p:"AppTargetFramework=netcoreapp3.1"
```

The above command allows you to build iceboxnet to target netcoreapp3.1 see details in https://github.com/zeroc-ice/ice/tree/3.7/csharp#compiling-ice-for-net-on-linux-or-macos

The README contains instructions to build on Windows too

**Comment by rainwolfchen** [comment]
thanks

**Comment by rainwolfchen** [comment]
After uninstalling 3.0 SDK and runtimes, this problem solved. thanks again.
