### ISSUE TITLE
javascript assertion in AsyncResult

### ISSUE THREAD

**Issue by cruppstahl** [zeroc-ice/ice#691]
I'm seeing that assertion frequently in production (using Ice-ssl, but not sure if that's relevant); I am not able to reproduce it in my local setup.

Here's the callstack:

```
assertion failedError
    at Function.assert (/srv/node_modules/ice/src/Ice/Debug.js:18:45)
    at Promise.markSent (/srv/node_modules/ice/src/Ice/AsyncResult.js:64:15)
    at Promise.markSent (/srv/node_modules/ice/src/Ice/OutgoingAsync.js:168:24)
    at Promise.sent (/srv/node_modules/ice/src/Ice/OutgoingAsync.js:270:14)
    at OutgoingMessage.sent (/srv/node_modules/ice/src/Ice/ConnectionI.js:2152:27)
    at ConnectionI.sendNextMessage (/srv/node_modules/ice/src/Ice/ConnectionI.js:1631:25)
    at ConnectionI.message (/srv/node_modules/ice/src/Ice/ConnectionI.js:852:26)
    at TcpTransceiver._transceiver.setCallbacks [as _bytesWrittenCallback] (/srv/node_modules/ice/src/Ice/ConnectionI.js:159:28)
    at sync._fd.write (/srv/node_modules/ice/src/Ice/TcpTransceiver.js:239:30)
    at onCorkedFinish (_stream_writable.js:680:5)
```

Any idea what causes this?

My Ice version is 3.7.3.

**Comment by pepone** [comment]
Hey, 

Can you give some more info about your enviroment, and how to reproduce this? 

You mention that you are using Ice-ssl, but from the stack trace you are using NodeJS, Ice for JavaScript doesn't support IceSSL with NodeJS so that sounds a bit confusing.

Looking at the stack trace for ConnectionI/TcpTransceiver it doesn't seems to match 3.7.3 line numbers, are you using a patch or a different Ice version?

https://github.com/zeroc-ice/ice/blob/v3.7.3/js/src/Ice/ConnectionI.js#L852
https://github.com/zeroc-ice/ice/blob/v3.7.3/js/src/Ice/TcpTransceiver.js#L239
