### ISSUE TITLE
C# Ice/background test sporadic failures

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#699]
```
testing read/write... System.Exception: Exception of type 'System.Exception' was thrown.
   at AllTests.test(Boolean b) in C:\Users\vagrant\workspace\ice\master\csharp\test\Ice\background\AllTests.cs:line 21
   at AllTests.readWriteTests(Configuration configuration, IBackgroundPrx background, IBackgroundControllerPrx ctl) in C:\Users\vagrant\workspace\ice\master\csharp\test\Ice\background\AllTests.cs:line 1113
   at AllTests.allTests(TestHelper helper) in C:\Users\vagrant\workspace\ice\master\csharp\test\Ice\background\AllTests.cs:line 215
   at Client.run(String[] args) in C:\Users\vagrant\workspace\ice\master\csharp\test\Ice\background\Client.cs:line 46
   at Test.TestDriver.runTest[T](String[] args) in C:\Users\vagrant\workspace\ice\master\csharp\test\TestCommon\TestHelper.cs:line 219
```

**Comment by bentoi** [comment]
Looks like dup of #650
