### ISSUE TITLE
Ice/retry failure

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#859]
I think this happens when the first timeout kicks in before the request send started, in this case we get an extra retry because invocations on connections that already contains an exception are always retry independent of the retry intervals.

We previously have a bigger timeout but it causes issue #850

```
testing invocation timeout and retries... value = 5, expected = 4
System.Exception: Exception of type 'System.Exception' was thrown.
   at Ice.retry.Instrumentation.testEqual(Int32& value, Int32 expected) in /Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-clang-default/csharp/test/Ice/retry/Instrumentation.cs:line 153
   at Ice.retry.Instrumentation.testRetryCount(Int32 expected) in /Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-clang-default/csharp/test/Ice/retry/Instrumentation.cs:line 162
   at Ice.retry.AllTests.allTests(TestHelper helper, Communicator communicator, Communicator communicator2, String rf) in /Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-clang-default/csharp/test/Ice/retry/AllTests.cs:line 293
   at Ice.retry.Client.run(String[] args) in /Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-clang-default/csharp/test/Ice/retry/Client.cs:line 36
   at Test.TestDriver.runTest[T](String[] args) in /Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-clang-default/csharp/test/TestCommon/TestHelper.cs:line 180
saved /Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-clang-default/csharp/test/Ice/retry/client-051920-1454.log
saved /Users/vagrant/workspace/ice-dist/3.7/dist-utils/build/ice/builds/ice-clang-default/csharp/test/Ice/retry/server-051920-1454.log
```

client.log
```
-- 5/19/2020 14:54:44:625 client: Network: trying to establish ssl connection to 127.0.0.1:14500
-- 5/19/2020 14:54:44:726 client: Protocol: received validate connection
   message type = 3 (validate connection)
   compression status = 0 (not compressed; do not compress response, if any)
   message size = 14
-- 5/19/2020 14:54:44:727 client: Network: established ssl connection
   local address = 127.0.0.1:56056
   remote address = 127.0.0.1:14500
-- 5/19/2020 14:54:44:727 client: Network: closed ssl connection
   local address = 127.0.0.1:56056
   remote address = 127.0.0.1:14500
   Ice.TimeoutException
-- 5/19/2020 14:54:44:727 client: Network: trying to establish ssl connection to 127.0.0.1:14500
-- 5/19/2020 14:54:44:795 client: Protocol: received validate connection
   message type = 3 (validate connection)
   compression status = 0 (not compressed; do not compress response, if any)
   message size = 14
-- 5/19/2020 14:54:44:795 client: Network: established ssl connection
   local address = 127.0.0.1:56065
   remote address = 127.0.0.1:14500
-- 5/19/2020 14:54:44:795 client: Protocol: sending request
   message type = 0 (request)
   compression status = 0 (not compressed; do not compress response, if any)
   message size = 44
   request id = 1
   identity = retry
   facet =
   operation = sleep
   mode = 2 (idempotent)
   context =
   encoding = 1.1
-- 5/19/2020 14:54:44:830 client: Network: closed ssl connection
   local address = 127.0.0.1:56065
   remote address = 127.0.0.1:14500
-- 5/19/2020 14:54:44:830 client: Retry: retrying operation call in 1ms because of exception
   Ice.ConnectionTimeoutException
-- 5/19/2020 14:54:44:831 client: Network: trying to establish ssl connection to 127.0.0.1:14500
-- 5/19/2020 14:54:44:905 client: Protocol: received validate connection
   message type = 3 (validate connection)
   compression status = 0 (not compressed; do not compress response, if any)
   message size = 14
-- 5/19/2020 14:54:44:906 client: Network: established ssl connection
   local address = 127.0.0.1:56076
   remote address = 127.0.0.1:14500
-- 5/19/2020 14:54:44:906 client: Protocol: sending request
   message type = 0 (request)
   compression status = 0 (not compressed; do not compress response, if any)
   message size = 44
   request id = 1
   identity = retry
   facet =
   operation = sleep
   mode = 2 (idempotent)
   context =
   encoding = 1.1
-- 5/19/2020 14:54:45:010 client: Network: closed ssl connection
   local address = 127.0.0.1:56076
   remote address = 127.0.0.1:14500
-- 5/19/2020 14:54:45:010 client: Retry: retrying operation call in 10ms because of exception
   Ice.ConnectionTimeoutException
-- 5/19/2020 14:54:45:023 client: Network: trying to establish ssl connection to 127.0.0.1:14500
-- 5/19/2020 14:54:45:098 client: Protocol: received validate connection
   message type = 3 (validate connection)
   compression status = 0 (not compressed; do not compress response, if any)
   message size = 14
-- 5/19/2020 14:54:45:098 client: Network: established ssl connection
   local address = 127.0.0.1:56096
   remote address = 127.0.0.1:14500
-- 5/19/2020 14:54:45:098 client: Protocol: sending request
   message type = 0 (request)
   compression status = 0 (not compressed; do not compress response, if any)
   message size = 44
   request id = 1
   identity = retry
   facet =
   operation = sleep
   mode = 2 (idempotent)
   context =
   encoding = 1.1
-- 5/19/2020 14:54:45:199 client: Network: closed ssl connection
   local address = 127.0.0.1:56096
   remote address = 127.0.0.1:14500
-- 5/19/2020 14:54:45:200 client: Retry: retrying operation call in 1ms because of exception
   Ice.ConnectionTimeoutException
-- 5/19/2020 14:54:45:201 client: Network: trying to establish ssl connection to 127.0.0.1:14500
-- 5/19/2020 14:54:45:274 client: Protocol: received validate connection
   message type = 3 (validate connection)
   compression status = 0 (not compressed; do not compress response, if any)
   message size = 14
-- 5/19/2020 14:54:45:274 client: Network: established ssl connection
   local address = 127.0.0.1:56108
   remote address = 127.0.0.1:14500
-- 5/19/2020 14:54:45:274 client: Protocol: sending request
   message type = 0 (request)
   compression status = 0 (not compressed; do not compress response, if any)
   message size = 44
   request id = 1
   identity = retry
   facet =
   operation = sleep
   mode = 2 (idempotent)
   context =
   encoding = 1.1
-- 5/19/2020 14:54:45:376 client: Network: closed ssl connection
   local address = 127.0.0.1:56108
   remote address = 127.0.0.1:14500
-- 5/19/2020 14:54:45:376 client: Retry: cannot retry operation call because retry limit has been exceeded
   Ice.ConnectionTimeoutException
```

**Comment by bentoi** [comment]
Yes, you're right. I'll put back the 200ms timeout which worked well so far... the increase of the sleep should be sufficient for fixing the original issue. If this shows up again, we could fix the test to fix the strict equality check and instead just make sure the retry count is >= 4.
