### ISSUE TITLE
C# Ice/interceptor test failure

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#920]
We got this failure on Debian buster VM (build 1044)
```
testing exceptions raised by the interceptor... ok
Now with AMD
testing simple interceptor... ok
testing retry... Process terminated. Assertion Failed
   at Test.TestHelper.Assert(Boolean b) in /home/vagrant/workspace/ice/master/csharp/test/TestCommon/TestHelper.cs:line 37
   at ZeroC.Ice.Test.Interceptor.Client.runAmdAssert(IMyObjectPrx prx, Interceptor interceptor) in /home/vagrant/workspace/ice/master/csharp/test/Ice/interceptor/Client.cs:line 95
   at ZeroC.Ice.Test.Interceptor.Client.Run(String[] args) in /home/vagrant/workspace/ice/master/csharp/test/Ice/interceptor/Client.cs:line 169
   at Test.TestDriver.RunTest[T](String[] args) in /home/vagrant/workspace/ice/master/csharp/test/TestCommon/TestHelper.cs:line 176
   at ZeroC.Ice.Test.Interceptor.Client.Main(String[] args) in /home/vagrant/workspace/ice/master/csharp/test/Ice/interceptor/Client.cs:line 183
```

**Comment by externl** [comment]
Is this still occurring?
