### ISSUE TITLE
C# Ice/binding test failure

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#921]
We got this failure on Windows 2019 vm with build 1044

```
testing per request binding with multiple endpoints and AMI... ok
testing per request binding and ordered endpoint selection... ZeroC.Ice.ConnectionLostException
 ---> System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine..
 ---> System.Net.Sockets.SocketException (10053): An established connection was aborted by the software in your host machine.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Threading.Tasks.TaskToApm.End[TResult](IAsyncResult asyncResult)
   at ZeroC.Ice.SslTransceiver.FinishRead(ArraySegment`1& buffer, Int32& offset) in C:\Users\vagrant\workspace\ice\master\csharp\src\Ice\SslTransceiver.cs:line 166
   --- End of inner exception stack trace ---
   at ZeroC.Ice.Proxy.<InvokeAsync>g__InvokeAsync|9_0(IObjectPrx proxy, OutgoingRequestFrame request, Boolean oneway, Boolean synchronous, IProgress`1 progress, CancellationToken cancel) in C:\Users\vagrant\workspace\ice\master\csharp\src\Ice\Proxy.cs:line 536
   at ZeroC.Ice.Proxy.Invoke(IObjectPrx proxy, OutgoingRequestFrame request, Boolean oneway) in C:\Users\vagrant\workspace\ice\master\csharp\src\Ice\Proxy.cs:line 321
   at ZeroC.Ice.OutgoingRequest`1.Invoke(IObjectPrx prx, OutgoingRequestFrame request) in C:\Users\vagrant\workspace\ice\master\csharp\src\Ice\OutgoingRequest.cs:line 21
   at ZeroC.Ice.OutgoingRequestWithEmptyParamList`1.Invoke(IObjectPrx prx, IReadOnlyDictionary`2 context) in C:\Users\vagrant\workspace\ice\master\csharp\src\Ice\OutgoingRequest.cs:line 56
   at ZeroC.Ice.Test.Binding.ITestIntfPrx.getAdapterName(IReadOnlyDictionary`2 context) in C:\Users\vagrant\workspace\ice\master\csharp\test\Ice\binding\msbuild\client\generated\Test.cs:line 29
   at ZeroC.Ice.Test.Binding.AllTests.allTests(TestHelper helper) in C:\Users\vagrant\workspace\ice\master\csharp\test\Ice\binding\AllTests.cs:line 601
   at ZeroC.Ice.Test.Binding.Client.Run(String[] args) in C:\Users\vagrant\workspace\ice\master\csharp\test\Ice\binding\Client.cs:line 22
   at Test.TestDriver.RunTest[T](String[] args) in C:\Users\vagrant\workspace\ice\master\csharp\test\TestCommon\TestHelper.cs:line 176
```

**Comment by externl** [comment]
Is this still occuring?
