### ISSUE TITLE
sporadic Ice/ami test failure with Android emulator

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice#93]
This occurs when running the android tests on macOS.

```
[ running client/server test - 05/31/18 08:37:14 ]
- Config: ssl,ipv6,mx,androidemulator
testing begin/end invocation... ok
testing local exceptions... ok
testing sent callback... ok
testing sent async callback... ok
testing unexpected exceptions... ok
testing batch requests with proxy... ok
testing batch requests with connection... ok
testing batch requests with communicator... ok
testing future operations... ok
testing graceful close connection with wait... null: unknown exception
java.util.concurrent.CompletionException: com.zeroc.Ice.ConnectionLostException
    error = 0
	at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:348)
	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1931)
	at test.Ice.ami.AllTests.allTests(AllTests.java:995)
	at test.Ice.ami.Client.run(Client.java:17)
	at test.Util.Application.main(Application.java:100)
	at test.Util.Application.main(Application.java:42)
	at com.zeroc.testcontroller.ControllerApp$MainHelperI.run(ControllerApp.java:366)
Caused by: com.zeroc.Ice.ConnectionLostException
    error = 0
	at com.zeroc.IceInternal.StreamSocket.read(StreamSocket.java:193)
	at com.zeroc.IceInternal.StreamSocket.read(StreamSocket.java:154)
	at com.zeroc.IceInternal.TcpTransceiver.read(TcpTransceiver.java:63)
	at com.zeroc.IceSSL.TransceiverI.read(TransceiverI.java:225)
	at com.zeroc.Ice.ConnectionI.read(ConnectionI.java:3000)
	at com.zeroc.Ice.ConnectionI.message(ConnectionI.java:995)
	at com.zeroc.IceInternal.ThreadPool.run(ThreadPool.java:417)
	at com.zeroc.IceInternal.ThreadPool.access$500(ThreadPool.java:12)
	at com.zeroc.IceInternal.ThreadPool$EventHandlerThread.run(ThreadPool.java:786)
	at java.lang.Thread.run(Thread.java:761)
unexpected exit status: expected: 0, got 1
```

**Comment by bentoi** [comment]
We now test Android on a device so it's no longer relevant.
